project:
  type: website
  post-render:
    - Rscript copy-feed.R
  resources:
    - _Statbook
    - Figures
    - _StatbookEng
    - agriCensData
    - CVA
    - lmDiallel
    - nonLInearRegression
    - PCA
    - seedTutorial
    - nonLinearRegression
    - tags
bibliography: _MyLibrary.bib
csl: _weed-research.csl
website:
  description: "Fixing the bridge between biologists and statisticians"
  site-url: https://www.statforbiology.com # you must change this appropriately for RSS feeds to work properly
  google-analytics: "G-GPNY1W5GL5"
  title: "Statforbiology"
  navbar:
    left:
      - aboutThis.qmd
      - about.qmd
      - text: "Posts"
        href: index.html
      - tutorials.qmd
      - Rpackages.qmd
      - links.qmd
    right:  
      - icon: github
        href: https://github.com/OnofriAndreaPG
      - icon: bluesky
        href: https://bsky.app/profile/statforbiology.bsky.social
  page-footer:
      center: |
         <hr/><br/>
         Copyright © 2018-2026 by Andrea Onofri is licensed under 
         [CC BY 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
         <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1">
         <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1">
         <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1">
         <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1">
         This site was built with Quarto.
      # right: "Built with Quarto"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    code-block-bg: "#F4F4F4" # Or true for default light grey
    code-block-border-left: "#31BAE9" # Optional colored border

editor: source

