baseurl = "https://www.statforbiology.com"
# Enable analytics by entering your Google Analytics tracking ID
GoogleAnalytics = "UA-131792052-1"

title = "Fixing the bridge between biologists and statisticians"

[params.author]
name = "Andrea Onofri"
email = "andrea.onofri@unipg.it"

copyright = "Copyright © 2026, @AndreaOnofri"
canonifyurls = true
pagination.pagerSize = 10

theme = "hugo-blog-jeffprod"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:contentbasename"
    
[taxonomies]
    tag = "tags"
    archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

