baseurl = "/"
languageCode = "en-us"
title = "Models are wrong ..."
author = "@JeffProd"
copyright = "Copyright © 2008–2018, @JeffProd"
paginate = 3
theme = "hugo-blog-jeffprod"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
    
[params]
    description = "A blog built through Hugo and blogdown."
    footer = "&copy; Andrea Onofri -- 2018 | [Github](https://github.com/OnofriAndreaPG) | [e-mail](mailto:andrea.onofri@unipg.it)"
