baseurl = "https://www.statforbiology.com"
# Enable analytics by entering your Google Analytics tracking ID
GoogleAnalytics = "UA-131792052-1"

title = "The broken bridge between biologists and statisticians"
author = "Andrea Onofri"
copyright = "Copyright © 2023, @AndreaOnofri"
canonifyurls = true
paginate = 10

theme = "hugo-blog-jeffprod"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:filename"
    
[taxonomies]
    tag = "tags"
    archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
