baseurl = "/"
title = "The broken bridge between biologists and statisticians"
author = "Andrea Onofri"
copyright = "Copyright © 2018, @AndreaOnofri"
canonifyurls = true
paginate = 3

theme = "hugo-blog-jeffprod"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:filename"
    
[taxonomies]
    tag = "tags"
    archive = "archives"
