---
title: "Companion R Packages"
author: "Andrea Onofri"
date: 2019-05-30
menu: "main"
bibliography: __MyLibrary.bib
csl: weed-research.csl
tags: 
   - aomisc
   - drcSeedGerm
   - agriCensData
   - drcte
---

This blog is supported by a few R packages containing all functions, datasets and other utilities, which are necessary to work through posts, tutorials and books. The packages are:

* [statforbiology](https://github.com/OnofriAndreaPG/statforbiology)
* [aomisc](https://github.com/OnofriAndreaPG/aomisc)
* [AgriCensData](https://github.com/OnofriAndreaPG/agriCensData)
* [drcSeedGerm](https://github.com/OnofriAndreaPG/drcSeedGerm)
* [drcte](https://github.com/OnofriAndreaPG/drcte)
* [lmDiallel](https://github.com/OnofriAndreaPG/lmDiallel)

The three packages 'drcSeedGerm', 'drcte' and 'lmDiallel' are already hosted on CRAN and they can be installed from within RStudio, by using the usual 'install.package()' function. For all packages, the development versions are hosted on gitHub and they can be installed from there. To do so, you need the 'devtools' package, so, if necessary, install this package first. Next, load this library and use the 'install_github()' function to install the three packages. For any problem, please, [email me](mailto:andrea.onofri@unipg.it)

```
# Installing the development versions
install.packages("devtools")
library(devtools)
install_github("OnofriAndreaPG/statforbiology")
install_github("OnofriAndreaPG/aomisc")
install_github("OnofriAndreaPG/agriCensData")
install_github("OnofriAndreaPG/drcSeedGerm")
install_github("OnofriAndreaPG/lmDiallel")
```

