{
  "hash": "607e9402fd2108fabf02cb0f9b1a00ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How do we combine errors, in biology? The delta method\"\nauthor: \"Andrea Onofri\"\ndate: \"2025-12-12\"\ncategories:\n   - R\n   - general\n   - 'R-bloggers'\ntags:\n   - R\n   - delta_method\n   - Error_propagation\naliases:\n  - /2024/stat_general_thedeltamethod_edited/index.html\n  - /2024/stat_general_thedeltamethod/index.html\n---\n\n\n\n\n\n\nIn a recent post I have shown that we can build linear combinations of model parameters ([see here](https://www.statforbiology.com/2024/stat_general_errorpropagation/) ). For example, if we have two parameter estimates, say $X$ and $Z$, with standard errors respectively equal to $\\sigma_X$ and $\\sigma_Z$ and a covariance of $\\sigma_{XZ}$ we can build a linear combination as follows:\n\n$$ Y = f(X,Z) = aX + bZ + c$$\n\nwhere $a$, $b$ and $c$ are three numeric constants. The standard error for this combination can be obtained as:\n\n$$ \\sigma_Y = \\sqrt{ a^2 \\sigma^2_X + b^2 \\sigma^2_Z + 2ab \\, \\sigma_{XZ} }$$\n\nIn biology, nonlinear transformations are much more frequent than linear transformations. Nonlinear transformations are, e.g., $Y = f(X,Z) = exp(X, Z)$, or, $Y = 1/(X + Z)$; we may wonder: what is the standard error for these nonlinear transformations? The solution to this problem is named the 'delta method' and may be beyond biologists with an average level of statistical proficiency. I thought it might be useful to talk about it, by using a very simple language and a few examples.\n\nLet's start with the transformation of a single variable $Y = f(X)$.\n\n# Example 1: The half-life of a herbicide\n\nA herbicide has proven to follow a first order degradation kinetic in soil, with constant degradation rate $X = -0.035$ and standard error equal $\\sigma_X = 0.00195$. What is the half-life of this herbicide and its standard error?\n\nEvery pesticide chemist knows that the half-life is derived by the degradation rate, according to the following equation:\n\n$$ y = \\frac{\\log(0.5)}{x}$$\n\nTherefore, if we plug-in x = X, the half-life of our herbicide is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY <- log(0.5)/-0.035\nY\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.80421\n```\n\n\n:::\n:::\n\n\nBut ... what is the standard error of this half-life? There is some uncertainty around the estimate of $Y$ and it is clear that such an uncertainty should propagate to the estimate of $Z = f(Q)$; unfortunately, the transformation is nonlinear and we cannot use the expression given above for linear transformations.\n\n### The basic idea beyond the delta method\n\nThe basic idea behind the delta method is that most of the simple nonlinear functions, which we use in biology, can be locally approximated by the tangent line through a point of interest. For example, our nonlinear half-life function is $y  = f(x) = \\frac{\\log(0.5)}{x}$ and, obviously, we are interested in the point where $x = X = -0.035$. In the graph below, we have represented our nonlinear function (in black) and its tangent line (in red) through the above point: we can see that the approximation is fairly good in the close vicinity of $Q = -0.035$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](general_DeltaMethod_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nWhat is the equation of the tangent line? In general, if the nonlinear function is $f(x)$, you may remember from high school that the slope $m$ of the tangent line is equal to the first derivative of $f(x)$, that is $f'(x)$. You may also remember that the equation of a line with slope $m$ through the point $P(X, Y)$ is $y - Y = m(x - X)$. As $Y = f(X)$, the tangent line has equation:\n\n$$y = f(X) + f'(Y)(x - X)$$\n\n### We need the derivative!\n\nIn order to write the equation of the red line in the Figure above, we need to consider that $X = -0.035$ and we need to be able to calculate the first derivative of our nonlinear half-life fuction. I am not able to derive the expression of the first derivative for all nonlinear functions and it was a relief for me to discover that R can handle this task in simple ways, e.g. by using the function `D()`. For our case, it is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD(expression(log(0.5)/X), \"X\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-(log(0.5)/X^2)\n```\n\n\n:::\n:::\n\n\nTherefore, we can use this R function to calculate the slope $m$ of the tangent line in the figure above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- -0.035\nm <- eval( D(expression(log(0.5)/X), \"X\") )\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 565.8344\n```\n\n\n:::\n:::\n\n\nWe already know that $f(-0.035) = 19.80421$. Therefore, we can write the equation of the tangent line (red line in the graph above):\n\n$$y = 19.80421 + 565.8344 \\, (x + 0.035)$$\n\nthat is:\n\n$$y = 19.80421 + 565.8344 \\, x + 565.8344 \\cdot 0.035 = 39.60841 + 565.8344 \\, x$$\n\n### Replacing a curve with a line\n\nNow, we have two functions:\n\n1. the original nonlinear half-life function $y = \\log(0.5)/x$$\n2. a new linear function ($y = 39.60841 + 565.8344 \\, x$), that is a very close approximation to the previous one, at least near to the point $X = -0.035$, which we are interested in.\n\nTherefore, we can approximate the former with the latter! If we use the linear function, we see that the half-life is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n39.60841 + 565.8344 * -0.035\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.80421\n```\n\n\n:::\n:::\n\n\nwhich is what we expected. The advantage is that we can now use the low of propagation of errors to estimate the standard error (see the first and second equation in this post):\n\n\n$$ \\sigma_{ \\left[ 39.60841 + 565.8344 \\, X \\right]} = \\sqrt{ 562.8344^2 \\, \\sigma^2_X}$$\n\nHere we go:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt( m^2 * (0.00195 ^ 2) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.103377\n```\n\n\n:::\n:::\n\n\n## In general...\n\nIf we have a nonlinear transformation $f(X)$, the standard error for this transformation is approximated by knowing the first derivative $f'(X)$ and the standard error of $X$:\n\n$$\\sigma_{G(X)}  \\simeq \\sqrt{ [f'(X)]^2 \\, \\sigma^2_X }$$\n\n# Example 2: a back-transformed count\n\nA paper reports that the mean number of microorganisms in a substrate, on a logarithmic scale, was $X = 5$ with standard error $\\sigma = 0.84$. It is easy to derive that the actual number of micro-organisms was $\\exp{5} = 148.4132$; what is the standard error of the back-transformed mean?\n\nThe first derivative of our nonlinear function is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nD(expression(exp(X)), \"X\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nexp(X)\n```\n\n\n:::\n:::\n\n\nand thus the slope of the tangent line is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- 5\nm <- eval( D(expression(exp(X)), \"X\") )\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 148.4132\n```\n\n\n:::\n:::\n\n\nAccording to the function above, the standard error for the back-transformed mean is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 0.84\nsqrt( m^2 * sigma^2 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 124.6671\n```\n\n\n:::\n:::\n\n\n\n# Example 3: Selenium concentration in olive drupes\n\nWhen the combination is nonlinear and involves two parameters, such as:\n\n$$Y = \\frac{X}{Z} \\quad \\textrm{or} \\quad Y = X \\, Z$$\n\nthe delta method requires a slightly more complex formula, which we will see by using another example.\n\nThe concentration of selenium in olive drupes was found to be $3.1 \\, \\mu g \\,\\, g^{-1}$ with standard error equal to 0.8. What is the intake of selenium when eating one drupe? Please, consider that one drupe weights, on average, 3.4 g (SE = 0.31) and that selenium concentration and drupe weight show a covariance of 0.55.\n\nThe amount of selenium is easily calculated as:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- 3.1; Z = 3.4\nY <- X * Z\nY\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.54\n```\n\n\n:::\n:::\n\n\nDelta standard errors can be obtained by considering the partial derivatives for each of the two variables and combining them as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndX <- eval( D(expression(X * Z), \"X\") )\ndZ <- eval( D(expression(X * Z), \"Z\") )\n\nsigmaX <- 0.8; sigmaZ <- 0.31; sigmaXZ <- 0.55\nsqrt( (dX^2) * sigmaX^2 + (dZ^2) * sigmaZ^2 + 2 * dX * dZ * sigmaXZ )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.462726\n```\n\n\n:::\n:::\n\n\nIn general terms, when $y = f(x, z)$ and it is nonlinear, it is:\n\n$$ \\sigma_y = \\sqrt{ (f'_x)^2 \\, \\sigma^2_x + (f'_z)^2 \\, \\sigma^2_z + 2f'_x\\,f'_z \\, \\sigma_{xz} }$$\n\n\nFor those of you who would like to get involved with matrix notation: we can reach the same result via matrix multiplication (see below). This might be easier when we have more than two variables to combine.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nder <- matrix(c(dX, dZ), 1, 2)\nsigma <- matrix(c(sigmaX^2, sigmaXZ, sigmaXZ, sigmaZ^2), 2, 2, byrow = T)\nsqrt( der %*% sigma %*% t(der) )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 4.462726\n```\n\n\n:::\n:::\n\n\n# The delta method with R\n\nIn R there is a shortcut function to calculate delta standard errors, that is available in the 'car' package. In order to use it, we need to have:\n\n1. a named vector for the variables that we have to combine\n2. an expression for the transformation\n3. a variance-covariance matrix\n\nFor the first example, we have:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobj <- c(\"X\" = -0.035)\nsigma <- matrix(c(0.00195^2), 1, 1)\n\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\ndeltaMethod(object = obj, g=\"log(0.5)/X\", vcov = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Estimate      SE   2.5 % 97.5 %\nlog(0.5)/X  19.8042  1.1034 17.6416 21.967\n```\n\n\n:::\n:::\n\n\nFor the second example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobj <- c(\"X\" = 5)\nsigma <- matrix(c(0.84^2), 1, 1)\ndeltaMethod(object = obj, g=\"exp(X)\", vcov = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Estimate     SE  2.5 % 97.5 %\nexp(X)   148.41 124.67 -95.93 392.76\n```\n\n\n:::\n:::\n\n\nFor the third example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobj <- c(\"X\" = 3.1, \"Z\" = 3.4)\nsigma <- matrix(c(0.8^2, 0.55, 0.55, 0.31^2), 2, 2, byrow = T)\ndeltaMethod(object = obj, g=\"X * Z\", vcov = sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Estimate      SE   2.5 % 97.5 %\nX * Z  10.5400  4.4627  1.7932 19.287\n```\n\n\n:::\n:::\n\n\n\nThe function 'deltaMethod()' is very handy to be used in connection with model objects, as we do not need to provide anything, but the transformation function. But this is something that requires another post!\n\nHowever, two final notes relating to the delta method need to be pointed out here:\n\n1. the delta standard error is always approximate;\n2. if the original variables are gaussian, the transformed variable, usually, is not gaussian.\n\nThanks for reading—and don’t forget to check out my new book below!\n\nAndrea Onofri   \nDepartment of Agricultural, Food and Environmental Sciences        \nUniversity of Perugia (Italy)        \nSend comments to: [andrea.onofri@unipg.it](mailto:andrea.onofri@unipg.it)  \n\n<a href = \"https://www.awin1.com/cread.php?awinmid=26429&awinaffid=2675822&ued=https%3A%2F%2Flink.springer.com%2Fbook%2F10.1007%2F978-3-032-08199-5\"><img src= \"../../Figures/Email_Signature_978-3-032-08199-5.png\" align=\"center\" alt=\"Book cover\" class=\"cover\" /></a>\n<br/>\n\n\n# Reference\n\n1. Beyene, J., Moineddin, R., 2005. Methods for confidence interval estimation of a ratio parameter with application to location quotients. BMC Med Res Methodol 5, 32. https://doi.org/10.1186/1471-2288-5-32\n\n\n---\nPost written on 25/5/2019 and edited on 22/11/2024 and 12/12/2025\n",
    "supporting": [
      "general_DeltaMethod_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}