---
title: 'Analysing seed germination and emergence data with R (a tutorial). Part 1'
author: "Andrea Onofri"
date: 2021-10-07
slug: 'Time_to_event_models'
categories:
  - R
  - 'Time_to_event_models'
tags:
  - R
  - 'Time_to_event_models'
  - 'Seed_germination'
  - drcte
  - drcSeedGerm
archives:
  - 2021
---


```{r setup, cache = F, echo = F}
#Put at the beginning
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
knitr::knit_hooks$set(document = function(x){ 
  gsub("```\n*```r*\n*", "", x) 
})
```

# Introduction to the tutorial

Germination/emergence assays are relatively easy to perform, by following standardised procedures, as described, e.g., by the International Seed Testing Association ([see here](https://www.ingentaconnect.com/content/ista/rules/2019/00002019/00000001) ). In short, we take a sample of seeds and we put them in an appropriate container. We put the container in the right environmental conditions (e.g., relating to humidity content and temperature) and we inspect the seeds according to a regular schedule (e.g., daily). At each inspection, we count the number of germinated/emerged seeds and remove them from the containers; inspections are performed until no new germinations/emergences are observed for a sufficient amount of time.

We see that these assays are rather simple, but, in spite of such simplicity, the process of data analysis still presents several grey areas. How should we quantify the germination/emergence process? How should we compare the germination/emergence of different seed lots?

A brief survey of literature shows that a plethora of methods is used, which is certainly encouraged by the wide availability of computer packages. Some of these methods have been around for quite a while (e.g., the use of germination indices or nonlinear regression), some others are relatively new (e.g., methods from survival analysis). It is clear that not all these methods are efficient or reliable, especially when they are used with little concern about the basic assumptions that each method makes.

Furthermore, the use of a lot of different methods of data analysis by different research groups may serve the purpose of creativity, but are we really sure that it also serves the purpose of advancing science? Wouldn't it be better if we could use the same reliable methods of data analysis, so that we could better understand each other, compare our results and pool them together?

Therefore, together with some collegues, we decided to start defining a framework for the analysis of germination and emergence data, which might help the readers to select efficient and reliable methods and, lately, improve comparisons and communication of results within the scientific community. We decided to structure this framework as the combination of (i) a step-by-step procedure (ii) the methods to accomplish it and (iii) a user friendly software interface, based on a new R package.

This is the first of a coming series of webpages, aimed at presenting the framework and related methods, provide examples together with commented R code and datasets. The webpages can be found by using the following link: [https://www.statforbiology.com/tags/drcte/](https://www.statforbiology.com/tags/drcte/): 


# The R package

The analyses we propose for seed germination/emergence assays can be performed by using our new R package, namely `drcte`. This package is heavily based on the 'drc' package (Ritz et al., 2015), that is a very flexible software for general model fitting purposes. Although `drc` contains, already, several  basic functions for time-to-event analyses, we felt that, in order to meet the specific needs of agricultural research, it would be useful to make some further customisation and develop some additional functions, which we implemented in the 'drcte' package. Furthermore, we also created the `drcSeedGerm` package, that contains specific functions for seed germination/emergence assays.

Both the `drcte` and `drcSeedGerm` packages can be downloaded and installed from gitHub, by using the code proposed in the box below. It requires the 'devtools' package, that needs to be as well installed, if it is not already included in the system.

```
install.packages("devtools")
library(devtools)
install_github("OnofriAndreaPG/drcte")
install_github("OnofriAndreaPG/drcSeedGerm")
```

We do hope you may find the package and tutorial useful to your purposes.

Please, stay tuned for further posts.

Prof. Andrea Onofri   
Department of Agricultural, Food and Environmental Sciences    
University of Perugia (Italy)    
Send comments to: [andrea.onofri@unipg.it](mailto:andrea.onofri@unipg.it)

<a href="https://twitter.com/onofriandreapg?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @onofriandreapg</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

---

# References

1. Ritz, C., Baty, F., Streibig, J. C., Gerhard, D. (2015) Dose-Response Analysis Using R PLOS ONE, 10(12), e0146021

