<!DOCTYPE html>
<html lang="en">
<head>
  
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131792052-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-131792052-1');
  </script>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>The broken bridge between biologists and statisticians  | Sample variance and population variance: which of the two?</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link rel="stylesheet" href="https://www.statforbiology.com/css/blog.css" />
    <script type="text/javascript"
      src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>    
</head>
<body>

    
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://www.statforbiology.com">Home</a>
            <a class="navbar-item" href="https://www.statforbiology.com/aboutthis" >About this site</a>
            <a class="navbar-item" href="https://www.statforbiology.com/tutorials" >Tutorials</a>
            <a class="navbar-item" href="https://www.statforbiology.com/_Statbook" >Book (Italian)</a>
            <a class="navbar-item" href="https://www.statforbiology.com/_StatbookEng" >Book (English)</a>
            <a class="navbar-item" href="https://www.statforbiology.com/rpackages" >R packages</a>
            <a class="navbar-item" href="https://www.statforbiology.com/links" >Links</a>
            <a class="navbar-item" href="https://www.statforbiology.com/about" >About me</a>
        </div>
    </nav>
    

    
    <section class="hero is-info is-medium">
        <div class="hero-body" style="background-image: url(https://www.statforbiology.com/img/bg-blog.jpg);">
            <div class="container has-text-centered">
                <br>
                <h1 class="title is-size-1">
                    
                        Sample variance and population variance: which of the two?
                    
                </h1>
                
            </div>
        </div>
    </section>



<div class="container">
    <div class="section">
    

<div class="columns">
    <div class="column is-9">
        <div class="tile is-child box">
          <p class="subtitle is-size-6 has-text-grey-light">
          Andrea Onofri &middot;&nbsp; Added on November 9, 2018 &middot;
          <i class="far fa-clock"></i>&nbsp;7 min read 
          </p><hr/>
            <div class="content">
                


<p>Teaching experimental methodology in agriculture related master courses poses some peculiar problems. One of these is to explain the difference between sample variance and population variance. For the students it is usually easy to grasp the idea that, being the mean the ‘center’ of the dataset, it is relevant to measure the average distance to the mean for all individuals in the dataset. Of course, we need to take the sum of squared distances, otherwise negative and positive residuals cancel each other out.</p>
<p>It is also very intuitive that the average of squared residuals (mean square or variance) is calculated by using the following expression:</p>
<p><span class="math display">\[{\sigma ^2} = \frac{\sum\limits_{i = 1}^n ({X_i} - \mu )^2}{n}\]</span></p>
<p>However, this is not what R (and other software) does. R divides by <span class="math inline">\(n - 1\)</span> and, at this stage, the students usually ask: “<em>why are you telling me that I have to divide the sum of squares by <span class="math inline">\(n - 1\)</span>, instead of <span class="math inline">\(n\)</span>? I have <span class="math inline">\(n\)</span> squared residuals, not <span class="math inline">\(n - 1\)</span>!</em>”.</p>
<p>You may think that the answer is pretty obvious. I don’t think so. The concept of variance is introduced at the beginning of the course, within the frame of descriptive statistics. At this stage, the students know nothing about probability distributions, sampling, inference and all the related concepts. They do not even know anything about degrees of freedom, yet!</p>
<p>If I were a mathematician and were facing students in math/stat, I could show the class how clever I am by giving a formal proof that <span class="math inline">\(n - 1\)</span> is the correct denominator in most circumstances. In particular, this is true when we have a sample taken from a population and we want to infere the variance of the population by using the sample. The formal proof can be found in most stat books and I am attaching it at the end of this post. However, I will never show this formal proof to my students at this stage. Indeed, such a proof assumes that the students know what a sampling distribution is, what the standard error is and how it is calculated. Furthermore, students in agriculture are usually very reluctant, when it comes to dealing with maths!</p>
<p>Therefore, I usually refrain from trying to appear more clever than I am. My question: “is it possible to teach the difference between the population variance and the sample variance, without talking about degrees of freedom or other ‘difficult’ concepts?”. Here is how I try to put it.</p>
<p>Let’s take a big, but finite population, i.e. an hectar of maize plants (roughly 70,000 plants). Let’s imagine that we know the individual yields for all plants in the population. With R we can get those yields by taking random values in the interval from 150 to 250 grams (this is reasonable… students in agriculture know these things pretty well! And, I am not referring to any density distribution… it would be too much at this stage).</p>
<pre class="r"><code>set.seed(1234)
pop &lt;- runif(70000, min = 150, max = 250)</code></pre>
<p>We now have our population (I will not show it… lack of space!). It is a finite population, so we can easily calculate the mean and the variance, i.e. the mean squared distance of all 70,000 individuals to the mean. You see that I am using the equation above (with <span class="math inline">\(n\)</span> underneath).</p>
<pre class="r"><code>mean(pop)</code></pre>
<pre><code>## [1] 200.0893</code></pre>
<pre class="r"><code>sigma2 &lt;- sum( ( pop - mean(pop) )^2 )/70000
sigma2</code></pre>
<pre><code>## [1] 835.184</code></pre>
<p>Let’s now forget about the population. In the field, we would never be able to measure the yield for all the plants in one hectar, due to lack of resources (time and money). Therefore, let’s measure 10 randomly selected plants (one in 7000; samples are often small in agriculture!). We can do this easily in R by sampling the original population.</p>
<pre class="r"><code>x &lt;- sample(pop, 10)
x</code></pre>
<pre><code>##  [1] 237.7442 242.4557 243.2478 152.7499 246.9411 154.4087 226.4784
##  [8] 236.2380 216.2226 187.3896</code></pre>
<p>We now calculate the mean and the variance for the sample, by using the equation above (i.e. using <span class="math inline">\(n = 10\)</span> as the denominator).</p>
<pre class="r"><code>mean(x)</code></pre>
<pre><code>## [1] 214.3876</code></pre>
<pre class="r"><code>sigma2_s &lt;- sum( ( x - mean(x) )^2 )/10
sigma2_s</code></pre>
<pre><code>## [1] 1197.856</code></pre>
<p>We do not know the population but we know our sample. As usual, in lack of other information, we conclude that the population should have the same characteristics of our sample. This is usually seen as a reasonable guess; at least the most reasonable one. The procedure we use to make a guess is called ‘estimator’ and the guess in itself is an ‘estimate’. Have we used a good estimator?</p>
<p>We can’t answer. Unless we repeat the sampling process for a lot of times and see how our estimates behave in the long run. Our estimator is good if, in the long run, it converges on the real value for the population. Let’s check this: we repeatedly take samples of 10 plants from our population and calculate the mean and variance as above. We repeat this process 10,000 times, storing the 10,000 means and variances in two vectors.</p>
<pre class="r"><code>meanS &lt;- c(); varS &lt;- c()
for(i in 1:10000){
  x &lt;- sample(pop, 10)
  meanS[i] &lt;- mean(x)
  varS[i] &lt;- sum( ( x - mean(x) )^2 )/10
}
mean(meanS)</code></pre>
<pre><code>## [1] 200.0309</code></pre>
<pre class="r"><code>mean(varS)</code></pre>
<pre><code>## [1] 753.4311</code></pre>
<p>We see that the mean of the means is 200.03. We got really very close to the real mean of the population. Indeed, the mean of the sample is a good (unbiased) estimator of the mean of the population.</p>
<p>On the other hand, the mean of the variances is 753.43. Please note that this is much smaller than the real variance of the population. It means that if we use the equation above (with <span class="math inline">\(n\)</span> at the denominator) to calculate the variance for the sample, we do not have a good estimator of the variance for the whole population. We can now look at the ratio between the variance of the population and our guess in the long run:</p>
<pre class="r"><code>var(pop)/mean(varS)</code></pre>
<pre><code>## [1] 1.108523</code></pre>
<p>We see that this is roughly equal to <span class="math inline">\(10/9\)</span>. In other words, if we:</p>
<ol style="list-style-type: decimal">
<li>take the sample and calculate the variance by using the equation above,</li>
<li>multiply by <span class="math inline">\(n = 10\)</span> and</li>
<li>divide by <span class="math inline">\(n - 1 = 9\)</span></li>
</ol>
<p>we can get a good estimator. This leads us to the following equation:</p>
<p><span class="math display">\[{\sigma ^2} = \frac{\sum\limits_{i = 1}^n ({X_i} - m )^2}{n - 1}\]</span></p>
<p>that is exactly the variance for the sample. This one we can easily calculate with R.</p>
<div id="which-of-the-two-then" class="section level1">
<h1>Which of the two, then?</h1>
<p>Just rememeber:</p>
<ol style="list-style-type: decimal">
<li>the variance (mean square) is calculated by dividing the sum of squared residuals by <span class="math inline">\(n\)</span>. This makes sense, because we have <span class="math inline">\(n\)</span> squared residuals.</li>
<li>However, if we have a random sample taken from a population, and if our aim is to estimate the variance for the whole population, we need to divide the sum of squared residuals by <span class="math inline">\(n - 1\)</span>. Otherwise, we get an understimation.</li>
</ol>
</div>
<div id="the-formal-proof-look-how-clever-i-am" class="section level1">
<h1>The formal proof (look how clever I am!)</h1>
<p>We have a population with mean equal to <span class="math inline">\(\mu\)</span> and variance equal to <span class="math inline">\(\sigma^2\)</span>. Let’s take a sample with its mean <span class="math inline">\(m \neq \mu\)</span> and <span class="math inline">\(m - \mu = \varepsilon\)</span>. For the population, we can write:</p>
<p><span class="math display">\[\sum\limits_{i = 1}^n (X_i - \mu )^2  = \sum\limits_{i = 1}^n (X_ i - m + \varepsilon)^2 = \sum\limits_{i = 1}^n ({X_i} - m)^2 + n \varepsilon^2\]</span></p>
<p>We already see that the sum of squared residuals is higher if we take <span class="math inline">\(m\)</span> instead of <span class="math inline">\(\mu\)</span>, unless <span class="math inline">\(\varepsilon = 0\)</span>, i.e. <span class="math inline">\(m = \mu\)</span>. From the above, we derive</p>
<p><span class="math display">\[\sum\limits_{i = 1}^n (X_i - \mu)^2 =  \sum\limits_{i = 1}^n (X_i - \mu )^2  - n ( {m - \mu } )^2\]</span></p>
<p>If we consider the first equation above (variance for the population) we have</p>
<p><span class="math display">\[\sum\limits_{i = 1}^n (X_i - \mu)^2 =  n \sigma^2 - n( m - \mu  )^2\]</span></p>
<p>We see that the rightmost term of this equation (<span class="math inline">\(n ( m - \mu )^2\)</span> is the sum of squared distances for the sampling distribution of the mean. That is <span class="math inline">\(n\)</span> times the squared standard error. Therefore:</p>
<p><span class="math display">\[\sum\limits_{i = 1}^n {{{({X_i} - \bar X)}^2} = } n{\sigma ^2} - n\left( {\frac{{{\sigma ^2}}}{n}} \right)\]</span></p>
<p>and</p>
<p><span class="math display">\[\sum\limits_{i = 1}^n {{{({X_i} - \bar X)}^2} = } (n - 1){\sigma ^2}\]</span></p>
<p>Here we go! Indeed:</p>
<p><span class="math display">\[ \frac{\sum\limits_{i = 1}^n (X_i - m)^2 }{n - 1} = {\sigma ^2}\]</span></p>
</div>

            </div>
        </div>
    </div>
    <div class="column is-3">
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Tags</h1>
        <div class="tags">
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/agricensdata">agricensdata</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/ammi_analysis">ammi_analysis</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/aomisc">aomisc</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/asreml">asreml</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/bayesian_stat">bayesian_stat</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/blogdown">blogdown</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/boxplot">boxplot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/correlation">correlation</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/data_management">data_management</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/delta_method">delta_method</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/descriptive_statistics">descriptive_statistics</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/diallel_models">diallel_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/dplyr">dplyr</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/drcseedgerm">drcseedgerm</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/drcte">drcte</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/drm">drm</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/error_propagation">error_propagation</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/gnlht">gnlht</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/jags">jags</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/linear_models">linear_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/lmdiallel">lmdiallel</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/lme">lme</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/long_term_experiments">long_term_experiments</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/mixed_models">mixed_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/multi_environment_studies">multi_environment_studies</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/nlme">nlme</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/nls">nls</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/nonlinear_regression">nonlinear_regression</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/percentiles">percentiles</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/qq_plot">qq_plot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/r">r</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/seed_germination">seed_germination</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/split_plot">split_plot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/tidyverse">tidyverse</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/time_to_event_models">time_to_event_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/variance">variance</a></span>
        
        </div>          
    </div>
</div><br>
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Recent posts</h1>
        
            <h1><a href="https://www.statforbiology.com/2021/stat_drcte_2-methods/">Analysing seed germination and emergence data with R (a tutorial). Part 2</a></h1>
            <time class="has-text-grey-light is-size-7">9 October 2021</time>
        
            <h1><a href="https://www.statforbiology.com/2021/stat_drcte_1-intro/">Analysing seed germination and emergence data with R (a tutorial). Part 1</a></h1>
            <time class="has-text-grey-light is-size-7">7 October 2021</time>
        
            <h1><a href="https://www.statforbiology.com/2021/stat_nls_speciesarea/">Why are derivatives important in biology? A case-study with nonlinear regression</a></h1>
            <time class="has-text-grey-light is-size-7">9 June 2021</time>
        
            <h1><a href="https://www.statforbiology.com/2021/stat_seedgermination_htt2step/">Other useful functions for nonlinear regression: threshold models and all that</a></h1>
            <time class="has-text-grey-light is-size-7">1 May 2021</time>
        
            <h1><a href="https://www.statforbiology.com/2021/stat_nls_r2/">The R-squared and nonlinear regression: a difficult marriage?</a></h1>
            <time class="has-text-grey-light is-size-7">25 March 2021</time>
        
    </div>
</div>
    <br>
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Archives</h1>
        
            <a href="https://www.statforbiology.com/archives/2021">2021</a> (11)<br>
        
            <a href="https://www.statforbiology.com/archives/2020">2020</a> (14)<br>
        
            <a href="https://www.statforbiology.com/archives/2019">2019</a> (14)<br>
        
            <a href="https://www.statforbiology.com/archives/2018">2018</a> (2)<br>
        
            <a href="https://www.statforbiology.com/archives/2014">2014</a> (1)<br>
        
    </div>
</div>

    </div>
</div>


    </div>
</div>
<footer class="footer has-background-grey-darker has-text-white">
    <div class="content has-text-centered">
        <p>
             <span class="icon is-large"><a href="mailto:andrea.onofri@unipg.it" class="mysocial"><i class="far fa-envelope-open fa-3x"></i></a></span>&nbsp;&nbsp;
            <span class="icon is-large"><a href="https://github.com/OnofriAndreaPG/" class="mysocial"><i class="fab fa-github fa-3x"></i></a></span>&nbsp;&nbsp;
           <span class="icon is-large"><a href="https://twitter.com/onofriandreapg" class="mysocial"><i class="fab fa-twitter fa-3x"></i></a></span>&nbsp;&nbsp;
            <span class="icon is-large"><a href="https://www.r-project.org/" class="mysocial"><i class="fab fa-r-project fa-3x"></i></a></span>&nbsp;&nbsp;
 
            <br><br>
            Copyright &copy; The broken bridge between biologists and statisticians, 2021 - Theme by <a href="https://jeffprod.com" class="mysocial">JeffProd.com</a>
            - <a class="mysocial" href="https://www.statforbiology.com/aboutThis">About this site</a>
        </p>
    </div>
</footer>

<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
</body>
</html>
