---
title: Metodologia sperimentale e trattamento statistico dei dati, con applicazioni in R
author: "Andrea Onofri"
date: 2024-06-07
menu: Main
subtitle: "Catania, 10-14/06/2024"
output: 
  html_document:
    theme: bootstrap
    highlight: tango
    toc: no
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

---

# Impiego (non proprio) di base di R

1. [Introduzione ad R](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EVvRUb9UQQ5Pi3nd38g8cJkB849jOhfq3KrmIeM-8BDyeg?e=1Rp7Fc)
2. [Gestione dei dati con R](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EW5uidkZEuxFkF_drmWxmCQBDgLSIrEU6cX4AP2T6XeHcw?e=ewrPU8)
3. [Strutture essenziali di programmazione](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/ESXwEDjHh6lOvezPGYwtPqcBLHyV_Xxbl35NwmPKtFKQIw?e=G0hEkD) 
4. [Introduzione alla grafica con R](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/ET1bLnyxfAVGh0qEWam6HRcBeKHSQw3hixRKW4MH_PfR5A?e=G68BrB)
5. [Esercizi](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/ETfKB7Hj_dFIoDdiRTs9-dYBCQiG9cLXSa2Kev0inp_lEw?e=2vfqP4)
6. Reference: [R for data science (2e)](https://r4ds.hadley.nz)

---

# Models and model building

1. [Slides](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EfANHKWb3RRGqCGIv9SMc6UB7XIjPV5lX2myXpM83IZeUQ?e=yER9pa)
2. [Esercizi](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EbcvSh7wcwlDlu01GHBJK6cBXB00kGDJ3PZZJxiLgRIGNg?e=QRCgZs)
3. Reference: Venables, W.N., Ripley, B.D., 2002. Modern applied statistics with S, 4th ed. ed, Statistics and computing. Springer, New York.


---

# Principal component analysis

1. [Slides](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EYmMcY-JZsZHl3e-hZW5gtEBD9f8GbSgiKW4a9_g5CDUqg?e=5D4NIe)
2. [Esercizi](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EfZ4kHJIDf9PtHXI7xZVHV4BZ9EmdhURcEeO7_qu7TgwDg?e=USzELS)
3. Reference: Legendre, P., Legendre, L., 2012. Numerical ecology. Elsevier, Amsterdam (The Netherlands).
4. Reference: Borcard, D., Gillet, F., Legendre, P., 2011. Numerical Ecology with R. Springer Science+Business Media, LLC 2011, New York.



---

# Cluster analysis

1. [Slides](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EcBIigLT5W5BgiBQnegwuAEBgYwMQE4yCphf7U27AZgQbA?e=T0vW1Y)
2. [Esercizi](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/Ed_YOKkGYQVBng-v96qq_ewBISs63dsnyK53zRistVUdig?e=wBwuXK)
3. Reference: Legendre, P., Legendre, L., 2012. Numerical ecology. Elsevier, Amsterdam (The Netherlands).
4. Reference: Borcard, D., Gillet, F., Legendre, P., 2011. Numerical Ecology with R. Springer Science+Business Media, LLC 2011, New York.

---

# Mixed models

1. [Slides](https://unipg-my.sharepoint.com/:b:/g/personal/andrea_onofri_unipg_it/EYNuunhZmkdLuwmYYyswcS8BmfbbqBreJhNGRoUz_dRS6A?e=hb6sDU)
2. Reference: Pinheiro, J.C., Bates, D.M., 2000. Mixed-Effects Models in S and S-Plus, Springer-Verlag Inc. ed. Springer-Verlag Inc., New York.
3. Reference: Gałecki, A., Burzykowski, T., 2013. Linear mixed-effects models using R: a step-by-step approach. Springer, Berlin.
