{
  "hash": "eaba7bdcbe91efa496797a23736dfe37",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Variance Puzzle: Why Doesn't R Divide by 'n'?\"\nauthor: \"Andrea Onofri\"\ndate: 2018-11-09\ntags: \n   - \"Population Variance\"\n   - \"Sample Variance\"\ncategories: \"descriptive statistics\"\naliases: \n  - /2018/stat_general_variancesamplepop/index.html\nimage: \"/Figures/VarianceSamplePop.jpg\"  \n---\n\nTeaching Experimental Methodology in master's courses related to agriculture poses some peculiar challenges. One of them is explaining the difference between **population variance** and **sample variance**.\n\nStudents usually have little difficulty understanding that, since the mean represents the \"centre\" of a dataset, it is natural to measure the average squared distance of all observations from the mean. Of course, we square the distances because, otherwise, positive and negative deviations would cancel each other out.\n\nIt therefore seems perfectly reasonable that the average squared distance (the **variance**) should be calculated as\n\n$${\\sigma ^2} = \\frac{\\sum\\limits_{i = 1}^n ({X_i} - \\mu )^2}{n}$$\n\nHowever, this is **not** what R (or most other statistical software) does. Instead, R divides by $n-1$, and at this point students inevitably ask:\n\n::: callout-important\n\"Why are you telling me to divide the sum of squares by $n-1$ instead of $n$? I have $n$ squared residuals, not $n-1$!\"\n:::\n\nYou might think that the answer is obvious. I do not.\n\nAt this stage of the course, variance is introduced within the context of descriptive statistics. The students know nothing yet about probability distributions, sampling, statistical inference, or degrees of freedom. If I were teaching mathematics or statistics, I could impress the class with a formal proof showing that $n-1$ is the correct denominator whenever a sample is used to estimate the population variance. That proof can be found in virtually every statistics textbook, and I have reproduced it at the end of this post.\n\nHowever, I would never present that proof at this point. It assumes concepts that the students have not yet encountered, such as sampling distributions and standard errors. Moreover, agricultural students are generally not enthusiastic when mathematics becomes too abstract!\n\nInstead of trying to appear clever, I usually ask myself a different question:\n\n::: callout-important\nCan we explain the difference between population variance and sample variance without mentioning degrees of freedom or any other difficult concepts?\n:::\n\nHere is the approach I usually take.\n\nLet's consider a large but finite population—for example, one hectare of maize, containing roughly 70,000 plants. Imagine that we know the yield of every single plant. In R we can simulate such a population by generating random values between 150 and 250 g. (Agricultural students immediately recognise these as realistic values, and at this stage I deliberately avoid discussing probability distributions.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\npop <- runif(70000, min = 150, max = 250)\n```\n:::\n\n\nWe now have our finite population. Since we know every individual, we can calculate both the population mean and the population variance—that is, the average squared distance of all 70,000 observations from their mean. Notice that I use the equation above, with $n$ in the denominator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(pop) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 200.0893\n```\n\n\n:::\n\n```{.r .cell-code}\nsigma2 <- sum( ( pop - mean(pop) )^2 )/70000\nsigma2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 835.184\n```\n\n\n:::\n:::\n\n\nNow let's forget about the population. In practice, we would never measure the yield of every plant in a hectare because of limitations in time and resources. Instead, suppose we randomly select just ten plants (agricultural experiments often involve surprisingly small sample sizes!).\n\nWe can obtain such a sample in R by drawing observations from the original population.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- sample(pop, 10)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 174.0269 239.5843 209.6669 222.3267 160.7107 229.6837 238.1470 202.0382\n [9] 249.2965 170.6348\n```\n\n\n:::\n:::\n\n\nUsing the same formula as before (that is, dividing by $n=10$), we calculate the sample mean and sample variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(x) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 209.6116\n```\n\n\n:::\n\n```{.r .cell-code}\nsigma2_s <- sum( ( x - mean(x) )^2 )/10 \nsigma2_s\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 908.6202\n```\n\n\n:::\n:::\n\n\nWe do not know the population, only the sample. In the absence of any other information, the most reasonable assumption is that the population resembles the sample. The procedure used to obtain this guess is called an **estimator**, while the resulting value is an **estimate**.\n\nBut is it a good estimator?\n\nWe cannot tell from a single sample. Instead, we need to repeat the sampling process many times and examine how the estimates behave in the long run. An estimator is considered good if, on average, it converges to the true population value.\n\nLet's repeat the sampling procedure 10,000 times, each time selecting ten plants and calculating both the sample mean and the sample variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanS <- c();\nvarS <- c() \nfor(i in 1:10000){   \n  x <- sample(pop, 10)   \n  meanS[i] <- mean(x)   \n  varS[i] <- sum( ( x - mean(x) )^2 )/10 \n  }\nmean(meanS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 199.9096\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(varS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 752.4658\n```\n\n\n:::\n:::\n\n\nThe average of the 10,000 sample means is 199.91, which is extremely close to the true population mean. Therefore, the sample mean is an **unbiased estimator** of the population mean.\n\nThe average of the 10,000 sample variances, however, is 752.47, which is noticeably smaller than the true population variance. In other words, if we divide by $n$, we systematically underestimate the population variance.\n\nLet's examine the ratio between the true population variance and the average estimated variance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(pop)/mean(varS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.109945\n```\n\n\n:::\n:::\n\n\nThe result is approximately $10/9$.\n\nTherefore, if we\n\n1.  calculate the sample variance by dividing by $n$,\n2.  multiply by $n$, and\n3.  divide by $n-1$,\n\nwe obtain an estimator that is correct on average.\n\nThis leads to the familiar formula\n\n$${\\sigma ^2} = \\frac{\\sum\\limits_{i = 1}^n ({X_i} - m )^2}{n - 1}$$\n\nwhich is exactly the sample variance calculated by R.\n\n# Which formula should we use?\n\nThe answer is easy to remember.\n\n1.  If we know the entire population, the variance is the average squared deviation from the population mean, so we divide by $n$.\n2.  If we only have a random sample and our goal is to estimate the population variance, we divide by $n-1$. Otherwise, our estimate will be systematically too small.\n\nThanks for reading! And ... don't forget to check out my new book!\n\nProf. Andrea Onofri\\\nDepartment of Agricultural, Food and Environmental Sciences\\\nUniversity of Perugia (Italy)\\\nSend comments to: [andrea.onofri\\@unipg.it](mailto:andrea.onofri@unipg.it)\n\n<a href = \"https://www.awin1.com/cread.php?awinmid=26429&awinaffid=2675822&ued=https%3A%2F%2Flink.springer.com%2Fbook%2F10.1007%2F978-3-032-08199-5\"><img src=\"/Figures/Email_Signature_978-3-032-08199-5.png\" alt=\"Book cover\" class=\"cover\" align=\"center\"/></a>\n\n------------------------------------------------------------------------\n\n# The formal proof (look how clever I am!)\n\nWe have a population with mean equal to $\\mu$ and variance equal to $\\sigma^2$. Let's take a sample with its mean $m \\neq \\mu$ and $m - \\mu = \\varepsilon$. For the population, we can write:\n\n$$\\sum\\limits_{i = 1}^n (X_i - \\mu )^2  = \\sum\\limits_{i = 1}^n (X_ i - m + \\varepsilon)^2 = \\sum\\limits_{i = 1}^n ({X_i} - m)^2 + n \\varepsilon^2$$\n\nWe already see that the sum of squared residuals is higher if we take $m$ instead of $\\mu$, unless $\\varepsilon = 0$, i.e. $m = \\mu$. From the above, we derive\n\n$$\\sum\\limits_{i = 1}^n (X_i - \\mu)^2 =  \\sum\\limits_{i = 1}^n (X_i - \\mu )^2  - n ( {m - \\mu } )^2$$\n\nIf we consider the first equation above (variance for the population) we have\n\n$$\\sum\\limits_{i = 1}^n (X_i - \\mu)^2 =  n \\sigma^2 - n( m - \\mu  )^2$$\n\nWe see that the rightmost term of this equation ($n ( m - \\mu  )^2$ is the sum of squared distances for the sampling distribution of the mean. That is $n$ times the squared standard error. Therefore:\n\n$$\\sum\\limits_{i = 1}^n {{{({X_i} - \\bar X)}^2} = } n{\\sigma ^2} - n\\left( {\\frac{{{\\sigma ^2}}}{n}} \\right)$$\n\nand\n\n$$\\sum\\limits_{i = 1}^n {{{({X_i} - \\bar X)}^2} = } (n - 1){\\sigma ^2}$$\n\nHere we go! Indeed:\n\n$$ \\frac{\\sum\\limits_{i = 1}^n (X_i - m)^2 }{n - 1} = {\\sigma ^2}$$\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}