<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Metodologia di sperimentazione in agricoltura</title>
  <meta name="description" content="Appunti dalle lezioni (A.A. 2017-2018)">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Metodologia di sperimentazione in agricoltura" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Appunti dalle lezioni (A.A. 2017-2018)" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Metodologia di sperimentazione in agricoltura" />
  
  <meta name="twitter:description" content="Appunti dalle lezioni (A.A. 2017-2018)" />
  

<meta name="author" content="Andrea Onofri">


<meta name="date" content="2019-01-21">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html">
<link rel="next" href="modelli-matamatici-descrittivi-breve-introduzione.html">
<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduzione</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#organizzazione-del-corso"><i class="fa fa-check"></i><b>1.1</b> Organizzazione del corso</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#esercitazioni-pratiche"><i class="fa fa-check"></i><b>1.2</b> Esercitazioni pratiche</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#obiettivi-specifici-del-corso"><i class="fa fa-check"></i><b>1.3</b> Obiettivi specifici del Corso</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><i class="fa fa-check"></i><b>2</b> Il metodo sperimentale: quando la scienza è scienza</a><ul>
<li class="chapter" data-level="2.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#introduzione-1"><i class="fa fa-check"></i><b>2.1</b> Introduzione</a><ul>
<li class="chapter" data-level="2.1.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#cosa-e-quindi-una-prova-scientifica"><i class="fa fa-check"></i><b>2.1.1</b> Cosa è quindi una prova scientifica?</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#esperimenti-buoni-e-cattivi"><i class="fa fa-check"></i><b>2.2</b> Esperimenti buoni e cattivi!</a><ul>
<li class="chapter" data-level="2.2.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#lerrore-sperimentale"><i class="fa fa-check"></i><b>2.2.1</b> L’errore sperimentale</a></li>
<li class="chapter" data-level="2.2.2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#il-campionamento"><i class="fa fa-check"></i><b>2.2.2</b> Il campionamento</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#scienza-metodo"><i class="fa fa-check"></i><b>2.3</b> Scienza = metodo</a></li>
<li class="chapter" data-level="2.4" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#chi-valuta-se-un-esperimento-e-attendibile"><i class="fa fa-check"></i><b>2.4</b> Chi valuta se un esperimento è attendibile?</a></li>
<li class="chapter" data-level="2.5" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#il-metodo-sperimentale"><i class="fa fa-check"></i><b>2.5</b> Il metodo sperimentale</a></li>
<li class="chapter" data-level="2.6" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#metodi-sperimentali-validi-ed-invalidi"><i class="fa fa-check"></i><b>2.6</b> Metodi sperimentali validi ed invalidi</a><ul>
<li class="chapter" data-level="2.6.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#primo-esperimento"><i class="fa fa-check"></i><b>2.6.1</b> Primo esperimento</a></li>
<li class="chapter" data-level="2.6.2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#secondo-esperimento"><i class="fa fa-check"></i><b>2.6.2</b> Secondo esperimento</a></li>
<li class="chapter" data-level="2.6.3" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#terzo-esperimento"><i class="fa fa-check"></i><b>2.6.3</b> Terzo esperimento</a></li>
<li class="chapter" data-level="2.6.4" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#quarto-esperimento-quello-buono"><i class="fa fa-check"></i><b>2.6.4</b> Quarto esperimento: quello buono</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#incertezza-residua"><i class="fa fa-check"></i><b>2.7</b> Incertezza residua</a></li>
<li class="chapter" data-level="2.8" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#il-ruolo-della-statistica"><i class="fa fa-check"></i><b>2.8</b> Il ruolo della statistica</a></li>
<li class="chapter" data-level="2.9" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#conclusioni"><i class="fa fa-check"></i><b>2.9</b> Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html"><i class="fa fa-check"></i><b>3</b> Introduzione al disegno sperimentale</a><ul>
<li class="chapter" data-level="3.1" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#definizioni"><i class="fa fa-check"></i><b>3.1</b> Definizioni</a></li>
<li class="chapter" data-level="3.2" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#elementi-fondamentali-del-disegno-sperimentale"><i class="fa fa-check"></i><b>3.2</b> Elementi fondamentali del disegno sperimentale</a><ul>
<li class="chapter" data-level="3.2.1" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#controllo-degli-errori"><i class="fa fa-check"></i><b>3.2.1</b> Controllo degli errori</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#replicazione"><i class="fa fa-check"></i><b>3.2.2</b> Replicazione</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#randomizzazione"><i class="fa fa-check"></i><b>3.2.3</b> Randomizzazione</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#esperimenti-non-validi"><i class="fa fa-check"></i><b>3.2.4</b> Esperimenti non validi</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#progettazione-di-un-esperimento-protocollo"><i class="fa fa-check"></i><b>3.3</b> Progettazione di un esperimento (protocollo)</a><ul>
<li class="chapter" data-level="3.3.1" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#ipotesi-scientifica-rightarrow-obiettivo-dellesperimento"><i class="fa fa-check"></i><b>3.3.1</b> Ipotesi scientifica <span class="math inline">\(\rightarrow\)</span> obiettivo dell’esperimento</a></li>
<li class="chapter" data-level="3.3.2" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---1"><i class="fa fa-check"></i><b>3.3.2</b> Casi di studio - 1</a></li>
<li class="chapter" data-level="3.3.3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#identificazione-dei-fattori-sperimentali"><i class="fa fa-check"></i><b>3.3.3</b> Identificazione dei fattori sperimentali</a></li>
<li class="chapter" data-level="3.3.4" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#esperimenti-multifattoriali"><i class="fa fa-check"></i><b>3.3.4</b> Esperimenti (multi)fattoriali</a></li>
<li class="chapter" data-level="3.3.5" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#aggiungere-un-controllo"><i class="fa fa-check"></i><b>3.3.5</b> Aggiungere un controllo?</a></li>
<li class="chapter" data-level="3.3.6" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#fattori-sperimentali-di-trattamento-e-di-blocco"><i class="fa fa-check"></i><b>3.3.6</b> Fattori sperimentali di trattamento e di blocco</a></li>
<li class="chapter" data-level="3.3.7" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---2"><i class="fa fa-check"></i><b>3.3.7</b> Casi di studio - 2</a></li>
<li class="chapter" data-level="3.3.8" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#identificazione-delle-unita-sperimentali-e-delle-repliche"><i class="fa fa-check"></i><b>3.3.8</b> Identificazione delle unità sperimentali e delle repliche</a></li>
<li class="chapter" data-level="3.3.9" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#scelta-delle-variabili-da-rilevare"><i class="fa fa-check"></i><b>3.3.9</b> Scelta delle variabili da rilevare</a></li>
<li class="chapter" data-level="3.3.10" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---3"><i class="fa fa-check"></i><b>3.3.10</b> Casi di studio - 3</a></li>
<li class="chapter" data-level="3.3.11" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#allocazione-dei-trattamenti"><i class="fa fa-check"></i><b>3.3.11</b> Allocazione dei trattamenti</a></li>
<li class="chapter" data-level="3.3.12" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---4"><i class="fa fa-check"></i><b>3.3.12</b> Casi di studio - 4</a></li>
<li class="chapter" data-level="3.3.13" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#impianto-delle-prove"><i class="fa fa-check"></i><b>3.3.13</b> Impianto delle prove</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#come-scrivere-un-progetto-di-ricerca-o-un-report-di-ricerca"><i class="fa fa-check"></i><b>3.4</b> Come scrivere un progetto di ricerca o un report di ricerca</a></li>
<li class="chapter" data-level="3.5" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#per-approfondimenti"><i class="fa fa-check"></i><b>3.5</b> Per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html"><i class="fa fa-check"></i><b>4</b> Per iniziare: introduzione ad R</a><ul>
<li class="chapter" data-level="4.1" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#cosa-e-r"><i class="fa fa-check"></i><b>4.1</b> Cosa è R?</a></li>
<li class="chapter" data-level="4.2" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#oggetti-e-assegnazioni"><i class="fa fa-check"></i><b>4.2</b> Oggetti e assegnazioni</a></li>
<li class="chapter" data-level="4.3" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#costanti-e-vettori"><i class="fa fa-check"></i><b>4.3</b> Costanti e vettori</a></li>
<li class="chapter" data-level="4.4" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#matrici"><i class="fa fa-check"></i><b>4.4</b> Matrici</a></li>
<li class="chapter" data-level="4.5" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#operazioni-ed-operatori"><i class="fa fa-check"></i><b>4.5</b> Operazioni ed operatori</a></li>
<li class="chapter" data-level="4.6" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#funzioni-ed-argomenti"><i class="fa fa-check"></i><b>4.6</b> Funzioni ed argomenti</a></li>
<li class="chapter" data-level="4.7" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#dataframe"><i class="fa fa-check"></i><b>4.7</b> Dataframe</a></li>
<li class="chapter" data-level="4.8" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#quale-oggetto-sto-utilizzando"><i class="fa fa-check"></i><b>4.8</b> Quale oggetto sto utilizzando?</a></li>
<li class="chapter" data-level="4.9" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#consigli-per-limmissione-di-dati-sperimentali"><i class="fa fa-check"></i><b>4.9</b> Consigli per l’immissione di dati sperimentali</a><ul>
<li class="chapter" data-level="4.9.1" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#immissione-manuale-di-dati"><i class="fa fa-check"></i><b>4.9.1</b> Immissione manuale di dati</a></li>
<li class="chapter" data-level="4.9.2" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#immissione-di-numeri-progressivi"><i class="fa fa-check"></i><b>4.9.2</b> Immissione di numeri progressivi</a></li>
<li class="chapter" data-level="4.9.3" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#immissione-dei-codici-delle-tesi-e-dei-blocchi"><i class="fa fa-check"></i><b>4.9.3</b> Immissione dei codici delle tesi e dei blocchi</a></li>
<li class="chapter" data-level="4.9.4" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#leggere-e-salvare-dati-esterni"><i class="fa fa-check"></i><b>4.9.4</b> Leggere e salvare dati esterni</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#alcune-operazioni-comuni-sul-dataset"><i class="fa fa-check"></i><b>4.10</b> Alcune operazioni comuni sul dataset</a><ul>
<li class="chapter" data-level="4.10.1" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#selezionare-un-subset-di-dati"><i class="fa fa-check"></i><b>4.10.1</b> Selezionare un subset di dati</a></li>
<li class="chapter" data-level="4.10.2" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#ordinare-un-vettore-o-un-dataframe"><i class="fa fa-check"></i><b>4.10.2</b> Ordinare un vettore o un dataframe</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#workspace"><i class="fa fa-check"></i><b>4.11</b> Workspace</a></li>
<li class="chapter" data-level="4.12" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#script-o-programmi"><i class="fa fa-check"></i><b>4.12</b> Script o programmi</a></li>
<li class="chapter" data-level="4.13" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#interrogazione-di-oggetti"><i class="fa fa-check"></i><b>4.13</b> Interrogazione di oggetti</a></li>
<li class="chapter" data-level="4.14" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#altre-funzioni-matriciali"><i class="fa fa-check"></i><b>4.14</b> Altre funzioni matriciali</a></li>
<li class="chapter" data-level="4.15" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#cenni-sulle-funzionalita-grafiche-in-r"><i class="fa fa-check"></i><b>4.15</b> Cenni sulle funzionalità grafiche in R</a></li>
<li class="chapter" data-level="4.16" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#per-approfondimenti-1"><i class="fa fa-check"></i><b>4.16</b> Per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html"><i class="fa fa-check"></i><b>5</b> Primo passo: la descrizione dei dati raccolti</a><ul>
<li class="chapter" data-level="5.1" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#le-variabili-quantitative-analisi-chimiche-e-altre-misurazioni-fondamentali"><i class="fa fa-check"></i><b>5.1</b> Le variabili quantitative: analisi chimiche e altre misurazioni fondamentali</a><ul>
<li class="chapter" data-level="5.1.1" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#indicatori-di-tendenza-centrale"><i class="fa fa-check"></i><b>5.1.1</b> Indicatori di tendenza centrale</a></li>
<li class="chapter" data-level="5.1.2" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#indicatori-di-variabilita"><i class="fa fa-check"></i><b>5.1.2</b> Indicatori di variabilità</a></li>
<li class="chapter" data-level="5.1.3" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#arrotondamenti"><i class="fa fa-check"></i><b>5.1.3</b> Arrotondamenti</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#descrizione-dei-sottogruppi"><i class="fa fa-check"></i><b>5.2</b> Descrizione dei sottogruppi</a></li>
<li class="chapter" data-level="5.3" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#distribuzioni-di-frequenza-e-classamento"><i class="fa fa-check"></i><b>5.3</b> Distribuzioni di frequenza e classamento</a></li>
<li class="chapter" data-level="5.4" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#statistiche-descrittive-per-le-distribuzioni-di-frequenza"><i class="fa fa-check"></i><b>5.4</b> Statistiche descrittive per le distribuzioni di frequenza</a></li>
<li class="chapter" data-level="5.5" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#distribuzioni-di-frequenza-bivariate-le-tabelle-di-contingenza"><i class="fa fa-check"></i><b>5.5</b> Distribuzioni di frequenza bivariate: le tabelle di contingenza</a></li>
<li class="chapter" data-level="5.6" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#connessione"><i class="fa fa-check"></i><b>5.6</b> Connessione</a></li>
<li class="chapter" data-level="5.7" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#correlazione"><i class="fa fa-check"></i><b>5.7</b> Correlazione</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html"><i class="fa fa-check"></i><b>6</b> Dalla popolazione al campione. I modelli stocastici</a><ul>
<li class="chapter" data-level="6.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#introduzione-2"><i class="fa fa-check"></i><b>6.1</b> Introduzione</a></li>
<li class="chapter" data-level="6.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#popolazione-di-soggetti-e-popolazione-di-misure"><i class="fa fa-check"></i><b>6.2</b> Popolazione di soggetti e popolazione di misure</a></li>
<li class="chapter" data-level="6.3" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-scienza-del-caso"><i class="fa fa-check"></i><b>6.3</b> La scienza del caso</a></li>
<li class="chapter" data-level="6.4" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#modelli-probabilistici-stocastici"><i class="fa fa-check"></i><b>6.4</b> Modelli probabilistici (stocastici)</a><ul>
<li class="chapter" data-level="6.4.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#funzioni-di-probabilita"><i class="fa fa-check"></i><b>6.4.1</b> Funzioni di probabilità</a></li>
<li class="chapter" data-level="6.4.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#funzioni-di-densita"><i class="fa fa-check"></i><b>6.4.2</b> Funzioni di densità</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-distribuzione-normale-curva-di-gauss"><i class="fa fa-check"></i><b>6.5</b> La distribuzione normale (curva di Gauss)</a><ul>
<li class="chapter" data-level="6.5.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-1"><i class="fa fa-check"></i><b>6.5.1</b> ESERCIZIO 1</a></li>
<li class="chapter" data-level="6.5.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-2"><i class="fa fa-check"></i><b>6.5.2</b> ESERCIZIO 2</a></li>
<li class="chapter" data-level="6.5.3" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-3"><i class="fa fa-check"></i><b>6.5.3</b> ESERCIZIO 3</a></li>
<li class="chapter" data-level="6.5.4" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-4"><i class="fa fa-check"></i><b>6.5.4</b> ESERCIZIO 4</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-distribuzione-t-di-student"><i class="fa fa-check"></i><b>6.6</b> La distribuzione t di Student</a><ul>
<li class="chapter" data-level="6.6.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-5"><i class="fa fa-check"></i><b>6.6.1</b> ESERCIZIO 5</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-distribuzione-f-di-fisher"><i class="fa fa-check"></i><b>6.7</b> La distribuzione F di Fisher</a><ul>
<li class="chapter" data-level="6.7.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-6"><i class="fa fa-check"></i><b>6.7.1</b> ESERCIZIO 6</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#modelli-stocastici-per-eventi-discreti-la-distribuzione-binomiale"><i class="fa fa-check"></i><b>6.8</b> Modelli stocastici per eventi discreti: la distribuzione binomiale</a><ul>
<li class="chapter" data-level="6.8.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-7"><i class="fa fa-check"></i><b>6.8.1</b> ESERCIZIO 7</a></li>
<li class="chapter" data-level="6.8.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-8"><i class="fa fa-check"></i><b>6.8.2</b> ESERCIZIO 8</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#ltri-modelli-stocastici-di-interesse-per-lo-sperimentatore"><i class="fa fa-check"></i><b>6.9</b> ltri modelli stocastici di interesse per lo sperimentatore</a></li>
<li class="chapter" data-level="6.10" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#e-allora"><i class="fa fa-check"></i><b>6.10</b> E allora?</a></li>
<li class="chapter" data-level="6.11" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#le-simulazioni-monte-carlo"><i class="fa fa-check"></i><b>6.11</b> Le simulazioni Monte Carlo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><i class="fa fa-check"></i><b>7</b> Modellizzare l’errore sperimentale: introduzione all’inferenza statistica</a><ul>
<li class="chapter" data-level="7.1" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#introduzione-3"><i class="fa fa-check"></i><b>7.1</b> Introduzione</a></li>
<li class="chapter" data-level="7.2" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#lanalisi-dei-dati-gli-ingredienti-fondamentali"><i class="fa fa-check"></i><b>7.2</b> L’analisi dei dati: gli ’ingredienti’ fondamentali</a></li>
<li class="chapter" data-level="7.3" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#modello-della-realta-e-sampling-space"><i class="fa fa-check"></i><b>7.3</b> Modello della realtà e ’sampling space’</a></li>
<li class="chapter" data-level="7.4" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#esempio-1-2"><i class="fa fa-check"></i><b>7.4</b> Esempio 1</a><ul>
<li class="chapter" data-level="7.4.1" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#sampling-distribution"><i class="fa fa-check"></i><b>7.4.1</b> Sampling distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#esempio-2-2"><i class="fa fa-check"></i><b>7.5</b> Esempio 2</a><ul>
<li class="chapter" data-level="7.5.1" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#definire-la-sampling-distribution-per-lesempio-2"><i class="fa fa-check"></i><b>7.5.1</b> Definire la ’sampling distribution’ per l’esempio 2</a></li>
<li class="chapter" data-level="7.5.2" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#le-simulazioni-monte-carlo-con-excel"><i class="fa fa-check"></i><b>7.5.2</b> Le simulazioni Monte Carlo con Excel</a></li>
<li class="chapter" data-level="7.5.3" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#la-distribuzione-delle-medie-campionarie-lerrore-standard"><i class="fa fa-check"></i><b>7.5.3</b> La distribuzione delle medie campionarie: l’errore standard</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#riepilogo-1-caratterizzare-lincertezza-di-un-esperimento"><i class="fa fa-check"></i><b>7.6</b> Riepilogo 1: Caratterizzare l’incertezza di un esperimento</a></li>
<li class="chapter" data-level="7.7" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#gli-intervalli-di-confidenza"><i class="fa fa-check"></i><b>7.7</b> Gli intervalli di confidenza</a></li>
<li class="chapter" data-level="7.8" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#gli-intervalli-di-confidenza-con-excel"><i class="fa fa-check"></i><b>7.8</b> Gli intervalli di confidenza con Excel</a></li>
<li class="chapter" data-level="7.9" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#qual-e-il-senso-dellintervallo-di-confidenza"><i class="fa fa-check"></i><b>7.9</b> Qual è il senso dell’intervallo di confidenza?</a></li>
<li class="chapter" data-level="7.10" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#analisi-statistica-dei-dati-riassunto-del-percorso-logico"><i class="fa fa-check"></i><b>7.10</b> Analisi statistica dei dati: riassunto del percorso logico</a></li>
<li class="chapter" data-level="7.11" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#presentazione-dei-risultati-degli-esperimenti"><i class="fa fa-check"></i><b>7.11</b> Presentazione dei risultati degli esperimenti</a></li>
<li class="chapter" data-level="7.12" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#da-ricordare"><i class="fa fa-check"></i><b>7.12</b> Da ricordare</a></li>
<li class="chapter" data-level="7.13" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#esercizi"><i class="fa fa-check"></i><b>7.13</b> Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html"><i class="fa fa-check"></i><b>8</b> Breve introduzione al test d’ipotesi</a><ul>
<li class="chapter" data-level="8.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#confronto-tra-una-media-osservata-e-una-media-teorica"><i class="fa fa-check"></i><b>8.1</b> Confronto tra una media osservata e una media teorica</a><ul>
<li class="chapter" data-level="8.1.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#esempio-1-3"><i class="fa fa-check"></i><b>8.1.1</b> ESEMPIO 1</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#simulazione-monte-carlo"><i class="fa fa-check"></i><b>8.2</b> Simulazione Monte Carlo</a></li>
<li class="chapter" data-level="8.3" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#soluzione-formale"><i class="fa fa-check"></i><b>8.3</b> Soluzione formale</a></li>
<li class="chapter" data-level="8.4" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#interpretazione-del-p-level"><i class="fa fa-check"></i><b>8.4</b> Interpretazione del P-level</a></li>
<li class="chapter" data-level="8.5" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#confronto-tra-due-medie-il-test-t-di-student"><i class="fa fa-check"></i><b>8.5</b> Confronto tra due medie: il test t di Student</a><ul>
<li class="chapter" data-level="8.5.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#esempio-2-3"><i class="fa fa-check"></i><b>8.5.1</b> ESEMPIO 2</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#approfondimento-tipologie-alternative-di-test-t"><i class="fa fa-check"></i><b>8.6</b> Approfondimento: tipologie alternative di test t</a></li>
<li class="chapter" data-level="8.7" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#confronto-tra-due-proporzioni"><i class="fa fa-check"></i><b>8.7</b> Confronto tra due proporzioni</a><ul>
<li class="chapter" data-level="8.7.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#esempio-3-2"><i class="fa fa-check"></i><b>8.7.1</b> ESEMPIO 3</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#conclusioni-1"><i class="fa fa-check"></i><b>8.8</b> Conclusioni</a></li>
<li class="chapter" data-level="8.9" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#riepilogo"><i class="fa fa-check"></i><b>8.9</b> Riepilogo</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html"><i class="fa fa-check"></i><b>9</b> Modelli matamatici descrittivi: breve introduzione</a><ul>
<li class="chapter" data-level="9.1" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html#che-centra-la-matematica"><i class="fa fa-check"></i><b>9.1</b> Che c’entra la matematica?</a></li>
<li class="chapter" data-level="9.2" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html#mettiamo-alcuni-paletti"><i class="fa fa-check"></i><b>9.2</b> Mettiamo alcuni paletti</a></li>
<li class="chapter" data-level="9.3" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html#metodo-di-lavoro"><i class="fa fa-check"></i><b>9.3</b> Metodo di lavoro</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html"><i class="fa fa-check"></i><b>10</b> Una variabile indipendente categorica: ANOVA ad una via</a><ul>
<li class="chapter" data-level="10.1" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#la-situazione-sperimentale"><i class="fa fa-check"></i><b>10.1</b> La situazione sperimentale</a></li>
<li class="chapter" data-level="10.2" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#la-verita-vera-la-popolazione"><i class="fa fa-check"></i><b>10.2</b> La verità ‘vera’ (la popolazione)</a></li>
<li class="chapter" data-level="10.3" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#esecuzione-dellesperimento"><i class="fa fa-check"></i><b>10.3</b> Esecuzione dell’esperimento</a></li>
<li class="chapter" data-level="10.4" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#analisi-dei-dati-1"><i class="fa fa-check"></i><b>10.4</b> Analisi dei dati</a><ul>
<li class="chapter" data-level="10.4.1" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#statistiche-descrittive"><i class="fa fa-check"></i><b>10.4.1</b> Statistiche descrittive</a></li>
<li class="chapter" data-level="10.4.2" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#stima-dei-parametri-1"><i class="fa fa-check"></i><b>10.4.2</b> Stima dei parametri</a></li>
<li class="chapter" data-level="10.4.3" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#stima-della-varianza"><i class="fa fa-check"></i><b>10.4.3</b> Stima della varianza</a></li>
<li class="chapter" data-level="10.4.4" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#effetto-del-trattamento"><i class="fa fa-check"></i><b>10.4.4</b> Effetto del trattamento</a></li>
<li class="chapter" data-level="10.4.5" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#test-dipotesi"><i class="fa fa-check"></i><b>10.4.5</b> Test d’ipotesi</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#per-approfondimenti-2"><i class="fa fa-check"></i><b>10.5</b> Per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><i class="fa fa-check"></i><b>11</b> La verifica delle assunzioni di base: metodi diagnostici</a><ul>
<li class="chapter" data-level="11.1" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#introduzione-4"><i class="fa fa-check"></i><b>11.1</b> Introduzione</a></li>
<li class="chapter" data-level="11.2" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#procedure-diagnostiche"><i class="fa fa-check"></i><b>11.2</b> Procedure diagnostiche</a></li>
<li class="chapter" data-level="11.3" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#analisi-grafica-dei-residui"><i class="fa fa-check"></i><b>11.3</b> Analisi grafica dei residui</a><ul>
<li class="chapter" data-level="11.3.1" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#grafico-dei-residui-contro-i-valori-attesi"><i class="fa fa-check"></i><b>11.3.1</b> Grafico dei residui contro i valori attesi</a></li>
<li class="chapter" data-level="11.3.2" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#qq-plot"><i class="fa fa-check"></i><b>11.3.2</b> QQ-plot</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#altri-strumenti-diagnostici"><i class="fa fa-check"></i><b>11.4</b> Altri strumenti diagnostici</a></li>
<li class="chapter" data-level="11.5" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#risultati-contraddittori"><i class="fa fa-check"></i><b>11.5</b> Risultati contraddittori</a></li>
<li class="chapter" data-level="11.6" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#terapia"><i class="fa fa-check"></i><b>11.6</b> ‘Terapia’</a><ul>
<li class="chapter" data-level="11.6.1" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#correzionerimozione-degli-outliers"><i class="fa fa-check"></i><b>11.6.1</b> Correzione/Rimozione degli outliers</a></li>
<li class="chapter" data-level="11.6.2" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#correzione-del-modello"><i class="fa fa-check"></i><b>11.6.2</b> Correzione del modello</a></li>
<li class="chapter" data-level="11.6.3" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#non-normalita-dei-residui-ed-eterogeneita-delle-varianze"><i class="fa fa-check"></i><b>11.6.3</b> Non-normalità dei residui ed eterogeneità delle varianze</a></li>
<li class="chapter" data-level="11.6.4" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#la-procedura-di-box-e-cox"><i class="fa fa-check"></i><b>11.6.4</b> La procedura di Box e Cox</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#referenze-bibliografiche-per-approfondimenti"><i class="fa fa-check"></i><b>11.7</b> Referenze bibliografiche per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html"><i class="fa fa-check"></i><b>12</b> Contrasti e confronti multipli con R</a><ul>
<li class="chapter" data-level="12.1" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#introduzione-5"><i class="fa fa-check"></i><b>12.1</b> Introduzione</a></li>
<li class="chapter" data-level="12.2" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#esempio"><i class="fa fa-check"></i><b>12.2</b> Esempio</a></li>
<li class="chapter" data-level="12.3" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#i-contrasti"><i class="fa fa-check"></i><b>12.3</b> I contrasti</a><ul>
<li class="chapter" data-level="12.3.1" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#varianza-del-contrasto-e-intervalli-di-confidenza"><i class="fa fa-check"></i><b>12.3.1</b> Varianza del contrasto e intervalli di confidenza</a></li>
<li class="chapter" data-level="12.3.2" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#significativita-del-contrasto-e-intervalli-di-confidenza"><i class="fa fa-check"></i><b>12.3.2</b> Significatività del contrasto e intervalli di confidenza</a></li>
<li class="chapter" data-level="12.3.3" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#i-contrasti-con-r"><i class="fa fa-check"></i><b>12.3.3</b> I contrasti con R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#i-confronti-multipli-a-coppie-pairwise-comparisons"><i class="fa fa-check"></i><b>12.4</b> I confronti multipli a coppie (pairwise comparisons)</a></li>
<li class="chapter" data-level="12.5" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#display-a-lettere"><i class="fa fa-check"></i><b>12.5</b> Display a lettere</a></li>
<li class="chapter" data-level="12.6" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#problemi-di-molteplicita-tassi-di-errore-per-confronto-e-per-esperimento"><i class="fa fa-check"></i><b>12.6</b> Problemi di molteplicità: tassi di errore per confronto e per esperimento</a><ul>
<li class="chapter" data-level="12.6.1" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#correzione-per-la-molteplicita"><i class="fa fa-check"></i><b>12.6.1</b> Correzione per la molteplicità</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#intervalli-di-confidenza-simultanei"><i class="fa fa-check"></i><b>12.7</b> Intervalli di confidenza simultanei</a></li>
<li class="chapter" data-level="12.8" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#e-le-classiche-procedure-di-confronto-multiplo"><i class="fa fa-check"></i><b>12.8</b> E le classiche procedure di confronto multiplo?</a></li>
<li class="chapter" data-level="12.9" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#consigli-pratici"><i class="fa fa-check"></i><b>12.9</b> Consigli pratici</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="referenze-bibliografiche.html"><a href="referenze-bibliografiche.html"><i class="fa fa-check"></i><b>13</b> Referenze bibliografiche</a></li>
<li class="chapter" data-level="14" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html"><i class="fa fa-check"></i><b>14</b> La regressione lineare semplice</a><ul>
<li class="chapter" data-level="14.1" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#introduzione-6"><i class="fa fa-check"></i><b>14.1</b> Introduzione</a></li>
<li class="chapter" data-level="14.2" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#esempio-6"><i class="fa fa-check"></i><b>14.2</b> Esempio</a></li>
<li class="chapter" data-level="14.3" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#stima-dei-parametri-2"><i class="fa fa-check"></i><b>14.3</b> Stima dei parametri</a></li>
<li class="chapter" data-level="14.4" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#valutazione-della-bonta-del-modello"><i class="fa fa-check"></i><b>14.4</b> Valutazione della bontà del modello</a><ul>
<li class="chapter" data-level="14.4.1" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#valutazione-grafica"><i class="fa fa-check"></i><b>14.4.1</b> Valutazione grafica</a></li>
<li class="chapter" data-level="14.4.2" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#errori-standard-dei-parametri"><i class="fa fa-check"></i><b>14.4.2</b> Errori standard dei parametri</a></li>
<li class="chapter" data-level="14.4.3" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#test-f-per-la-mancanza-dadattamento"><i class="fa fa-check"></i><b>14.4.3</b> Test F per la mancanza d’adattamento</a></li>
<li class="chapter" data-level="14.4.4" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#test-f-per-la-bonta-di-adattamento-e-coefficiente-di-determinazione"><i class="fa fa-check"></i><b>14.4.4</b> Test F per la bontà di adattamento e coefficiente di determinazione</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#previsioni"><i class="fa fa-check"></i><b>14.5</b> Previsioni</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Metodologia di sperimentazione in agricoltura</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="breve-introduzione-al-test-dipotesi" class="section level1">
<h1><span class="header-section-number">Capitolo 8</span> Breve introduzione al test d’ipotesi</h1>
<p>Abbiamo visto che l’approccio classico all’analisi dei dati è fondamentalmente caratterizzato da due elementi:</p>
<ol style="list-style-type: decimal">
<li>modello di generazione dei dati sperimentali;</li>
<li><em>sampling distribution</em> (o <em>sample space</em> o <em>distribuzione campionaria</em>).</li>
</ol>
<p>La sampling distribution viene utilizzata per l’inferenza statistica (stima per intervallo) e può essere utilizzata analogamente per il test d’ipotesi. A questo proposito, riprendiamo l’esempio utilizzato in precedenza per gli intervalli di confidenza.</p>
<div id="confronto-tra-una-media-osservata-e-una-media-teorica" class="section level2">
<h2><span class="header-section-number">8.1</span> Confronto tra una media osservata e una media teorica</h2>
<div id="esempio-1-3" class="section level3">
<h3><span class="header-section-number">8.1.1</span> ESEMPIO 1</h3>
<p>Abbiamo misurato la concentrazione di una soluzione erbicida tramite un gascromatografo. Facendo l’analisi in triplicato, abbiamo ottenuto i tre valori 109.28, 132.29 e 130.85. La media è 124.14 e la deviazione standard è 12.89. Concludiamo che <span class="math inline">\(mu\)</span> è uguale a 124.14, con un errore standard (<span class="math inline">\(s_m\)</span>) pari a 7.44 e un intervallo di confidenza che va da 92.12 a 156.16. Immaginiamo che esista un livello soglia pari a 200 mg/l, al disopra del quale il prodotto diviene tossico per i mammiferi. Dato che non conosciamo il vero valore di <span class="math inline">\(\mu\)</span> ci chiediamo: <em>è possibile che le nostre tre repliche, nella realtà, provengano da una popolazione che ha media uguale a 200</em>?</p>
<p>In questo caso sappiamo bene che non è possibile, visto che abbiamo generato i dati sperimentali (vedi il capitolo precedente), tramite simulazione Monte Carlo, partendo da una verità vera nota (<span class="math inline">\(\mu\)</span> = 120 e <span class="math inline">\(\sigma\)</span> = 12); tuttavia, nella realtà, la domanda è lecita.</p>
<p>In particolare, possiamo calcolare una statistica, che abbiamo già utilizzato per l’intervallo di confidenza, in grado di misurare la discrepanza tra quanto abbiamo osservato e l’ipotesi nulla:</p>
<p><span class="math display">\[ T = \frac{m - 200}{s_m} \]</span></p>
<p>Il valore da noi osservato è T = (124.14 - 200)/7.44 = -10.196, il che implica un certo grado di discrepanza, altrimenti avremmo dovuto osservare un valore di T più vicino a 0. <strong>Possiamo affermare che ciò sia imputabile solo alla variabilità di campionamento e che quindi il nostro esperimento conferma l’ipotesi di partenza (ipotesi nulla)</strong>?</p>
<p>Definiamo quindi la nostra ipotesi di lavoro come <strong>ipotesi nulla</strong> (<span class="math inline">\(H_0\)</span>):</p>
<p><span class="math display">\[H_0: \mu = 200\]</span></p>
<p>oppure, che è anche meglio:</p>
<p><span class="math display">\[H_0: T = 0\]</span></p>
<p>Oltre all’ipotesi nulla, dobbiamo anche definire l’ipotesi alternativa semplice (a ‘due code’), che potrebbe essere:</p>
<p><span class="math display">\[H_1: T \neq 0\]</span></p>
<p>E’possibile anche definire ipotesi alternative complesse del tipo:</p>
<p><span class="math display">\[H_1: T \leq 0\]</span></p>
<p>oppure</p>
<p><span class="math display">\[H_1: T \geq 0\]</span></p>
<p>Bisogna ricordare che le ipotesi debbono essere stabilite prima di effettuare l’esperimento. In questo caso abbiamo fatto un campionamento e abbiamo trovato un valore (124.14) inferiore a quello atteso (200). Che cosa ci attendevamo prima di fare l’esperimento? Un valore diverso da 200, senza poter lecitamente immaginare se sarebbe stato maggiore o minore? In questo caso l’ipotesi alternativa dovrebbe essere la prima (quella semplice). Immaginavamo invece che avrebbe potuto essere inferiore? Allora potremmo utilizzare la prima ipotesi alternativa complessa. In questo caso propendiamo per la prima ipotesi alternativa complessa, cioè <span class="math inline">\(\mu \leq 200\)</span>.</p>
<p>Siamo in totale coerenza con la logica Galileiana: abbiamo un ipotesi di partenza e un esperimento, col quale eventualmente rigettare questa ipotesi. Fisher, negli anni 20 del 1900, propose di utilizzare come <strong>‘forza dell’evidenza scientifica’ la probabilità di ottenere un risultato uguale o più estremo di quello osservato, calcolata supponendo vera l’ipotesi nulla.</strong> Si tratta quindi di capire, tramite la definizione di un’apposita ‘sampling distribution’ per T, qual è la proporzione di valori pari o inferiori a -10.196. Dato che la ipotesi alternativa</p>
<p>Per rispondere utilizzeremo la doppia strada: quella empirica (simulazione Monte Carlo) e quella formale.</p>
</div>
</div>
<div id="simulazione-monte-carlo" class="section level2">
<h2><span class="header-section-number">8.2</span> Simulazione Monte Carlo</h2>
<p>Ci chiediamo: come sarebbe la <em>sampling distribution</em> di T, se <span class="math inline">\(\mu\)</span> fosse uguale a 200? Possiamo costruirla con una simulazione Monte Carlo, ripetendo molte volte (es. 100’000) l’estrazione di campioni con numerosità pari a 3, da una distribuzione normale con media pari a 200 e deviazione standard pari a 12.89 e calcolando la statistica T. Utilizziamo questo valore di deviazione standard perché è quello osservato nel campione e non abbiamo nessun altra informazione disponibile sulla deviazione standard della popolazione originale. Per eseguire questa operazione utilizziamo il seguente codice R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>)
result &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">100000</span>)
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">1000000</span>){
  sample &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">3</span>, <span class="dv">200</span>, <span class="fl">12.888926</span>)
  result[i] &lt;-<span class="st"> </span>(<span class="kw">mean</span>(sample) <span class="op">-</span><span class="st"> </span><span class="dv">200</span>) <span class="op">/</span><span class="st"> </span>(<span class="kw">sd</span>(sample)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">3</span>))
}</code></pre></div>
<p>In questo modo otteniamo 100’000 valori di T e possiamo calcolare la proporzione di questi che è pari o inferiore al valore da noi osservato (-10.196):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">109.28</span>, <span class="fl">132.29</span>, <span class="fl">130.85</span>)
Tobs &lt;-<span class="st"> </span>(<span class="kw">mean</span>(x) <span class="op">-</span><span class="st"> </span><span class="dv">200</span>)<span class="op">/</span>(<span class="kw">sd</span>(x)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">3</span>))
<span class="kw">length</span>(result[result <span class="op">&lt;</span><span class="st"> </span>Tobs])<span class="op">/</span><span class="dv">1000000</span></code></pre></div>
<pre><code>## [1] 0.004697</code></pre>
<p>Eseguendo questa simulazione, otteniamo una proporzione di valori pari a 0.0048. Il risultato si riassume dicendo che il P-level per l’ipotesi nulla è pari a 0.0048. La regola di condotta della statistica tradizionale è quella di rigettare l’ipotesi nulla quando il P-level è inferiore ad una certa soglia prefissata (normalmente P <span class="math inline">\(\leq\)</span> 0.05). Di conseguenza, concludiamo che vi sono elementi sufficienti per contrastare l’ipotesi che il valore incognito della concentrazione di erbicida sia pari a 200 mg/l.</p>
<p>In altre parole, l’evidenza scientifica è sufficiente buona per il rifiuto dell’ipotesi nulla, anche se esiste una certa probabilità d’errore, pari appunto alla probabilità che l’ipotesi nulla sia vera (P = 0.0048).</p>
</div>
<div id="soluzione-formale" class="section level2">
<h2><span class="header-section-number">8.3</span> Soluzione formale</h2>
<p>Possiamo definire una distribuzione di frequenze per T? Empiricamente possiamo osservare che, analogamente al caso degli intervalli di confidenza, possiamo far riferimento alla distribuzione T di Student.</p>
<div class="figure">
<img src="Figures/TstudNorm.jpg" alt="Distribuzione empirica di T, distribuzione normale standardizzata (blu) e distribuzione t di Student con 2 gradi di libertà" style="width:90.0%" />
<p class="caption">Distribuzione empirica di T, distribuzione normale standardizzata (blu) e distribuzione t di Student con 2 gradi di libertà</p>
</div>
<p>Senza ricorrere alla simulazione Monte Carlo, possiamo quindi risolvere il problema utilizzando la distribuzione t di Student:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pt</span>(<span class="op">-</span><span class="fl">10.194</span>, <span class="dt">df=</span><span class="dv">2</span>, <span class="dt">lower.tail=</span>T)</code></pre></div>
<pre><code>## [1] 0.9952569</code></pre>
<p>dove gli argomenti indicano rispettivamente il valore osservato, i gradi di libertà e la coda della distribuzione di nostro interesse (a noi interessa la coda sinistra, cioè i valori inferiori a quello dato). Il risultato ottenuto è pari a 0.00474, molto simile a quello ottenuto per simulazione.</p>
<p>Allo stesso valore, più semplicemente, si giunge utilizzando la funzione “t.test()”:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(x, <span class="dt">mu=</span><span class="dv">200</span>, <span class="dt">alternative=</span><span class="st">&quot;less&quot;</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = -10.194, df = 2, p-value = 0.004743
## alternative hypothesis: true mean is less than 200
## 95 percent confidence interval:
##      -Inf 145.8694
## sample estimates:
## mean of x 
##    124.14</code></pre>
</div>
<div id="interpretazione-del-p-level" class="section level2">
<h2><span class="header-section-number">8.4</span> Interpretazione del P-level</h2>
<p>Quando il P-level è inferiore a 0.05, rifiutiamo l’ipotesi nulla e concludiamo che vi sono elementi sufficienti (prove scientifiche sufficientemente forti) per rifiutare la nostra ipotesi di partenza.</p>
<p>Bisogna sottolineare come il P-level nella statistica tradizionale sia stato inizialmente proposto da Fisher come criterio di comportamento e non come un vero e proprio criterio inferenziale-probabilistico. Successivamente, Jarzy Neyman ed Egon Pearson, intorno al 1930, proposero di utilizzare il P-level come probabilità di errore di I specie, cioè come probabilità di rifiutare erroneamente l’ipotesi nulla. Tuttavia, trattandosi di una probabilità calcolata a partire da una <em>sampling distribution</em>, cioè da un’ipotetica infinita ripetizione dell’esperimento, essa non ha alcun valore in relazione al singolo esperimento effettivamente eseguito, come i due autori menzionati in precedenza hanno esplicitamente chiarito.</p>
<p>Di conseguenza, nel caso in esempio, affermare che abbiamo una probabilità di errore pari a 0.00474 nel rifiutare l’ipotesi nulla, rappresenterebbe un abuso: le nostre conclusioni potrebbero essere false o vere, ma non abbiamo alcun elemento per scegliere tra le due opzioni. Possiamo solo affermare che, se ripetessimo infinite volte l’esperimento e se l’ipotesi nulla fosse vera, otterremmo un risultato estremo come il nostro o più estremo solo in 4.74 casi (circa) su 1000. In altre parole, nel lungo periodo, basando le nostre conclusioni sul criterio anzidetto (rifiuto l’ipotesi nulla se il P-value è inferiore a 0.05) commettiamo un errore in non più del 5% dei casi. Insomma, il P-value non può essere guardato come la probabilità di ‘falso-positivo’ ad ogni singolo test, ma solo nel lunghissimo periodo.</p>
</div>
<div id="confronto-tra-due-medie-il-test-t-di-student" class="section level2">
<h2><span class="header-section-number">8.5</span> Confronto tra due medie: il test t di Student</h2>
<p>Analizziamo un primo esempio pratico di test d’ipotesi: nella sperimentazione agraria si ha spesso interesse a considerare due popolazioni per scoprire se queste sono diverse per il carattere o i caratteri considerati. Più in particolare, siccome ognuna delle popolazioni sarà descritta dalla sua media, saremo interessati a rispondere al quesito se l’eventuale differenza rilevata tra le due medie è da ritenersi una differenza reale, effettiva e con un preciso significato biologico. In sostanza, in termini statistici, dovremo stabilire se la differenza tra le medie è significativa oppure da attribuire a fattori casuali e quindi non significativa.</p>
<p>Anche se il problema può sembrare banale, esso non lo è; basti ripensare al fatto che ogni media stimata si porta dietro un alone di incertezza, definito appunto dall’intervallo di confidenza.</p>
<div id="esempio-2-3" class="section level3">
<h3><span class="header-section-number">8.5.1</span> ESEMPIO 2</h3>
<p>Un ricercatore ha scelto casualmente dieci piante da una popolazione; ne ha trattate cinque con l’erbicida A e cinque con un placebo (P). Alla fine dell’esperimento ha determinato il peso di ognuna delle dieci piante. E’ evidente che le piante oggetto dell’esperimento sono solo un campione di quelle possibili, così come è evidente che il peso, come ogni altra variabile biologica è soggetto ad una certa variabilità naturale, legata sia a questioni genotipiche che fenotipiche, oltre che ad eventuali errori casuali di misura.</p>
<p>I risultati sono i seguenti:</p>
<p>A (peso in g): 65 - 68 - 69 - 71 - 78; la media è pari a 70.2, mentre la deviazione standard è pari a 4.87. L’errore standard che è pari a 2.18 e quindi l’intervallo di confidenza della media è 70.2 <span class="math inline">\(\pm\)</span> 6.04</p>
<p>P (peso in g): 80 - 81 - 84 - 88 - 94; la media è 85.4, mentre la deviazione standard è pari a 5.72. L’errore standard è pari a 2.56, mentre l’intervallo di confidenza per la media è 85.4 <span class="math inline">\(\pm\)</span> 7.11</p>
<p>Possiamo affermare che A riduce il peso delle piante trattate, coerentemente con le aspettative riguardo ad una molecola erbicida? Nel rispondere a questa domanda bisogna tener presente che i campioni sono totalmente irrilevanti, dato che il nostro interesse è rivolto alle popolazioni che hanno generato i campioni. Vogliamo cioè che le nostre conclusioni abbiano carattere di universalità e non siano specifiche a quanto abbiamo osservato nel nostro esperimento. Intanto possiamo notare che il limite di confidenza superiore per A (70.2 + 6.04 = 76.24) è inferiore al limite di confidenza inferiore per P (75.4 - 7.11 = 68.29). Questo non è un criterio sul quale basare le nostre considerazioni, ma è comunque un segno che le popolazioni da cui provengono i due campioni potrebbero essere diverse.</p>
<p>Per trovare un criterio decisionali più rigoroso, possiamo formulare <strong>l’ipotesi nulla in questi termini</strong>:</p>
<p><span class="math display">\[H_0: \mu_1 = \mu_2 = \mu\]</span></p>
<p>In altre parole, la nostra ipotesi di lavoro è che i due campioni siano in realtà estratti da due distribuzioni normali con la stessa media e la stessa deviazione standard, il che equivale a dire che i due campioni provengono da un unica distribuzione normale con media <span class="math inline">\(\mu\)</span> e deviazione standard <span class="math inline">\(\sigma\)</span>.</p>
<p>L’ipotesi alternativa semplice può essere definita:</p>
<p><span class="math display">\[H_1 :\mu_1  \ne \mu_2\]</span></p>
<p>Se abbiamo elementi sufficienti, possiamo anche adottare ipotesi alternative complesse, del tipo</p>
<p><span class="math display">\[H_1 :\mu _1  &gt; \mu _2\]</span></p>
<p>oppure:</p>
<p><span class="math display">\[H_1 :\mu _1  &lt; \mu _2\]</span></p>
<p>anche se queste ipotesi alternative debbono essere ragionevolmente fatte prima di eseguire l’esperimento, non dopo averne visto i risultati.</p>
<p>Quale statistica potrebbe meglio descrivere l’andamento dell’esperimento, in relazione all’ipotesi nulla? E’ evidente che questa statistica dovrebbe essere basata su due indicatori diversi:</p>
<ol style="list-style-type: decimal">
<li>l’entità della differenza tra le medie: più la differenza tra le due medie è alta e più è probabile che essa sia significativa;</li>
<li>l’entità dell’errore standard. Più è elevata la variabilità dei dati (e quindi l’errore di stima) più è bassa la probabilità che le differenze osservate tra le medie siano significative.</li>
</ol>
<p>Su queste basi, si può individuare la seguente statistica:</p>
<p><span class="math display">\[T = \frac{m_1 - m_2}{SED}\]</span></p>
<p>Si può osservare che T, in realtà, non è altro che il rapporto tra le quantità indicate in precedenza ai punti 1 e 2: infatti la quantità al numeratore è la differenza tra le medie dei due campioni, mentre la quantità al denominatore è il cosiddetto errore standard della differenza tra due medie (SED). Quest’ultima quantità si può ottenere pensando che i due campioni sono estratti in modo indipendente e, pertanto, la varianza della somma (algebrica) è uguale alla somma delle varianze. La varianza delle due medie è data dal quadrato delle loro deviazioni standard, cioè dal quadrato degli errori standard. Pertanto:</p>
<p><span class="math display">\[SED^2 = SEM_1^2 + SEM_2^2\]</span></p>
<p>Sappiamo anche che il SEM si ottiene dividendo la deviazione standard di ogni campione per la radice quadrata del numero dei dati, quindi:</p>
<p><span class="math display">\[SED^2 = \frac{s_1^2}{n_1} +  \frac{s_2^2}{n_2}\]</span></p>
<p>cioè:</p>
<p><span class="math display">\[SED = \sqrt{ \frac{s_1^2}{n_1} +  \frac{s_2^2}{n_2} }\]</span></p>
<p>Possiamo anche scrivere:</p>
<p><span class="math display">\[SED = \sqrt{ \frac{s_1^2 \, n_2 + s_2^2 \, n_1}{n_1 \, n_2} }\]</span></p>
<p>e, se le varianze sono uguali (<span class="math inline">\(s_1^2 = s_2^2 = s^2\)</span>), segue che:</p>
<p><span class="math display">\[SED = \sqrt {s^2 \frac{n_1  + n_2}{n_1 \, n_2 } }\]</span></p>
<p>Se fosse anche <span class="math inline">\(n_1 = n_2 =n\)</span>, potremmo scrivere:</p>
<p><span class="math display">\[SED = \sqrt{2 \, \frac{s^2}{n} } = \sqrt{2} \times SEM\]</span></p>
<p>Il valore osservato per T è quindi uguale a:</p>
<p><span class="math display">\[T = \frac{85.4 - 70.2}{3.361547} = 4.5217\]</span></p>
<p>dove il denominatore è ottenuto come:</p>
<p><span class="math display">\[SED = \sqrt{ 2.18^2 +  2.56^2 } = 3.361547\]</span></p>
<p>A questo punto avendo osservato T = 4.5217, possiamo chiederci qual è la ‘sampling distribution’ per T, cioè quali valori potrebbe assumere questa statistica se ripetessimo il campionamento infinite volte, assumendo che l’ipotesi nulla fosse vera.</p>
<p>La sampling distribution per T potrebbe essere ottenuta empiricamente, utilizzando una simulazione MONTE CARLO ed immaginando di estrarre numerose coppie di campioni, dalla stessa distribuzione normale, analogamente a quanto abbiamo fatto nell’esempio precedente. Se l’ipotesi nulla è vera, possiamo immaginare che questa distribuzione gaussiana abbia una media pari a (70.2 + 85.4)/2 = 77.8 e una deviazione standard pari alla deviazione standard delle dieci osservazioni (tutte insieme, senza distinzioni di trattamento), cioè 5.71.</p>
<p>Il codice da utilizzare in R per le simulazioni è il seguente:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">victo &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">65</span>, <span class="dv">68</span>, <span class="dv">69</span>, <span class="dv">71</span>, <span class="dv">78</span>)
lucrezia &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">80</span>, <span class="dv">81</span>, <span class="dv">84</span>, <span class="dv">88</span>, <span class="dv">94</span>)
media &lt;-<span class="st"> </span><span class="kw">mean</span>(<span class="kw">c</span>(victo, lucrezia))
devSt &lt;-<span class="st"> </span><span class="kw">sd</span>(<span class="kw">c</span>(victo, lucrezia))
<span class="kw">set.seed</span>(<span class="dv">1234</span>)
result &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">100000</span>)
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">100000</span>){
  sample1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">5</span>, media, devSt)
  sample2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">5</span>, media, devSt)
  SED &lt;-<span class="st"> </span><span class="kw">sqrt</span>( (<span class="kw">sd</span>(sample1)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">5</span>))<span class="op">^</span><span class="dv">2</span> <span class="op">+</span>
<span class="st">                 </span>(<span class="kw">sd</span>(sample2)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">5</span>))<span class="op">^</span><span class="dv">2</span> )
  result[i] &lt;-<span class="st"> </span>(<span class="kw">mean</span>(sample1) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(sample2)) <span class="op">/</span><span class="st"> </span>SED
}</code></pre></div>
<p>I risultati delle 100’000 simulazioni sono riportati nel grafico sottostante. Possiamo notare che, dei 100’000 valori di T osservati assumendo vera l’ipotesi nulla, solo l’un per mille sono superiori a quello da noi osservato e altrettanti sono inferiori a -4.5217. In totale, la probabilità di osservare un valore di T così alto in valore assoluto e dello 0.21 %.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">SED_obs &lt;-<span class="st"> </span><span class="kw">sqrt</span>( (<span class="kw">sd</span>(victo)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">5</span>))<span class="op">^</span><span class="dv">2</span> <span class="op">+</span>
<span class="st">                   </span>(<span class="kw">sd</span>(lucrezia)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">5</span>))<span class="op">^</span><span class="dv">2</span> )
T_obs &lt;-<span class="st"> </span>(<span class="kw">mean</span>(victo) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(lucrezia))<span class="op">/</span>SED_obs
(<span class="kw">length</span>(result[result <span class="op">&lt;</span><span class="st"> </span>T_obs]) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">length</span>(result[result <span class="op">&gt;</span><span class="st"> </span><span class="op">-</span><span class="st"> </span>T_obs])) <span class="op">/</span><span class="dv">100000</span></code></pre></div>
<pre><code>## [1] 0.00164</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Codice Grafico </span>
b &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="dv">12</span>, <span class="dv">12</span>, <span class="dt">by=</span><span class="fl">0.25</span>)
<span class="kw">hist</span>(result, <span class="dt">breaks =</span> b, <span class="dt">freq=</span>F, <span class="dt">xlab =</span> <span class="kw">expression</span>(<span class="kw">paste</span>(m)), <span class="dt">ylab=</span><span class="st">&quot;Density&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">10</span>,<span class="dv">10</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.45</span>), <span class="dt">main=</span><span class="st">&quot;&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">curve</span>(<span class="kw">dnorm</span>(x), <span class="dt">add=</span>T, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-92-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">curve</span>(<span class="kw">dt</span>(x, <span class="dv">8</span>), <span class="dt">add=</span>T, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)
<span class="kw">abline</span>(<span class="dt">v =</span> <span class="fl">4.52</span>, <span class="dt">lty =</span> <span class="dv">2</span>)
<span class="kw">abline</span>(<span class="dt">v =</span> <span class="op">-</span><span class="fl">4.52</span>, <span class="dt">lty =</span> <span class="dv">2</span>)
<span class="kw">text</span>(<span class="dv">5</span>, <span class="fl">0.4</span>, <span class="dt">label=</span><span class="st">&quot;4.52&quot;</span>, <span class="dt">adj=</span><span class="dv">0</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)
<span class="kw">text</span>(<span class="op">-</span><span class="dv">5</span>, <span class="fl">0.4</span>, <span class="dt">label=</span><span class="st">&quot;-4.52&quot;</span>, <span class="dt">adj=</span><span class="dv">1</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-92-3.png" width="672" /></p>
<p>In modo più formale, sempre analogamente all’esempio precedente, si può dimostrare che la sampling distribution per T è costituita dalla distribuzione t di Student, con 8 gradi di libertà (quattro per campione). A questo punto siamo in grado di calcolare la probabilità di ottenere valori di T altrettanto estremi o più estremi di quello da noi osservato, tenendo però presente che il test è ‘a due code’, nel senso che dobbiamo considerare T osservato e il suo reciproco, che avremmo ottenuto se avessimo cambiato il senso della differenza (<span class="math inline">\(m_2 - m_1\)</span> invece che <span class="math inline">\(m_1 - m_2\)</span>). In altre parole ci chiediamo qual è la possibilità di campionare valori esterni all’intervallo (-4.5217; 4.5217).</p>
<p>Possiamo ottenere questa informazione utilizzando la funzione:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">pt</span>(T_obs, <span class="dv">8</span>, <span class="dt">lower.tail=</span>T)</code></pre></div>
<pre><code>## [1] 1.998055</code></pre>
<p>Abbiamo moltiplicato per 2 il risultato, in quanto la funzione ‘dt()’ fornisce la probabilità di trovare individui inferiori a -4.5217 (‘lower.tail = T’), che, essendo la distribuzione simmetrica, è esattamente uguale alla probabilità di trovare soggetti superiori a 4.5217.</p>
<p>Vediamo che il P-level è minore di 0.05 e possiamo quindi rifiutare l’ipotesi nulla. Concludiamo che vi è un’evidenza scientifica abbastanza forte per ritenere che l’erbicida A induca una riduzione del peso delle piante trattate.</p>
<p>Allo stesso valore, più semplicemente, si perviene utilizzando la funzione:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(victo, lucrezia, <span class="dt">var.equal=</span>T)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  victo and lucrezia
## t = -4.5217, df = 8, p-value = 0.001945
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -22.951742  -7.448258
## sample estimates:
## mean of x mean of y 
##      70.2      85.4</code></pre>
<p>Gli argomenti della funzione ‘t.test()’ sono i due vettori è l’argomento ‘var.equal’, che in questo caso è stato settato su TRUE. Per comprendere il significato di quest’ultimo argomento dobbiamo vedere quali sono le tipologie di t test possibili.</p>
</div>
</div>
<div id="approfondimento-tipologie-alternative-di-test-t" class="section level2">
<h2><span class="header-section-number">8.6</span> Approfondimento: tipologie alternative di test t</h2>
<p>Il test t può essere di tre tipi:</p>
<ol style="list-style-type: decimal">
<li>Appaiato. In questo caso le misure sono prese a coppia sullo stesso soggetto e non sono quindi indipendenti.</li>
<li>Omoscedastico. Le misure sono prese su soggetti diversi (indipendenti) e possiamo suppore che i due campioni provengano da due popolazioni con la stessa varianza.</li>
<li>Eteroscedastico. Le misure sono prese su soggetti diversi, ma le varianze non sono omogenee.</li>
</ol>
<p>Nel nostro esempio vediamo che le varianze dei campioni sono piuttosto simili e quindi adottiamo un test t omoscedastico (‘var.equal = T’).</p>
<p>Se dovessimo supporre che i due campioni provengono da popolazioni con varianze diverse, allora si porrebbe il problema di stabilire il numero di gradi di libertà del SEM. Abbiamo visto che se le varianze dei due campioni sono uguali (o meglio, sono due stime della stessa varianza), la varianza della somma/differenza ha un ha un numero di gradi di libertà pari alla somma dei gradi di libertà delle due varianze. Se le varianze fossero diverse, il numero di gradi di libertà della loro combinazione lineare (somma o differenza) si dovrebbe approssimare con la formula di Satterthwaite:</p>
<p><span class="math display">\[DF_s \simeq \frac{ \left( s^2_1 + s^2_2 \right)^2 }{ \frac{(s^2_1)^2}{DF_1} + \frac{(s^2_2)^2}{DF_2} }\]</span></p>
<p>Vediamo che se le varianze e i gradi di libertà sono uguali, la formula precedente riduce a:</p>
<p><span class="math display">\[DF_s = 2 \times DF\]</span></p>
<p>Nel nostro caso, se fosse <span class="math inline">\(s^2_1 \neq s^2_2\)</span> avremmo un numero frazionario di gradi di libertà:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dfS &lt;-<span class="st"> </span>(<span class="kw">var</span>(victo) <span class="op">+</span><span class="st"> </span><span class="kw">var</span>(lucrezia))<span class="op">^</span><span class="dv">2</span> <span class="op">/</span><span class="st"> </span>
<span class="st">  </span>((<span class="kw">var</span>(victo)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">4</span> <span class="op">+</span><span class="st"> </span>(<span class="kw">var</span>(lucrezia)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">4</span>)
dfS</code></pre></div>
<pre><code>## [1] 7.79772</code></pre>
<p>Il risultato può essere riscontrato con:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(victo, lucrezia, <span class="dt">var.equal=</span>F)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  victo and lucrezia
## t = -4.5217, df = 7.7977, p-value = 0.002076
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -22.986884  -7.413116
## sample estimates:
## mean of x mean of y 
##      70.2      85.4</code></pre>
<p>Se invece avessimo rilevato le misure accoppiate su quattro individui avremmo solo 4 gradi di libertà:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(victo, lucrezia, <span class="dt">var.equal=</span>T, <span class="dt">paired=</span>T)</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  victo and lucrezia
## t = -22.915, df = 4, p-value = 2.149e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -17.04169 -13.35831
## sample estimates:
## mean of the differences 
##                   -15.2</code></pre>
</div>
<div id="confronto-tra-due-proporzioni" class="section level2">
<h2><span class="header-section-number">8.7</span> Confronto tra due proporzioni</h2>
<p>Il test di t è molto utile, ma soltanto nel caso in cui si abbia a che fare con caratteri quantitativi, cioè con variabili misurate su una scala continua, per le quali sia possibile calcolare delle statistiche descrittive, come appunto la media.</p>
<p>In molti casi, gli sperimentatori sono interessati a rilevare alcune caratteristiche qualitative, come ad esempio lo stato di una pianta in seguito ad un trattamento (morta o viva), il colore dei semi (si ricordino i piselli verdi e gialli di Mendel) ed altre caratteristiche che non sono misurabili facilmente su una scala continua.</p>
<p>Avendo a che fare con variabili qualitative l’unico dato che si può rilevare è la proporzione degli individui che presentano le diverse modalità. Proviamo ad osservare il seguente esempio.</p>
<div id="esempio-3-2" class="section level3">
<h3><span class="header-section-number">8.7.1</span> ESEMPIO 3</h3>
<p>Immaginiamo di voler verificare se un coadiuvante aumenta l’efficacia di un erbicida organizziamo un esperimento in cui utilizziamo l’erbicida da solo e con il coadiuvante. Nel primo caso (erbicida da solo) otteniamo 56 morti su 75 piante trattate, mentre nel secondo caso otteniamo 48 morti su 50 piante trattate.</p>
<p>I risultati del nostro esperimento si riducono ad una tabella di contingenza di questo tipo:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">counts &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">56</span>, <span class="dv">19</span>, <span class="dv">48</span>, <span class="dv">2</span>)
tab &lt;-<span class="st"> </span><span class="kw">matrix</span>(counts, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dt">byrow =</span> T)
<span class="kw">row.names</span>(tab) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;E&quot;</span>, <span class="st">&quot;EC&quot;</span>)
<span class="kw">colnames</span>(tab) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;M&quot;</span>, <span class="st">&quot;V&quot;</span>)
tab</code></pre></div>
<pre><code>##     M  V
## E  56 19
## EC 48  2</code></pre>
<p>Abbiamo già visto nel capitolo sulla statistica descrittiva come è possibile costruire un indice di connessione (detto <span class="math inline">\(\chi^2\)</span>) che misura la quantità del ‘legame’ tra le due variabili rilevate (trattamento e mortalità). Ci stiamo infatti chiedendo se il numero dei morti è indipendente dal tipo di trattamento oppure no.</p>
<p>Sappiamo già come calcolare il <span class="math inline">\(\chi^2\)</span> con R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>( <span class="kw">as.table</span>(tab) )</code></pre></div>
<pre><code>## Number of cases in table: 125 
## Number of factors: 2 
## Test for independence of all factors:
##  Chisq = 9.768, df = 1, p-value = 0.001776</code></pre>
<p>Il valore osservato è pari a 9.768. Siccome siamo in ambito inferenziale, dobbiamo ricordare che non ci interessa il confronto tra proporzioni osservate nel caso in studio, ma ci interessa il confronto delle proporzioni delle popolazione da cui i due campioni (uno di 75 l’altro di 50 individui) sono stati estratti. Di conseguenza, è possibile che, pur essendo vera l’ipotesi nulla, noi abbiamo ottenuto un valore maggiore di zero per effetto del campionamento e dell’errore sperimentale, cioè per il solo effetto del caso. Ma quanto è probabile questa evenienza?</p>
<p>Poniamo l’ipotesi nulla in questi termini:</p>
<p><span class="math display">\[H_o :\pi_1  = \pi_2  = \pi\]</span></p>
<p>Ci chiediamo: se l’ipotesi nulla è vera (<span class="math inline">\(\pi_1 = \pi_2\)</span>), qual è la sampling distribution per <span class="math inline">\(\chi^2\)</span>? E’possibile simulare questo esperimento immaginando di campionare da una distribuzione binomiale con <span class="math inline">\(\pi\)</span> = 0.832 il numero di successi su 75 esperimenti (che corrisponde alla prima cella in alto a sinistra della tabella di contingenza precedente). Per differenza con i totali marginali possiamo poi dedurre le altre tre frequenze e calcolare il valore di <span class="math inline">\(\chi^2\)</span>.</p>
<p>La simulazione di un test di <span class="math inline">\(\chi^2\)</span> può esser fatta utilizzando la funzione ‘r2dtable()’ che produce il numero voluto di tabelle di contingenza, con righe e colonne indipendenti r rispettando i totali marginali voluti. Le tabelle prodotte (nel nostro caso 10’000) sono restituite come lista, quindi possiamo utilizzare la funzione ‘lapply()’ per applicare ad ogni elemento della lista la funzione che restituisce il <span class="math inline">\(\chi^2\)</span> (‘chiSim’).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">chiSim &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="kw">summary</span>(<span class="kw">as.table</span>(x))<span class="op">$</span>stat
<span class="kw">set.seed</span>(<span class="dv">1234</span>)
tabs &lt;-<span class="st"> </span><span class="kw">r2dtable</span>(<span class="dv">10000</span>, <span class="kw">apply</span>(tab, <span class="dv">1</span>, sum), <span class="kw">apply</span>(tab, <span class="dv">2</span>, sum))
chiVals &lt;-<span class="st"> </span><span class="kw">as.numeric</span>( <span class="kw">lapply</span>( tabs, chiSim) )
<span class="kw">length</span>(chiVals[chiVals <span class="op">&gt;</span><span class="st"> </span><span class="fl">9.768</span>])</code></pre></div>
<pre><code>## [1] 22</code></pre>
<p>Vediamo che vi sono 19 valori più alti di quello da noi osservato (p = 0.0019).</p>
<p>In modo formale, si può dimostrare che, se <span class="math inline">\(n\)</span> è sufficientemente grande (n &gt; 30), il valore osservato di <span class="math inline">\(\chi^2\)</span> segue appunto la distribuzione della variabile casuale <span class="math inline">\(\chi^2\)</span>, con un numero di gradi di libertà <span class="math inline">\(\nu\)</span> pari al numero dei confronti (in questo caso 1). Possiamo quindi utilizzare questa variabile casuale per calcolare la probabilità di ottenere valori pari o superiori a 9.768:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pchisq</span>(<span class="fl">9.76801</span>, <span class="dv">1</span>, <span class="dt">lower.tail=</span>F)</code></pre></div>
<pre><code>## [1] 0.001775746</code></pre>
<p>Allo stesso risultato, ma in modo più semplice, è possibile pervenire utilizzando la già vista funnzione ‘summary()’ applicata alla tabella di contingenza (vedi sopra), oppure:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">chisq.test</span>(tab, <span class="dt">correct=</span>F)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tab
## X-squared = 9.768, df = 1, p-value = 0.001776</code></pre>
</div>
</div>
<div id="conclusioni-1" class="section level2">
<h2><span class="header-section-number">8.8</span> Conclusioni</h2>
<p>Abbiamo visto quale strumento abbiamo a disposizione per tirare conclusioni in presenza di incertezza sperimentale. Dovrebbe essere evidente che anche le nostre conclusioni sono incerte, in quanto soggette all’errore di campionamento. In particolare, abbiamo visto che esiste un rischio di errore di prima specie, cioè rifiutare erronamente l’ipotesi nulla (falso positivo). Allo stesso modo, esiste anche un rischio di errore di II specie, cioè accettare erroneamente l’ipotesi nulla (falso negativo). Dei due errori parleremo in una dispensa specifica.</p>
</div>
<div id="riepilogo" class="section level2">
<h2><span class="header-section-number">8.9</span> Riepilogo</h2>
<p>Lo schema di lavoro, nel test d’ipotesi, è il seguente:</p>
<ol style="list-style-type: decimal">
<li>Si formula l’ipotesi nulla;</li>
<li>Si individua una statistica che descriva l’andamento dell’esperimento, in relazione all’ipotesi nulla;</li>
<li>Si individua la sampling distribution per questa statistica, assumendo vera l’ipotesi nulla; la sampling distribution può essere empirica (ottenuta per simulazione) o teorica, scelta in base a considerazioni probabilistiche</li>
<li>Si calcola la probabilità che, essendo vera l’ipotesi nulla, si possa osservare una valore altrettanto estremo o più estremo di quello calcolato, per la statistica di riferimento;</li>
<li>Se il livello di probabilità è inferiore ad una certa soglia <span class="math inline">\(\alpha\)</span> prefissata (generalmente 0.05), si rifiuta l’ipotesi nulla.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelli-matamatici-descrittivi-breve-introduzione.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
