<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Metodologia di sperimentazione in agricoltura</title>
  <meta name="description" content="Appunti dalle lezioni (A.A. 2017-2018)">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Metodologia di sperimentazione in agricoltura" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Appunti dalle lezioni (A.A. 2017-2018)" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Metodologia di sperimentazione in agricoltura" />
  
  <meta name="twitter:description" content="Appunti dalle lezioni (A.A. 2017-2018)" />
  

<meta name="author" content="Andrea Onofri">


<meta name="date" content="2019-01-21">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html">
<link rel="next" href="referenze-bibliografiche.html">
<script src="book_assets/jquery-2.2.3/jquery.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduzione</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#organizzazione-del-corso"><i class="fa fa-check"></i><b>1.1</b> Organizzazione del corso</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#esercitazioni-pratiche"><i class="fa fa-check"></i><b>1.2</b> Esercitazioni pratiche</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#obiettivi-specifici-del-corso"><i class="fa fa-check"></i><b>1.3</b> Obiettivi specifici del Corso</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><i class="fa fa-check"></i><b>2</b> Il metodo sperimentale: quando la scienza è scienza</a><ul>
<li class="chapter" data-level="2.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#introduzione-1"><i class="fa fa-check"></i><b>2.1</b> Introduzione</a><ul>
<li class="chapter" data-level="2.1.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#cosa-e-quindi-una-prova-scientifica"><i class="fa fa-check"></i><b>2.1.1</b> Cosa è quindi una prova scientifica?</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#esperimenti-buoni-e-cattivi"><i class="fa fa-check"></i><b>2.2</b> Esperimenti buoni e cattivi!</a><ul>
<li class="chapter" data-level="2.2.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#lerrore-sperimentale"><i class="fa fa-check"></i><b>2.2.1</b> L’errore sperimentale</a></li>
<li class="chapter" data-level="2.2.2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#il-campionamento"><i class="fa fa-check"></i><b>2.2.2</b> Il campionamento</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#scienza-metodo"><i class="fa fa-check"></i><b>2.3</b> Scienza = metodo</a></li>
<li class="chapter" data-level="2.4" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#chi-valuta-se-un-esperimento-e-attendibile"><i class="fa fa-check"></i><b>2.4</b> Chi valuta se un esperimento è attendibile?</a></li>
<li class="chapter" data-level="2.5" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#il-metodo-sperimentale"><i class="fa fa-check"></i><b>2.5</b> Il metodo sperimentale</a></li>
<li class="chapter" data-level="2.6" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#metodi-sperimentali-validi-ed-invalidi"><i class="fa fa-check"></i><b>2.6</b> Metodi sperimentali validi ed invalidi</a><ul>
<li class="chapter" data-level="2.6.1" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#primo-esperimento"><i class="fa fa-check"></i><b>2.6.1</b> Primo esperimento</a></li>
<li class="chapter" data-level="2.6.2" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#secondo-esperimento"><i class="fa fa-check"></i><b>2.6.2</b> Secondo esperimento</a></li>
<li class="chapter" data-level="2.6.3" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#terzo-esperimento"><i class="fa fa-check"></i><b>2.6.3</b> Terzo esperimento</a></li>
<li class="chapter" data-level="2.6.4" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#quarto-esperimento-quello-buono"><i class="fa fa-check"></i><b>2.6.4</b> Quarto esperimento: quello buono</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#incertezza-residua"><i class="fa fa-check"></i><b>2.7</b> Incertezza residua</a></li>
<li class="chapter" data-level="2.8" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#il-ruolo-della-statistica"><i class="fa fa-check"></i><b>2.8</b> Il ruolo della statistica</a></li>
<li class="chapter" data-level="2.9" data-path="il-metodo-sperimentale-quando-la-scienza-e-scienza.html"><a href="il-metodo-sperimentale-quando-la-scienza-e-scienza.html#conclusioni"><i class="fa fa-check"></i><b>2.9</b> Conclusioni</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html"><i class="fa fa-check"></i><b>3</b> Introduzione al disegno sperimentale</a><ul>
<li class="chapter" data-level="3.1" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#definizioni"><i class="fa fa-check"></i><b>3.1</b> Definizioni</a></li>
<li class="chapter" data-level="3.2" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#elementi-fondamentali-del-disegno-sperimentale"><i class="fa fa-check"></i><b>3.2</b> Elementi fondamentali del disegno sperimentale</a><ul>
<li class="chapter" data-level="3.2.1" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#controllo-degli-errori"><i class="fa fa-check"></i><b>3.2.1</b> Controllo degli errori</a></li>
<li class="chapter" data-level="3.2.2" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#replicazione"><i class="fa fa-check"></i><b>3.2.2</b> Replicazione</a></li>
<li class="chapter" data-level="3.2.3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#randomizzazione"><i class="fa fa-check"></i><b>3.2.3</b> Randomizzazione</a></li>
<li class="chapter" data-level="3.2.4" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#esperimenti-non-validi"><i class="fa fa-check"></i><b>3.2.4</b> Esperimenti non validi</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#progettazione-di-un-esperimento-protocollo"><i class="fa fa-check"></i><b>3.3</b> Progettazione di un esperimento (protocollo)</a><ul>
<li class="chapter" data-level="3.3.1" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#ipotesi-scientifica-rightarrow-obiettivo-dellesperimento"><i class="fa fa-check"></i><b>3.3.1</b> Ipotesi scientifica <span class="math inline">\(\rightarrow\)</span> obiettivo dell’esperimento</a></li>
<li class="chapter" data-level="3.3.2" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---1"><i class="fa fa-check"></i><b>3.3.2</b> Casi di studio - 1</a></li>
<li class="chapter" data-level="3.3.3" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#identificazione-dei-fattori-sperimentali"><i class="fa fa-check"></i><b>3.3.3</b> Identificazione dei fattori sperimentali</a></li>
<li class="chapter" data-level="3.3.4" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#esperimenti-multifattoriali"><i class="fa fa-check"></i><b>3.3.4</b> Esperimenti (multi)fattoriali</a></li>
<li class="chapter" data-level="3.3.5" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#aggiungere-un-controllo"><i class="fa fa-check"></i><b>3.3.5</b> Aggiungere un controllo?</a></li>
<li class="chapter" data-level="3.3.6" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#fattori-sperimentali-di-trattamento-e-di-blocco"><i class="fa fa-check"></i><b>3.3.6</b> Fattori sperimentali di trattamento e di blocco</a></li>
<li class="chapter" data-level="3.3.7" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---2"><i class="fa fa-check"></i><b>3.3.7</b> Casi di studio - 2</a></li>
<li class="chapter" data-level="3.3.8" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#identificazione-delle-unita-sperimentali-e-delle-repliche"><i class="fa fa-check"></i><b>3.3.8</b> Identificazione delle unità sperimentali e delle repliche</a></li>
<li class="chapter" data-level="3.3.9" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#scelta-delle-variabili-da-rilevare"><i class="fa fa-check"></i><b>3.3.9</b> Scelta delle variabili da rilevare</a></li>
<li class="chapter" data-level="3.3.10" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---3"><i class="fa fa-check"></i><b>3.3.10</b> Casi di studio - 3</a></li>
<li class="chapter" data-level="3.3.11" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#allocazione-dei-trattamenti"><i class="fa fa-check"></i><b>3.3.11</b> Allocazione dei trattamenti</a></li>
<li class="chapter" data-level="3.3.12" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#casi-di-studio---4"><i class="fa fa-check"></i><b>3.3.12</b> Casi di studio - 4</a></li>
<li class="chapter" data-level="3.3.13" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#impianto-delle-prove"><i class="fa fa-check"></i><b>3.3.13</b> Impianto delle prove</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#come-scrivere-un-progetto-di-ricerca-o-un-report-di-ricerca"><i class="fa fa-check"></i><b>3.4</b> Come scrivere un progetto di ricerca o un report di ricerca</a></li>
<li class="chapter" data-level="3.5" data-path="introduzione-al-disegno-sperimentale.html"><a href="introduzione-al-disegno-sperimentale.html#per-approfondimenti"><i class="fa fa-check"></i><b>3.5</b> Per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html"><i class="fa fa-check"></i><b>4</b> Per iniziare: introduzione ad R</a><ul>
<li class="chapter" data-level="4.1" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#cosa-e-r"><i class="fa fa-check"></i><b>4.1</b> Cosa è R?</a></li>
<li class="chapter" data-level="4.2" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#oggetti-e-assegnazioni"><i class="fa fa-check"></i><b>4.2</b> Oggetti e assegnazioni</a></li>
<li class="chapter" data-level="4.3" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#costanti-e-vettori"><i class="fa fa-check"></i><b>4.3</b> Costanti e vettori</a></li>
<li class="chapter" data-level="4.4" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#matrici"><i class="fa fa-check"></i><b>4.4</b> Matrici</a></li>
<li class="chapter" data-level="4.5" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#operazioni-ed-operatori"><i class="fa fa-check"></i><b>4.5</b> Operazioni ed operatori</a></li>
<li class="chapter" data-level="4.6" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#funzioni-ed-argomenti"><i class="fa fa-check"></i><b>4.6</b> Funzioni ed argomenti</a></li>
<li class="chapter" data-level="4.7" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#dataframe"><i class="fa fa-check"></i><b>4.7</b> Dataframe</a></li>
<li class="chapter" data-level="4.8" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#quale-oggetto-sto-utilizzando"><i class="fa fa-check"></i><b>4.8</b> Quale oggetto sto utilizzando?</a></li>
<li class="chapter" data-level="4.9" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#consigli-per-limmissione-di-dati-sperimentali"><i class="fa fa-check"></i><b>4.9</b> Consigli per l’immissione di dati sperimentali</a><ul>
<li class="chapter" data-level="4.9.1" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#immissione-manuale-di-dati"><i class="fa fa-check"></i><b>4.9.1</b> Immissione manuale di dati</a></li>
<li class="chapter" data-level="4.9.2" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#immissione-di-numeri-progressivi"><i class="fa fa-check"></i><b>4.9.2</b> Immissione di numeri progressivi</a></li>
<li class="chapter" data-level="4.9.3" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#immissione-dei-codici-delle-tesi-e-dei-blocchi"><i class="fa fa-check"></i><b>4.9.3</b> Immissione dei codici delle tesi e dei blocchi</a></li>
<li class="chapter" data-level="4.9.4" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#leggere-e-salvare-dati-esterni"><i class="fa fa-check"></i><b>4.9.4</b> Leggere e salvare dati esterni</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#alcune-operazioni-comuni-sul-dataset"><i class="fa fa-check"></i><b>4.10</b> Alcune operazioni comuni sul dataset</a><ul>
<li class="chapter" data-level="4.10.1" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#selezionare-un-subset-di-dati"><i class="fa fa-check"></i><b>4.10.1</b> Selezionare un subset di dati</a></li>
<li class="chapter" data-level="4.10.2" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#ordinare-un-vettore-o-un-dataframe"><i class="fa fa-check"></i><b>4.10.2</b> Ordinare un vettore o un dataframe</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#workspace"><i class="fa fa-check"></i><b>4.11</b> Workspace</a></li>
<li class="chapter" data-level="4.12" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#script-o-programmi"><i class="fa fa-check"></i><b>4.12</b> Script o programmi</a></li>
<li class="chapter" data-level="4.13" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#interrogazione-di-oggetti"><i class="fa fa-check"></i><b>4.13</b> Interrogazione di oggetti</a></li>
<li class="chapter" data-level="4.14" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#altre-funzioni-matriciali"><i class="fa fa-check"></i><b>4.14</b> Altre funzioni matriciali</a></li>
<li class="chapter" data-level="4.15" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#cenni-sulle-funzionalita-grafiche-in-r"><i class="fa fa-check"></i><b>4.15</b> Cenni sulle funzionalità grafiche in R</a></li>
<li class="chapter" data-level="4.16" data-path="per-iniziare-introduzione-ad-r.html"><a href="per-iniziare-introduzione-ad-r.html#per-approfondimenti-1"><i class="fa fa-check"></i><b>4.16</b> Per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html"><i class="fa fa-check"></i><b>5</b> Primo passo: la descrizione dei dati raccolti</a><ul>
<li class="chapter" data-level="5.1" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#le-variabili-quantitative-analisi-chimiche-e-altre-misurazioni-fondamentali"><i class="fa fa-check"></i><b>5.1</b> Le variabili quantitative: analisi chimiche e altre misurazioni fondamentali</a><ul>
<li class="chapter" data-level="5.1.1" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#indicatori-di-tendenza-centrale"><i class="fa fa-check"></i><b>5.1.1</b> Indicatori di tendenza centrale</a></li>
<li class="chapter" data-level="5.1.2" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#indicatori-di-variabilita"><i class="fa fa-check"></i><b>5.1.2</b> Indicatori di variabilità</a></li>
<li class="chapter" data-level="5.1.3" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#arrotondamenti"><i class="fa fa-check"></i><b>5.1.3</b> Arrotondamenti</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#descrizione-dei-sottogruppi"><i class="fa fa-check"></i><b>5.2</b> Descrizione dei sottogruppi</a></li>
<li class="chapter" data-level="5.3" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#distribuzioni-di-frequenza-e-classamento"><i class="fa fa-check"></i><b>5.3</b> Distribuzioni di frequenza e classamento</a></li>
<li class="chapter" data-level="5.4" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#statistiche-descrittive-per-le-distribuzioni-di-frequenza"><i class="fa fa-check"></i><b>5.4</b> Statistiche descrittive per le distribuzioni di frequenza</a></li>
<li class="chapter" data-level="5.5" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#distribuzioni-di-frequenza-bivariate-le-tabelle-di-contingenza"><i class="fa fa-check"></i><b>5.5</b> Distribuzioni di frequenza bivariate: le tabelle di contingenza</a></li>
<li class="chapter" data-level="5.6" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#connessione"><i class="fa fa-check"></i><b>5.6</b> Connessione</a></li>
<li class="chapter" data-level="5.7" data-path="primo-passo-la-descrizione-dei-dati-raccolti.html"><a href="primo-passo-la-descrizione-dei-dati-raccolti.html#correlazione"><i class="fa fa-check"></i><b>5.7</b> Correlazione</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html"><i class="fa fa-check"></i><b>6</b> Dalla popolazione al campione. I modelli stocastici</a><ul>
<li class="chapter" data-level="6.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#introduzione-2"><i class="fa fa-check"></i><b>6.1</b> Introduzione</a></li>
<li class="chapter" data-level="6.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#popolazione-di-soggetti-e-popolazione-di-misure"><i class="fa fa-check"></i><b>6.2</b> Popolazione di soggetti e popolazione di misure</a></li>
<li class="chapter" data-level="6.3" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-scienza-del-caso"><i class="fa fa-check"></i><b>6.3</b> La scienza del caso</a></li>
<li class="chapter" data-level="6.4" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#modelli-probabilistici-stocastici"><i class="fa fa-check"></i><b>6.4</b> Modelli probabilistici (stocastici)</a><ul>
<li class="chapter" data-level="6.4.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#funzioni-di-probabilita"><i class="fa fa-check"></i><b>6.4.1</b> Funzioni di probabilità</a></li>
<li class="chapter" data-level="6.4.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#funzioni-di-densita"><i class="fa fa-check"></i><b>6.4.2</b> Funzioni di densità</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-distribuzione-normale-curva-di-gauss"><i class="fa fa-check"></i><b>6.5</b> La distribuzione normale (curva di Gauss)</a><ul>
<li class="chapter" data-level="6.5.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-1"><i class="fa fa-check"></i><b>6.5.1</b> ESERCIZIO 1</a></li>
<li class="chapter" data-level="6.5.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-2"><i class="fa fa-check"></i><b>6.5.2</b> ESERCIZIO 2</a></li>
<li class="chapter" data-level="6.5.3" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-3"><i class="fa fa-check"></i><b>6.5.3</b> ESERCIZIO 3</a></li>
<li class="chapter" data-level="6.5.4" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-4"><i class="fa fa-check"></i><b>6.5.4</b> ESERCIZIO 4</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-distribuzione-t-di-student"><i class="fa fa-check"></i><b>6.6</b> La distribuzione t di Student</a><ul>
<li class="chapter" data-level="6.6.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-5"><i class="fa fa-check"></i><b>6.6.1</b> ESERCIZIO 5</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#la-distribuzione-f-di-fisher"><i class="fa fa-check"></i><b>6.7</b> La distribuzione F di Fisher</a><ul>
<li class="chapter" data-level="6.7.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-6"><i class="fa fa-check"></i><b>6.7.1</b> ESERCIZIO 6</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#modelli-stocastici-per-eventi-discreti-la-distribuzione-binomiale"><i class="fa fa-check"></i><b>6.8</b> Modelli stocastici per eventi discreti: la distribuzione binomiale</a><ul>
<li class="chapter" data-level="6.8.1" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-7"><i class="fa fa-check"></i><b>6.8.1</b> ESERCIZIO 7</a></li>
<li class="chapter" data-level="6.8.2" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#esercizio-8"><i class="fa fa-check"></i><b>6.8.2</b> ESERCIZIO 8</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#ltri-modelli-stocastici-di-interesse-per-lo-sperimentatore"><i class="fa fa-check"></i><b>6.9</b> ltri modelli stocastici di interesse per lo sperimentatore</a></li>
<li class="chapter" data-level="6.10" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#e-allora"><i class="fa fa-check"></i><b>6.10</b> E allora?</a></li>
<li class="chapter" data-level="6.11" data-path="dalla-popolazione-al-campione-i-modelli-stocastici.html"><a href="dalla-popolazione-al-campione-i-modelli-stocastici.html#le-simulazioni-monte-carlo"><i class="fa fa-check"></i><b>6.11</b> Le simulazioni Monte Carlo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><i class="fa fa-check"></i><b>7</b> Modellizzare l’errore sperimentale: introduzione all’inferenza statistica</a><ul>
<li class="chapter" data-level="7.1" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#introduzione-3"><i class="fa fa-check"></i><b>7.1</b> Introduzione</a></li>
<li class="chapter" data-level="7.2" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#lanalisi-dei-dati-gli-ingredienti-fondamentali"><i class="fa fa-check"></i><b>7.2</b> L’analisi dei dati: gli ’ingredienti’ fondamentali</a></li>
<li class="chapter" data-level="7.3" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#modello-della-realta-e-sampling-space"><i class="fa fa-check"></i><b>7.3</b> Modello della realtà e ’sampling space’</a></li>
<li class="chapter" data-level="7.4" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#esempio-1-2"><i class="fa fa-check"></i><b>7.4</b> Esempio 1</a><ul>
<li class="chapter" data-level="7.4.1" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#sampling-distribution"><i class="fa fa-check"></i><b>7.4.1</b> Sampling distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#esempio-2-2"><i class="fa fa-check"></i><b>7.5</b> Esempio 2</a><ul>
<li class="chapter" data-level="7.5.1" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#definire-la-sampling-distribution-per-lesempio-2"><i class="fa fa-check"></i><b>7.5.1</b> Definire la ’sampling distribution’ per l’esempio 2</a></li>
<li class="chapter" data-level="7.5.2" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#le-simulazioni-monte-carlo-con-excel"><i class="fa fa-check"></i><b>7.5.2</b> Le simulazioni Monte Carlo con Excel</a></li>
<li class="chapter" data-level="7.5.3" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#la-distribuzione-delle-medie-campionarie-lerrore-standard"><i class="fa fa-check"></i><b>7.5.3</b> La distribuzione delle medie campionarie: l’errore standard</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#riepilogo-1-caratterizzare-lincertezza-di-un-esperimento"><i class="fa fa-check"></i><b>7.6</b> Riepilogo 1: Caratterizzare l’incertezza di un esperimento</a></li>
<li class="chapter" data-level="7.7" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#gli-intervalli-di-confidenza"><i class="fa fa-check"></i><b>7.7</b> Gli intervalli di confidenza</a></li>
<li class="chapter" data-level="7.8" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#gli-intervalli-di-confidenza-con-excel"><i class="fa fa-check"></i><b>7.8</b> Gli intervalli di confidenza con Excel</a></li>
<li class="chapter" data-level="7.9" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#qual-e-il-senso-dellintervallo-di-confidenza"><i class="fa fa-check"></i><b>7.9</b> Qual è il senso dell’intervallo di confidenza?</a></li>
<li class="chapter" data-level="7.10" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#analisi-statistica-dei-dati-riassunto-del-percorso-logico"><i class="fa fa-check"></i><b>7.10</b> Analisi statistica dei dati: riassunto del percorso logico</a></li>
<li class="chapter" data-level="7.11" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#presentazione-dei-risultati-degli-esperimenti"><i class="fa fa-check"></i><b>7.11</b> Presentazione dei risultati degli esperimenti</a></li>
<li class="chapter" data-level="7.12" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#da-ricordare"><i class="fa fa-check"></i><b>7.12</b> Da ricordare</a></li>
<li class="chapter" data-level="7.13" data-path="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html"><a href="modellizzare-lerrore-sperimentale-introduzione-allinferenza-statistica.html#esercizi"><i class="fa fa-check"></i><b>7.13</b> Esercizi</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html"><i class="fa fa-check"></i><b>8</b> Breve introduzione al test d’ipotesi</a><ul>
<li class="chapter" data-level="8.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#confronto-tra-una-media-osservata-e-una-media-teorica"><i class="fa fa-check"></i><b>8.1</b> Confronto tra una media osservata e una media teorica</a><ul>
<li class="chapter" data-level="8.1.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#esempio-1-3"><i class="fa fa-check"></i><b>8.1.1</b> ESEMPIO 1</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#simulazione-monte-carlo"><i class="fa fa-check"></i><b>8.2</b> Simulazione Monte Carlo</a></li>
<li class="chapter" data-level="8.3" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#soluzione-formale"><i class="fa fa-check"></i><b>8.3</b> Soluzione formale</a></li>
<li class="chapter" data-level="8.4" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#interpretazione-del-p-level"><i class="fa fa-check"></i><b>8.4</b> Interpretazione del P-level</a></li>
<li class="chapter" data-level="8.5" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#confronto-tra-due-medie-il-test-t-di-student"><i class="fa fa-check"></i><b>8.5</b> Confronto tra due medie: il test t di Student</a><ul>
<li class="chapter" data-level="8.5.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#esempio-2-3"><i class="fa fa-check"></i><b>8.5.1</b> ESEMPIO 2</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#approfondimento-tipologie-alternative-di-test-t"><i class="fa fa-check"></i><b>8.6</b> Approfondimento: tipologie alternative di test t</a></li>
<li class="chapter" data-level="8.7" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#confronto-tra-due-proporzioni"><i class="fa fa-check"></i><b>8.7</b> Confronto tra due proporzioni</a><ul>
<li class="chapter" data-level="8.7.1" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#esempio-3-2"><i class="fa fa-check"></i><b>8.7.1</b> ESEMPIO 3</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#conclusioni-1"><i class="fa fa-check"></i><b>8.8</b> Conclusioni</a></li>
<li class="chapter" data-level="8.9" data-path="breve-introduzione-al-test-dipotesi.html"><a href="breve-introduzione-al-test-dipotesi.html#riepilogo"><i class="fa fa-check"></i><b>8.9</b> Riepilogo</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html"><i class="fa fa-check"></i><b>9</b> Modelli matamatici descrittivi: breve introduzione</a><ul>
<li class="chapter" data-level="9.1" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html#che-centra-la-matematica"><i class="fa fa-check"></i><b>9.1</b> Che c’entra la matematica?</a></li>
<li class="chapter" data-level="9.2" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html#mettiamo-alcuni-paletti"><i class="fa fa-check"></i><b>9.2</b> Mettiamo alcuni paletti</a></li>
<li class="chapter" data-level="9.3" data-path="modelli-matamatici-descrittivi-breve-introduzione.html"><a href="modelli-matamatici-descrittivi-breve-introduzione.html#metodo-di-lavoro"><i class="fa fa-check"></i><b>9.3</b> Metodo di lavoro</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html"><i class="fa fa-check"></i><b>10</b> Una variabile indipendente categorica: ANOVA ad una via</a><ul>
<li class="chapter" data-level="10.1" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#la-situazione-sperimentale"><i class="fa fa-check"></i><b>10.1</b> La situazione sperimentale</a></li>
<li class="chapter" data-level="10.2" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#la-verita-vera-la-popolazione"><i class="fa fa-check"></i><b>10.2</b> La verità ‘vera’ (la popolazione)</a></li>
<li class="chapter" data-level="10.3" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#esecuzione-dellesperimento"><i class="fa fa-check"></i><b>10.3</b> Esecuzione dell’esperimento</a></li>
<li class="chapter" data-level="10.4" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#analisi-dei-dati-1"><i class="fa fa-check"></i><b>10.4</b> Analisi dei dati</a><ul>
<li class="chapter" data-level="10.4.1" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#statistiche-descrittive"><i class="fa fa-check"></i><b>10.4.1</b> Statistiche descrittive</a></li>
<li class="chapter" data-level="10.4.2" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#stima-dei-parametri-1"><i class="fa fa-check"></i><b>10.4.2</b> Stima dei parametri</a></li>
<li class="chapter" data-level="10.4.3" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#stima-della-varianza"><i class="fa fa-check"></i><b>10.4.3</b> Stima della varianza</a></li>
<li class="chapter" data-level="10.4.4" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#effetto-del-trattamento"><i class="fa fa-check"></i><b>10.4.4</b> Effetto del trattamento</a></li>
<li class="chapter" data-level="10.4.5" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#test-dipotesi"><i class="fa fa-check"></i><b>10.4.5</b> Test d’ipotesi</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="una-variabile-indipendente-categorica-anova-ad-una-via.html"><a href="una-variabile-indipendente-categorica-anova-ad-una-via.html#per-approfondimenti-2"><i class="fa fa-check"></i><b>10.5</b> Per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><i class="fa fa-check"></i><b>11</b> La verifica delle assunzioni di base: metodi diagnostici</a><ul>
<li class="chapter" data-level="11.1" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#introduzione-4"><i class="fa fa-check"></i><b>11.1</b> Introduzione</a></li>
<li class="chapter" data-level="11.2" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#procedure-diagnostiche"><i class="fa fa-check"></i><b>11.2</b> Procedure diagnostiche</a></li>
<li class="chapter" data-level="11.3" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#analisi-grafica-dei-residui"><i class="fa fa-check"></i><b>11.3</b> Analisi grafica dei residui</a><ul>
<li class="chapter" data-level="11.3.1" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#grafico-dei-residui-contro-i-valori-attesi"><i class="fa fa-check"></i><b>11.3.1</b> Grafico dei residui contro i valori attesi</a></li>
<li class="chapter" data-level="11.3.2" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#qq-plot"><i class="fa fa-check"></i><b>11.3.2</b> QQ-plot</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#altri-strumenti-diagnostici"><i class="fa fa-check"></i><b>11.4</b> Altri strumenti diagnostici</a></li>
<li class="chapter" data-level="11.5" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#risultati-contraddittori"><i class="fa fa-check"></i><b>11.5</b> Risultati contraddittori</a></li>
<li class="chapter" data-level="11.6" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#terapia"><i class="fa fa-check"></i><b>11.6</b> ‘Terapia’</a><ul>
<li class="chapter" data-level="11.6.1" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#correzionerimozione-degli-outliers"><i class="fa fa-check"></i><b>11.6.1</b> Correzione/Rimozione degli outliers</a></li>
<li class="chapter" data-level="11.6.2" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#correzione-del-modello"><i class="fa fa-check"></i><b>11.6.2</b> Correzione del modello</a></li>
<li class="chapter" data-level="11.6.3" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#non-normalita-dei-residui-ed-eterogeneita-delle-varianze"><i class="fa fa-check"></i><b>11.6.3</b> Non-normalità dei residui ed eterogeneità delle varianze</a></li>
<li class="chapter" data-level="11.6.4" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#la-procedura-di-box-e-cox"><i class="fa fa-check"></i><b>11.6.4</b> La procedura di Box e Cox</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html"><a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html#referenze-bibliografiche-per-approfondimenti"><i class="fa fa-check"></i><b>11.7</b> Referenze bibliografiche per approfondimenti</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html"><i class="fa fa-check"></i><b>12</b> Contrasti e confronti multipli con R</a><ul>
<li class="chapter" data-level="12.1" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#introduzione-5"><i class="fa fa-check"></i><b>12.1</b> Introduzione</a></li>
<li class="chapter" data-level="12.2" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#esempio"><i class="fa fa-check"></i><b>12.2</b> Esempio</a></li>
<li class="chapter" data-level="12.3" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#i-contrasti"><i class="fa fa-check"></i><b>12.3</b> I contrasti</a><ul>
<li class="chapter" data-level="12.3.1" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#varianza-del-contrasto-e-intervalli-di-confidenza"><i class="fa fa-check"></i><b>12.3.1</b> Varianza del contrasto e intervalli di confidenza</a></li>
<li class="chapter" data-level="12.3.2" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#significativita-del-contrasto-e-intervalli-di-confidenza"><i class="fa fa-check"></i><b>12.3.2</b> Significatività del contrasto e intervalli di confidenza</a></li>
<li class="chapter" data-level="12.3.3" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#i-contrasti-con-r"><i class="fa fa-check"></i><b>12.3.3</b> I contrasti con R</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#i-confronti-multipli-a-coppie-pairwise-comparisons"><i class="fa fa-check"></i><b>12.4</b> I confronti multipli a coppie (pairwise comparisons)</a></li>
<li class="chapter" data-level="12.5" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#display-a-lettere"><i class="fa fa-check"></i><b>12.5</b> Display a lettere</a></li>
<li class="chapter" data-level="12.6" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#problemi-di-molteplicita-tassi-di-errore-per-confronto-e-per-esperimento"><i class="fa fa-check"></i><b>12.6</b> Problemi di molteplicità: tassi di errore per confronto e per esperimento</a><ul>
<li class="chapter" data-level="12.6.1" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#correzione-per-la-molteplicita"><i class="fa fa-check"></i><b>12.6.1</b> Correzione per la molteplicità</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#intervalli-di-confidenza-simultanei"><i class="fa fa-check"></i><b>12.7</b> Intervalli di confidenza simultanei</a></li>
<li class="chapter" data-level="12.8" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#e-le-classiche-procedure-di-confronto-multiplo"><i class="fa fa-check"></i><b>12.8</b> E le classiche procedure di confronto multiplo?</a></li>
<li class="chapter" data-level="12.9" data-path="contrasti-e-confronti-multipli-con-r.html"><a href="contrasti-e-confronti-multipli-con-r.html#consigli-pratici"><i class="fa fa-check"></i><b>12.9</b> Consigli pratici</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="referenze-bibliografiche.html"><a href="referenze-bibliografiche.html"><i class="fa fa-check"></i><b>13</b> Referenze bibliografiche</a></li>
<li class="chapter" data-level="14" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html"><i class="fa fa-check"></i><b>14</b> La regressione lineare semplice</a><ul>
<li class="chapter" data-level="14.1" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#introduzione-6"><i class="fa fa-check"></i><b>14.1</b> Introduzione</a></li>
<li class="chapter" data-level="14.2" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#esempio-6"><i class="fa fa-check"></i><b>14.2</b> Esempio</a></li>
<li class="chapter" data-level="14.3" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#stima-dei-parametri-2"><i class="fa fa-check"></i><b>14.3</b> Stima dei parametri</a></li>
<li class="chapter" data-level="14.4" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#valutazione-della-bonta-del-modello"><i class="fa fa-check"></i><b>14.4</b> Valutazione della bontà del modello</a><ul>
<li class="chapter" data-level="14.4.1" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#valutazione-grafica"><i class="fa fa-check"></i><b>14.4.1</b> Valutazione grafica</a></li>
<li class="chapter" data-level="14.4.2" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#errori-standard-dei-parametri"><i class="fa fa-check"></i><b>14.4.2</b> Errori standard dei parametri</a></li>
<li class="chapter" data-level="14.4.3" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#test-f-per-la-mancanza-dadattamento"><i class="fa fa-check"></i><b>14.4.3</b> Test F per la mancanza d’adattamento</a></li>
<li class="chapter" data-level="14.4.4" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#test-f-per-la-bonta-di-adattamento-e-coefficiente-di-determinazione"><i class="fa fa-check"></i><b>14.4.4</b> Test F per la bontà di adattamento e coefficiente di determinazione</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#previsioni"><i class="fa fa-check"></i><b>14.5</b> Previsioni</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Metodologia di sperimentazione in agricoltura</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="contrasti-e-confronti-multipli-con-r" class="section level1">
<h1><span class="header-section-number">Capitolo 12</span> Contrasti e confronti multipli con R</h1>
<div id="introduzione-5" class="section level2">
<h2><span class="header-section-number">12.1</span> Introduzione</h2>
<p>L’ANOVA rappresenta frequentemente il primo passo nell’elaborazione statistica dei dati sperimentali. Essa consente di quantificare l’errore sperimentale e ci permette di sapere se l’effetto del trattamento (nel suo complesso) è risultato significativo. Tuttavia, con la sola ANOVA non siamo ancora capaci di definire una graduatoria di merito tra i diversi livelli del trattamento sperimentale. Dopo l’ANOVA è quindi logico chiedersi (in ordine crescente di importanza):</p>
<ol style="list-style-type: decimal">
<li>Il generico trattamento A ha un effetto diverso dal trattamento B?</li>
<li>Il trattamento A è migliore/uguale/peggiore di B?</li>
<li>Quant’è la differenza tra A e B?</li>
</ol>
<p>La prima domanda è abbastanza sciocca, in quanto due trattamenti non sono quasi mai esattamente uguali. Le altre due domande sono invece più rilevanti, specialmente la seconda, in quanto conoscere l’entità della differenza, oltre che la sua significatività, è fondamentale per comprendere anche la sua rilevanza biologica. Infatti una differenza potrebbe essere significativa, ma irrilevante da un punto di vista agronomico o, viceversa, essa potrebbe essere non significativa, ma estremamente rilevante, quindi meritevole di ulteriori approfondimenti scientifici. Per rispondere alle domande precedenti in genere utilizziamo i contrasti e i confronti multipli, che introdurremo con un esempio.</p>
</div>
<div id="esempio" class="section level2">
<h2><span class="header-section-number">12.2</span> Esempio</h2>
<p>Ammettiamo di aver effettuato una prova con un trattamento sperimentali caratterizzato da quattro livelli qualitativi (tesi di concimazione), con i risultati riportati di seguito:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">yield &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">21</span>,<span class="dv">23</span>,<span class="dv">22</span>,<span class="dv">19</span>,<span class="dv">20</span>,<span class="dv">12</span>,<span class="dv">15</span>,<span class="dv">13</span>,<span class="dv">19</span>,<span class="dv">18</span>,<span class="dv">16</span>)
fert &lt;-<span class="st"> </span><span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Minerale&quot;</span>, <span class="st">&quot;Minerale lento&quot;</span>, 
          <span class="st">&quot;Non concimato&quot;</span>, <span class="st">&quot;Organico&quot;</span>), <span class="dt">each=</span><span class="dv">3</span>))
dataset &lt;-<span class="st"> </span><span class="kw">data.frame</span>(yield, fert)
<span class="kw">rm</span>(yield, fert)
dataset</code></pre></div>
<pre><code>##    yield           fert
## 1     20       Minerale
## 2     21       Minerale
## 3     23       Minerale
## 4     22 Minerale lento
## 5     19 Minerale lento
## 6     20 Minerale lento
## 7     12  Non concimato
## 8     15  Non concimato
## 9     13  Non concimato
## 10    19       Organico
## 11    18       Organico
## 12    16       Organico</code></pre>
<p>L’ANOVA può essere eseguita facilmente con R o con un altro software.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(yield <span class="op">~</span><span class="st"> </span>fert, <span class="dt">data=</span>dataset)
<span class="kw">anova</span>(model)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: yield
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## fert       3 115.000  38.333  16.429 0.0008821 ***
## Residuals  8  18.667   2.333                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In questo caso, l’analisi della varianza ed il relativo test di F ci dicono che esiste una differenza significativa tra le medie, ma rimane il problema di classificare le soluzioni concimanti in ordine di efficacia. Per calcolare le medie dei trattamenti utilizziamo la funzione <em>emmeans()</em> del package <em>emmeans</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(emmeans)</code></pre></div>
<pre><code>## NOTE: As of emmeans versions &gt; 1.2.3,
##       The &#39;cld&#39; function will be deprecated in favor of &#39;CLD&#39;.
##       You may use &#39;cld&#39; only if you have package:multcomp attached.</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">medie &lt;-<span class="st"> </span><span class="kw">emmeans</span>(model, <span class="op">~</span>fert)
medie</code></pre></div>
<pre><code>##  fert             emmean        SE df lower.CL upper.CL
##  Minerale       21.33333 0.8819171  8 19.29963 23.36704
##  Minerale lento 20.33333 0.8819171  8 18.29963 22.36704
##  Non concimato  13.33333 0.8819171  8 11.29963 15.36704
##  Organico       17.66667 0.8819171  8 15.63296 19.70037
## 
## Confidence level used: 0.95</code></pre>
<p>Vediamo che l’output di R riporta anche gli errori standard delle medie (SEM) e gli intervalli di confidenza.</p>
</div>
<div id="i-contrasti" class="section level2">
<h2><span class="header-section-number">12.3</span> I contrasti</h2>
<p>Si definisce CONTRASTO una combinazione lineare dei parametri di un modello (ad esempio le medie dei trattamenti), in modo che i coefficienti sommati diano 0. Ad esempio, considerando i parametri del modello precedente, una combinazione lineare del tipo:</p>
<p><span class="math display">\[ C = \frac{1}{3} \cdot 21.33 + \frac{1}{3} \cdot 20.33 - 1 \cdot 13.33 + \frac{1}{3} \cdot 17.67 = 6.446667\]</span></p>
<p>è un contrasto, in quanto i coefficienti sommati 1/3 + 1/3 - 1 + 1/3 = 0. Al contrario una combinazione del tipo:</p>
<p><span class="math display">\[C1 = 1 \cdot 21.33  + 1 \cdot 20.33 - 1 \cdot 13.33 + 1 \cdot 17.67\]</span></p>
<p>non è un contrasto valido, perché la somma dei coefficienti non è zero (1 + 1 - 1 + 1 = -2).</p>
<p>Il primo contrasto C, ha un preciso significato biologico, in quanto stima la differenza tra il non fertilizzato e la media dei fertilizzati e risponde a tutte e tre le domande:</p>
<ol style="list-style-type: decimal">
<li>La fertilizzazione (in media) ha un effetto diverso dal testimone non fertilizzato? Risposta: si, perché la differenza è non nulla</li>
<li>La fertilizzazione in media è migliore/uguale/peggiore del testimone? Risposta: migliore, perché la differenza è positiva.</li>
<li>Quant’è la differenza tra il fertilizzato e il non-fertilizzato? Risposta: è pari a 6.45</li>
</ol>
<p>E’ evidente, tuttavia, che l’errore sperimentale produce incertezza, che sarebbe bene includere nei risultati, sotto forma di intervallo di confidenza. La domanda quindi è: qual è la varianza del contrasto?</p>
<div id="varianza-del-contrasto-e-intervalli-di-confidenza" class="section level3">
<h3><span class="header-section-number">12.3.1</span> Varianza del contrasto e intervalli di confidenza</h3>
<p>Ogni contrasto ha la sua varianza, ottenuta come combinazione lineare di varianze, attraverso il metodo di propagazione degli errori. In generale:</p>
<p><span class="math display">\[var(A x + B y) = A^{2} var(x) + B^2 var(y) + 2 A \times B \,\, covar (x y)\]</span></p>
<p>dove A e B sono i coefficienti del contrasto, x e y sono i parametri del modello. Se i parametri non sono correlati (come in questo caso e, in genere, nell’ANOVA) la covarianza è zero e quindi la varianza della somma/differenza è uguale alla somma delle varianze.</p>
<p>Nel nostro caso, la varianza del contrasto è:</p>
<p><span class="math display">\[var(C) = \left( \frac{1}{3} \cdot 0.882 \right)^2 +  \left( \frac{1}{3} \cdot 0.882 \right)^2 + 0.882^2 +  \left( \frac{1}{3} \cdot 0.882 \right)^2 = 1.037\]</span></p>
<p>mentre la deviazione standard è pari ad 1.0183. Dopo aver calcolato la deviazione standard, possiamo costruire un intervallo di confidenza per il contrasto, utilizzando le formule usuali (quantili della distribuzione di t):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">limSup &lt;-<span class="st"> </span><span class="fl">6.4467</span> <span class="op">+</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">8</span>) <span class="op">*</span><span class="st"> </span><span class="fl">1.018277</span>
limInf &lt;-<span class="st"> </span><span class="fl">6.4467</span> <span class="op">-</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">8</span>) <span class="op">*</span><span class="st"> </span><span class="fl">1.018277</span>
limInf; limSup</code></pre></div>
<pre><code>## [1] 4.098549</code></pre>
<pre><code>## [1] 8.794851</code></pre>
<p>Con questo abbiamo risposto a tutte e tre le nostre domande di ricerca:</p>
<ol style="list-style-type: decimal">
<li>Fertilizzare non produce lo stesso effetto che non fertilizzare;</li>
<li>Fertilizzare permette di produrre di più che non fertilizzare.</li>
<li>La differenza è pari a 6.44 q/ha e, ripetendo questo esperimento, nel 95% dei casi otterremo differenze variabili entro l’intervallo tra 4.1 e 8.8 q/ha.</li>
</ol>
</div>
<div id="significativita-del-contrasto-e-intervalli-di-confidenza" class="section level3">
<h3><span class="header-section-number">12.3.2</span> Significatività del contrasto e intervalli di confidenza</h3>
<p>E’ importante notare che l’intervallo di confidenza esposto in precedenza non contiene lo zero e quindi la differenza tra i due trattamenti in studio è significativa (significativamente diversa da 0). Tuttavia potremmo essere intenzionati a testare questa differenza in modo formale, a prescindere dal calcolo dell’intervallo di confidenza. Secondo Tukey (1991), questo tipo di test è sciocco (‘foolish’) almeno per due motivi:</p>
<ol style="list-style-type: decimal">
<li>la domanda non è realistica: due trattamenti diversi non possono che dare risultati diversi, magari in modo impercettibile, ma pur sempre diversi;</li>
<li>l’eventuale rifiuto dell’ipotesi nulla non ci da nessuna informazione sulla rilevanza biologica della differenza, che è indipendente dalla sua significatività.</li>
</ol>
<p>Ferma restando l’importanza dell’intervallo di confidenza, quale misura della <em>effect size</em>, il test d’ipotesi è pratica usuale e quindi la tratteremo nel dovuto dettaglio. Dovrebbe essere noto che il rapporto tra una stima ed il suo errore standard ha una distribuzione di t di Student, con un numero di gradi di libertà pari all’errore. Di conseguenza possiamo saggiare l’ipotesi nulla che il contrasto è uguale a 0 calcolando la probabilità di trovare un valore di t pari o superiore (in valore assoluto) a quello da noi ottenuto. Nell’esempio sottostante abbiamo moltiplicato la probabilità trovata per 2, dato che si tratta di un test a due code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">t &lt;-<span class="st"> </span><span class="fl">6.4467</span> <span class="op">/</span><span class="st"> </span><span class="fl">1.018277</span>
<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">pt</span>(t, <span class="dv">8</span>, <span class="dt">lower.tail =</span> F)</code></pre></div>
<pre><code>## [1] 0.0002251554</code></pre>
</div>
<div id="i-contrasti-con-r" class="section level3">
<h3><span class="header-section-number">12.3.3</span> I contrasti con R</h3>
<p>Nel caso in esempio, si potrebbero pianificare tre contrasti (incluso quello già discusso):</p>
<ol style="list-style-type: decimal">
<li>non concimato vs concimato (in media)</li>
<li>concime organico vs. concimi minerali (in media)</li>
<li>minerale tradizionale vs. lento rilascio.</li>
</ol>
<p>Eseguire questi contrasti con R è abbastanza semplice, utilizzando il package <em>emmeans</em>. La procedura di lavoro è la seguente:</p>
<ol style="list-style-type: decimal">
<li>adattare il modello e stimarne i parametri (funzione lm(), utilizzata più sopra)</li>
<li>costruire un vettore per ogni contrasto, contenente i relativi coefficienti, tenendo presente l’ordine delle medie nell’oggetto ‘medie’ (m1, m2, m3; vedi più sotto)</li>
<li>Impiegare la funzione <em>contrast</em>, passandole come argomento l’oggetto ‘medie’ ottenuto con la funzione <em>emmeans</em> (vedi sopra) ed una lista contenente i tre vettori dei coefficienti (m1, m2, m3), ai quali si può assegnare un nome, ad esempio, C1, C2 e C3.</li>
<li>Con la funzione <em>confint</em> possiamo ottenere gli intervalli di confidenza, invece che le significanze.</li>
</ol>

<pre><code>m1 &lt;- c(1/3, 1/3,  -1, 1/3)
m2 &lt;- c(0.5, 0.5, 0, -1)
m3 &lt;- c(1, -1, 0, 0)
contrast(medie, method=list(C1=m1, C2=m2, C3=m3), 
           adjust=&quot;none&quot;)
confint(contrast(medie, method=list(C1=m1, C2=m2, C3=m3), 
           adjust=&quot;none&quot;))</code></pre>

<p>Il test mostra che la concimazione ha, in media, un effetto significativo, che il concime organico differisce significativamente dai minerali (in media) e che il concime a lento rilascio non è significativamente diverso da quello normale.</p>
</div>
</div>
<div id="i-confronti-multipli-a-coppie-pairwise-comparisons" class="section level2">
<h2><span class="header-section-number">12.4</span> I confronti multipli a coppie (pairwise comparisons)</h2>
<p>Non sempre le prove sperimentali consentono di saggiare pochi contrasti pre-stabiliti, ma spesso è necessario confrontare tutte le possibili coppie di trattamenti (<em>pairwise comparisons</em>). In questo caso dovremmo definire un contrasto per ogni coppia di medie, anche se l’impiego del package <em>emmeans</em> agevola, non di poco, il lavoro.</p>
<p>In particolare, possiamo immaginare due situazioni di riferimento: tutti contro tutti (confronti tipo “Tukey”) e tutti verso uno (confronti tipo “Dunnett”).</p>
<p>Nell’esempio sottostante mostriamo un confronto tipo Tukey (tutti contro tutti), eseguito utilizzando la funzione ‘contrast’ (come sopra), passando il valore ‘pairwise’ all’argomento ‘method’.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Confronti multipli a coppie</span>
<span class="kw">contrast</span>(medie, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>, <span class="dt">method=</span><span class="st">&quot;pairwise&quot;</span>)</code></pre></div>
<pre><code>##  contrast                        estimate       SE df t.ratio p.value
##  Minerale - Minerale lento       1.000000 1.247219  8   0.802  0.4458
##  Minerale - Non concimato        8.000000 1.247219  8   6.414  0.0002
##  Minerale - Organico             3.666667 1.247219  8   2.940  0.0187
##  Minerale lento - Non concimato  7.000000 1.247219  8   5.612  0.0005
##  Minerale lento - Organico       2.666667 1.247219  8   2.138  0.0650
##  Non concimato - Organico       -4.333333 1.247219  8  -3.474  0.0084</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">contrast</span>(medie, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>, <span class="dt">method=</span><span class="st">&quot;pairwise&quot;</span>))</code></pre></div>
<pre><code>##  contrast                        estimate       SE df   lower.CL  upper.CL
##  Minerale - Minerale lento       1.000000 1.247219  8 -1.8760925  3.876092
##  Minerale - Non concimato        8.000000 1.247219  8  5.1239075 10.876092
##  Minerale - Organico             3.666667 1.247219  8  0.7905742  6.542759
##  Minerale lento - Non concimato  7.000000 1.247219  8  4.1239075  9.876092
##  Minerale lento - Organico       2.666667 1.247219  8 -0.2094258  5.542759
##  Non concimato - Organico       -4.333333 1.247219  8 -7.2094258 -1.457241
## 
## Confidence level used: 0.95</code></pre>

<p>Per i confronti del tipo ‘tutti verso uno’ è possibile utilizzare la stessa funzione, assegnando però il valore ‘dunnett’ (invece che ‘pairwise’) all’ argomento ‘method’.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">contrast</span>(medie, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>, <span class="dt">method=</span><span class="st">&quot;dunnett&quot;</span>)</code></pre></div>
<pre><code>##  contrast                   estimate       SE df t.ratio p.value
##  Minerale lento - Minerale -1.000000 1.247219  8  -0.802  0.4458
##  Non concimato - Minerale  -8.000000 1.247219  8  -6.414  0.0002
##  Organico - Minerale       -3.666667 1.247219  8  -2.940  0.0187</code></pre>

<p>Purtroppo vediamo che R confronta tutte le tesi con ‘Minerale’, che non è quello che volevamo. Bisogna ricordare infatti che il livello di riferimento è, per default, il primo in ordine alfabetico e, se vogliamo utiizzare ‘Non concimato’ come riferimento, dobbiamo dobbiamo ricodificare il vettore ‘fert’ e, successivamente, ripetere l’analisi.</p>

<pre><code>#Confronti tutti vs uno (il primo in ordine alfabetico)
dataset$fert

#Vediamo che il riferimento è &quot;Minerale&quot;. Lo cambiamo in &quot;Non concimato&quot;
dataset$fert &lt;- relevel(dataset$fert, ref=&quot;Non concimato&quot;)
dataset$fert

#A questo punto dobbiamo ripetere le analisi
model &lt;- lm(yield ~ fert, data=dataset)
medie &lt;- emmeans(model, ~fert)
contrast(medie, adjust=&quot;none&quot;, method=&quot;dunnett&quot;)
confint(contrast(medie, adjust=&quot;none&quot;, method=&quot;dunnett&quot;))</code></pre>

</div>
<div id="display-a-lettere" class="section level2">
<h2><span class="header-section-number">12.5</span> Display a lettere</h2>
<p>I risultati di un confronto multiplo a coppie (pairwise) possono essere presentati anche con un display a lettere, nel quale le medie seguite da lettere diverse sono significativamente diverse per un livello di probabilità di errore minore di quello dato.</p>
<p>Realizzare un display a letter manualmente è piuttosto facile, utilizzando la seguente procedura:</p>
<ol style="list-style-type: decimal">
<li>ordinare le medie in senso crescente/decrescente</li>
<li>partire dalla prima media e aggiungere la lettera A a tutte quelle che non sono significativamente diverse</li>
<li>passare alla seconda media e aggiungere la lettera B a tutte quelle che non sono significativamente diverse</li>
<li>procedere analogamente con tutte le medie successive</li>
</ol>
<p>Con R si può sfruttare il package emmeans, con la sintassi sottostante.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Per aggiungere le lettere di significanza</span>
<span class="kw">cld</span>(medie, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>, <span class="dt">Letters=</span>LETTERS)</code></pre></div>
<pre><code>##  fert             emmean        SE df lower.CL upper.CL .group
##  Non concimato  13.33333 0.8819171  8 11.29963 15.36704  A    
##  Organico       17.66667 0.8819171  8 15.63296 19.70037   B   
##  Minerale lento 20.33333 0.8819171  8 18.29963 22.36704   BC  
##  Minerale       21.33333 0.8819171  8 19.29963 23.36704    C  
## 
## Confidence level used: 0.95 
## significance level used: alpha = 0.05</code></pre>
</div>
<div id="problemi-di-molteplicita-tassi-di-errore-per-confronto-e-per-esperimento" class="section level2">
<h2><span class="header-section-number">12.6</span> Problemi di molteplicità: tassi di errore per confronto e per esperimento</h2>
<p>Operando nel modo anzidetto, ogni contrasto/confronto ha una probabilità di errore del 5%. Se i contrasti/confronti sono più di uno (family of <em>n</em> contrasts), la probabilità di sbagliarne almeno uno (<em>maximum experimentwise error rate</em>) è data da:</p>
<p><span class="math display">\[\alpha_E = 1 - (1 - \alpha_C)^n\]</span></p>
<p>Bisogna premettere che l’anzidetta formula vale quando i contrasti sono totalmente indipendenti tra loro, cosa che quasi mai avviene, dato che, anche in un semplice modello ANOVA, i contrasti condividono la stessa varianza d’errore e sono quindi più o meno correlati tra di loro. Con contrasti non indipendenti la formula anzidetta fornisce una sovrastima di <span class="math inline">\(\alpha_E\)</span> (per questo si parla di <em>maximum experimentwise error rate</em>).</p>
<p>Il numero di confronti a coppie per esperimento può essere anche molto elevato: se ho <em>k</em> medie il numero dei confronti possibili è pari a <span class="math inline">\(k \cdot (k-1)/2\)</span>. Di conseguenza, la probabilità di errore per esperimento (<span class="math inline">\(\alpha_E\)</span>) può essere molto più alta del valore <span class="math inline">\(\alpha_C\)</span> prefissato per confronto.</p>
<p>Ad esempio, se ho 15 medie, ho <span class="math inline">\((15 \cdot 14)/2 = 105\)</span> confronti possibili. Se uso <span class="math inline">\(\alpha_C = 0.05\)</span> per ogni confronto, la probabilità di sbagliarne almeno uno è pari (in caso di confronti indipendenti) a <span class="math inline">\(1 - (1 - 0.05)^105 = 0.995\)</span>. Sostanzialmente, vi è pressoché la certezza che in questo esperimento qualcosa è sbagliato!</p>
<div id="correzione-per-la-molteplicita" class="section level3">
<h3><span class="header-section-number">12.6.1</span> Correzione per la molteplicità</h3>
<p>Quando si elaborano i dati di un esperimento nel quale è necessario fare molti contrasti, o confronti, o, più in generale, molti test d’ipotesi simultanei, si potrebbe voler esprimere un giudizio globale (simultaneo) sull’intera famiglia di contrasti/confronti, minimizzando la possibilità che anche solo uno o pochi di essi siano sbagliati. Vediamo alcuni esempi di quando questo potrebbe capitare.</p>
<ol style="list-style-type: decimal">
<li>Non vogliamo correre rischi di escludere erroneamente alcun trattamento dal lotto dei migliori. Infatti, poniamo di voler trovare i migliori di <em>k</em> trattamenti, intendendo con ciò quelli che non sono significativamente inferiori a nessun altro. In questa situazione, facendo ogni confronto con il 5% di probabilità di errore, la probabilità di escludere erroneamente anche solo un trattamento dal lotto dei migliori è molto più alta di quella prefissata, perché basta sbagliare anche uno solo dei <em>k - 1</em> confronti con il migliore.</li>
<li>Abbiamo utilizzato un display a lettere e intendiamo affermare che ‘i trattamenti seguiti da lettere diverse sono significativamente diversi’. In questo caso, stiamo tirando una conclusione basata sull’intera famiglia di confronti e non possiamo lecitamente riportare la probabilità di errore di un singolo confronto.</li>
</ol>
<p>In tutte le condizioni analoghe a quelle più sopra accennate si pone il problema di aggiustare il p-level) di ogni contrasto in modo da rispettare un certo livello prestabilito di errore per esperimento (e non per confronto).</p>
<p>Per aggiustare il p-level e correggere quindi per la molteplicità abbiamo parecchie possibilità. La prima è quella di utilizzare la formula precedente (metodo di Sidak). Ad esempio, nel caso del terzo dei sei confronti a coppie illustrati in precedenza (Minerale - Organico = 3.667; p = 0.018713), la correzione del p-level per la molteplicità è:</p>
<p><span class="math display">\[ \alpha_E = 1 - (1 - 0.018713)^6 = 0.1051546 \]</span></p>
<p>Con R possiamo utilizzare il seguente comando:</p>

<pre><code>contrast(medie, method=&quot;pairwise&quot;, adjust=&quot;sidak&quot;)</code></pre>

<p>Vediamo che alcuni confronti che prima erano significativi, ora non lo sono più.</p>
<p>Un’alternativa più nota (e semplice) è quella di utilizzare la diseguaglianza di Bonferroni:</p>
<p><span class="math display">\[\alpha_E = \alpha_C \cdot k\]</span></p>
<p>Quest’ultima è un po’ più conservativa della precedente, nel senso che fornisce un p-level aggiustato leggermente più alto dell’altra.</p>
<p><span class="math display">\[\alpha_E = 0.018713 \cdot 6 = 0.112278 \]</span></p>
<p>Con R:</p>

<pre><code>contrast(medie, method=&quot;pairwise&quot;, adjust=&quot;bonferroni&quot;)</code></pre>

<p>Sono possibili altre procedure di aggiustamento del p-level (metodi di Holm, Hochberg, Hommel), ma nessuna di queste tiene conto della correlazione eventualmente esistente tra i contrasti e tutte quindi sono da definirsi più o meno ‘conservative’.</p>
<p>Invece che aggiustare il p-level con uno dei metodi indicati più sopra è possibile considerare che, nel caso di contrasti e/o confronti, ogni singolo test d’ipotesi consiste in un rapporto tra una stima e il suo errore standard e segue la distribuzione di t univariata (vedi sopra). Di conseguenza, una famiglia di confronti/contrasti segue la distribuzione di t multivariato, con una matrice di correlazione che deducibile dal contesto, come indicato da Bretz et al., (2011), pag. 73. In altre parole, noto che sia il valore di t di ogni contrasto/confronto, posso desumere la relativa probabilità dalla distribuzione di t multivariata, invece che da quella univariata. Ovviamente il calcolo manuale è complesso e dovremo affidarci al software, come esemplificato più sotto. Questo tipo di correzione è quella di default in R, come si può desumere dal fatto che in tutti i frammenti di codice dati finora abbiamo dovuto specificare esplicitamente ‘correct=“none”’.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Confronti multipli a coppie, basati sul t multivariato</span>
<span class="kw">contrast</span>(medie, <span class="dt">method=</span><span class="st">&quot;pairwise&quot;</span>)</code></pre></div>
<pre><code>##  contrast                        estimate       SE df t.ratio p.value
##  Minerale - Minerale lento       1.000000 1.247219  8   0.802  0.8518
##  Minerale - Non concimato        8.000000 1.247219  8   6.414  0.0009
##  Minerale - Organico             3.666667 1.247219  8   2.940  0.0724
##  Minerale lento - Non concimato  7.000000 1.247219  8   5.612  0.0022
##  Minerale lento - Organico       2.666667 1.247219  8   2.138  0.2203
##  Non concimato - Organico       -4.333333 1.247219  8  -3.474  0.0342
## 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">contrast</span>(medie, <span class="dt">method=</span><span class="st">&quot;dunnett&quot;</span>)</code></pre></div>
<pre><code>##  contrast                   estimate       SE df t.ratio p.value
##  Minerale lento - Minerale -1.000000 1.247219  8  -0.802  0.7516
##  Non concimato - Minerale  -8.000000 1.247219  8  -6.414  0.0006
##  Organico - Minerale       -3.666667 1.247219  8  -2.940  0.0479
## 
## P value adjustment: dunnettx method for 3 tests</code></pre>

<p>Possiamo notare che i p-levels sono leggermente più bassi di quelli ottenuti con Bonferroni, che conferma quindi di essere una procedura molto conservativa, mentre l’impiego del t multivariato consente di rispettare esattamente il tasso di errore ‘per esperimento’familywise’.</p>
</div>
</div>
<div id="intervalli-di-confidenza-simultanei" class="section level2">
<h2><span class="header-section-number">12.7</span> Intervalli di confidenza simultanei</h2>
<p>Nell’ottica esposta in precedenza, che prevede l’uso preferenziale degli intervalli di confidenza al posto del test d’ipotesi, è molto più interessante creare degli intervalli di confidenza <em>familywise</em>. Nel caso più semplice dei confronti a coppie nell’ANOVA per disegni ortogonali (bilanciati), si può utilizzare al posto del valore <span class="math inline">\(t_{\alpha/2, \nu}\)</span> il valore ottenuto dalla distribuzione t multivariata, che, per nostra fortuna, si può facilmente desumere dalle tabelle dello ‘Studentised Range’, in funzione del numero di trattamenti in prova. Ad esempio, si può consultare <a href="http://davidmlane.com/hyperstat/sr_table.html">questo link</a>, da dove desumiamo che lo Studentised Range per 4 medie e 8 gradi di libertà dell’errore è 4.529. Di conseguenza, se consideriamo ancora il terzo dei sei confronti a coppie illustrati in precedenza (Organico vs Minerale; SE = 1.247), l’intervallo di confidenza non corretto sarebbe:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">limSup &lt;-<span class="st"> </span><span class="fl">3.667</span> <span class="op">+</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">8</span>) <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span>
limInf &lt;-<span class="st"> </span><span class="fl">3.667</span> <span class="op">-</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dv">8</span>) <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span>
limInf; limSup</code></pre></div>
<pre><code>## [1] 0.7914128</code></pre>
<pre><code>## [1] 6.542587</code></pre>
<p>Mentre l’intervallo di confidenza corretto sarebbe :</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">limSup &lt;-<span class="st"> </span><span class="fl">3.667</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span>) <span class="op">*</span><span class="st"> </span><span class="fl">4.529</span> <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span>
limInf &lt;-<span class="st"> </span><span class="fl">3.667</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span>) <span class="op">*</span><span class="st"> </span><span class="fl">4.529</span> <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span>
limSup; limInf</code></pre></div>
<pre><code>## [1] 7.660501</code></pre>
<pre><code>## [1] -0.3265008</code></pre>
<p>Possiamo osservare che lo Studentised Range viene diviso per <span class="math inline">\(\sqrt{2}\)</span>. Con R possiamo ottenere lo stesso risultato:</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">contrast</span>(medie, <span class="dt">method=</span><span class="st">&quot;pairwise&quot;</span>))</code></pre></div>
<pre><code>##  contrast                        estimate       SE df  lower.CL   upper.CL
##  Minerale - Minerale lento       1.000000 1.247219  8 -2.994035  4.9940347
##  Minerale - Non concimato        8.000000 1.247219  8  4.005965 11.9940347
##  Minerale - Organico             3.666667 1.247219  8 -0.327368  7.6607013
##  Minerale lento - Non concimato  7.000000 1.247219  8  3.005965 10.9940347
##  Minerale lento - Organico       2.666667 1.247219  8 -1.327368  6.6607013
##  Non concimato - Organico       -4.333333 1.247219  8 -8.327368 -0.3392987
## 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 4 estimates</code></pre>

<p>Nel caso dei confronti tutti contro uno (tipo Dunnet), l’intervallo di confidenza può essere analogamente calcolato con la distribuzione t-multivariato. Le tabelle da consultare in questo caso sono diverse, perché, a parità di numero di medie, il numero di confronti è inferiore. Segnaliamo <a href="http://www.stat.ufl.edu/~winner/tables/dunnett-2side.pdf">questo link</a>. A titolo di esempio, il valore tabulato per 4 medie e 8 gradi di libertà è pari a 2.8826 e, di conseguenza, l’intervallo di confidenza per l’ultimo dei tre confronti tutti verso uno è pari a:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">limSup &lt;-<span class="st"> </span><span class="fl">4.333333</span> <span class="op">+</span><span class="st"> </span><span class="fl">2.88</span> <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span>
limInf &lt;-<span class="st"> </span><span class="fl">4.333333</span> <span class="op">-</span><span class="st"> </span><span class="fl">2.88</span> <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span>
limSup; limInf</code></pre></div>
<pre><code>## [1] 7.924693</code></pre>
<pre><code>## [1] 0.741973</code></pre>
<p>che è più o meno uguale a quello ottenuto con R (anche se vi sono alcune differenza, che lasciano pensare a qualche piccolo bug nel programma).</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(<span class="kw">contrast</span>(medie, <span class="dt">method=</span><span class="st">&quot;dunnett&quot;</span>))</code></pre></div>
<pre><code>##  contrast                   estimate       SE df   lower.CL    upper.CL
##  Minerale lento - Minerale -1.000000 1.247219  8  -4.630378  2.63037782
##  Non concimato - Minerale  -8.000000 1.247219  8 -11.630378 -4.36962218
##  Organico - Minerale       -3.666667 1.247219  8  -7.297044 -0.03628885
## 
## Confidence level used: 0.95 
## Conf-level adjustment: dunnettx method for 3 estimates</code></pre>

<p>Sono possibili altre procedure di correzione più avanzate (Shaffer, Westfall), che tuttavia sono valide in presenza di alcune assunzioni aggiuntive e debbono quindi essere valutate con attenzione.</p>
</div>
<div id="e-le-classiche-procedure-di-confronto-multiplo" class="section level2">
<h2><span class="header-section-number">12.8</span> E le classiche procedure di confronto multiplo?</h2>
<p>Il confronto multiplo tradizionale è basato sul calcolo di una differenza critica minima, da utilizzare come base per il confronto tra due medie. In pratica, due medie sono considerate significativamente diverse quando la loro differenza supera la differenza critica. In questo modo possiamo solo sapere su un confronto è significativo oppure no, per P &lt; 0.05 o per qualche altro livello <span class="math inline">\(\alpha\)</span> prefissato, venendo così a mancare ogni altra informazione sull’<em>effect size</em> e sulla vera probabilità d’errore di I specie. Per questi motivi, i confronti basati sulla sola differenza critica sono considerati sub-ottimali, e dovrebbero essere evitati, anche se sono tuttora molto diffusi.</p>
<p>La differenza critica più utilizzata (almeno nel passato) è la Minima Differenza significativa, che è basata sul tasso di errore per confronto. Per l’esperimento in esempio, la MDS è pari a:</p>
<p><span class="math display">\[ MDS = 2.306 \times 1.247 = 2.875582\]</span></p>
<p>dove 2.306 è il valore critico della distribuzione di t, per una probabilità del 5% (a due code) e 8 gradi di libertà.</p>
<p>Un’altra differenza critica molto utilizzata è la <em>Honest Significant Difference</em> di Tukey (per i confronti a coppie), che utilizza, invece della distribuzione t univariata, la distribuzione t multivariata. Dovendola calcolare a mano, possiamo utilizzare lo Studentised range, ancora diviso per <span class="math inline">\(\sqrt{2}\)</span>:</p>
<p><span class="math display">\[ HSD = 4.529 \times \frac{1}{\sqrt{2}} \times 1.247 = 3.9935 \]</span></p>
<p>La HSD garantisce un tasso di errore <em>experimentwise</em> e può essere utilizzata per ottenere intervalli di confidenza simultanei (vedi sopra).</p>
<p>Un’altra procedura molto importante è quella di Dunnett, che consente di confrontare tutte le medie con un testimone (o con il migliore/peggiore dei trattamenti). Per dati bilanciati, la differenza critica in questo caso è (si vedano le tabelle indicate in precedenza per gli intervalli di confidenza):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">2.88</span> <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span></code></pre></div>
<pre><code>## [1] 3.59136</code></pre>
<p>ed assicura il tasso d’errore prefissato per esperimento, anche se la differenza critica è più piccola della HSD, perché viene effettuato un minor numero di confronti.</p>
<p>Se volessimo confrontare tutte le medie con la media più alta (o più bassa) potremmo utilizzare il test di Dunnett ad una coda, che utilizza appunto un valore critico tabulato leggermente inferiore (si veda a: <a href="http://www.watpon.com/table/dunnetttest.pdf" class="uri">http://www.watpon.com/table/dunnetttest.pdf</a>, facendo però attenzione alla lettura della tabella, che, a differenza della precedente, richiede il numero di medie da confrontare escluso il controllo).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">2.42</span> <span class="op">*</span><span class="st"> </span><span class="fl">1.247</span></code></pre></div>
<pre><code>## [1] 3.01774</code></pre>
<p>Esistono almeno altre tre procedure classiche di confronto multiplo, che elenchiamo di seguito:</p>
<ol style="list-style-type: decimal">
<li>Test di Duncan;</li>
<li>Test di Newman-Keuls;</li>
<li>Test di confronto multiplo di Tukey.</li>
</ol>
<p>In genere queste procedure sono sconsigliabili, per i seguenti motivi:</p>
<ol style="list-style-type: decimal">
<li>sono basate su differenze critiche multiple (crescenti al crescere della distanza dei trattamenti in graduatoria) e quindi non consentono la definizione di un’intervallo di confidenza. Di conseguenza, tra le domande ‘biologiche’ alle quali si cerca la risposta con i confronti multipli (si veda all’inizio) sono in grado di rispondere solo alla prima e non alla seconda e alla terza (non consentono il calcolo di un intervallo di confidenza).</li>
<li>Non danno protezione ne’ per un tasso di errore per confronto ne’ per esperimento, ma rimangono a metà strada, in modo imprecisato (quindi il p level non è effettivamente noto, né a livello di singolo confronto né a livello di esperimento).</li>
</ol>
</div>
<div id="consigli-pratici" class="section level2">
<h2><span class="header-section-number">12.9</span> Consigli pratici</h2>
<p>La cosa fondamentale è muoversi in coerenza con le finalità dell’esperimento. Si consiglia di:</p>
<ol style="list-style-type: decimal">
<li>Quando è possibile, pianificare gli esperimenti in modo da ottenere le risposte cercate con pochi contrasti di interesse. In questo modo il problema della molteplicità è minimizzato.</li>
<li>Non usare mai contrasti con serie di dati quantitative. In questo caso la regressione è l’approccio corretto. In generale, utilizzare i contrasti solo se sono coerenti con la logica dell’esperimento.</li>
<li>Pianificare esattamente il numero di contrasti necessari ed eseguirli, fornendo il valore del contrasto e il suo errore standard.</li>
<li>Decidere è necessario aggiustare il p-level (e gli intervalli di confidenza) per la molteplicità (tasso di errore <em>comparisonwise</em> o <em>experimentwise</em>).</li>
<li>Se si decide di aggiustare il p-level, considerare che le procedure di Bonferroni o Sidak possono essere eccessivamente protette. Preferire quindi le procedure di aggiustamento basate sulla distribuzione t multivariata, il che, a livello di confronto multiplo con dati bilanciati, è equivalente ad utilizzate la Tukey HSD o il test di Dunnett.</li>
<li>Evitare le procedure di Duncan e Newmann-Keuls: non danno il livello di protezione cercato e, inoltre, non sono basate su una differenza critica costante (quindi sono difficili da discutere).</li>
</ol>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="la-verifica-delle-assunzioni-di-base-metodi-diagnostici.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referenze-bibliografiche.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["_main.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
