<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitolo 3 Richiami di statistica descrittiva | Metodologia sperimentale per le scienze agrarie</title>
  <meta name="description" content="Capitolo 3 Richiami di statistica descrittiva | Metodologia sperimentale per le scienze agrarie con applicazioni in R" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitolo 3 Richiami di statistica descrittiva | Metodologia sperimentale per le scienze agrarie" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Capitolo 3 Richiami di statistica descrittiva | Metodologia sperimentale per le scienze agrarie con applicazioni in R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitolo 3 Richiami di statistica descrittiva | Metodologia sperimentale per le scienze agrarie" />
  
  <meta name="twitter:description" content="Capitolo 3 Richiami di statistica descrittiva | Metodologia sperimentale per le scienze agrarie con applicazioni in R" />
  

<meta name="author" content="Andrea Onofri e Dario Sacco" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="progettare-un-esperimento.html"/>
<link rel="next" href="modelli-statistici-ed-analisi-dei-dati.html"/>
<script src="book_assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="book_assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="book_assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="book_assets/anchor-sections-1.1.0/anchor-sections.js"></script>
<!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131792052-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-131792052-1');
  </script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">Metodologia sperimentale</a></strong></li> 

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Premessa</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#obiettivi"><i class="fa fa-check"></i>Obiettivi</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#organizzazione"><i class="fa fa-check"></i>Organizzazione</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-statistico"><i class="fa fa-check"></i>Software statistico</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#gli-autori"><i class="fa fa-check"></i>Gli autori</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ringraziamenti-e-scuse"><i class="fa fa-check"></i>Ringraziamenti e scuse</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html"><i class="fa fa-check"></i><b>1</b> Scienza e pseudo-scienza</a>
<ul>
<li class="chapter" data-level="1.1" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#scienza-dati"><i class="fa fa-check"></i><b>1.1</b> Scienza = dati</a></li>
<li class="chapter" data-level="1.2" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#dati-buoni-e-cattivi"><i class="fa fa-check"></i><b>1.2</b> Dati ‘buoni’ e ‘cattivi’</a></li>
<li class="chapter" data-level="1.3" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#dati-buoni-e-metodi-buoni"><i class="fa fa-check"></i><b>1.3</b> Dati ‘buoni’ e metodi ‘buoni’</a></li>
<li class="chapter" data-level="1.4" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#il-principio-di-falsificazione"><i class="fa fa-check"></i><b>1.4</b> Il principio di falsificazione</a></li>
<li class="chapter" data-level="1.5" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#falsificare-un-risultato"><i class="fa fa-check"></i><b>1.5</b> Falsificare un risultato</a></li>
<li class="chapter" data-level="1.6" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#elementi-fondamentali-del-disegno-sperimentale"><i class="fa fa-check"></i><b>1.6</b> Elementi fondamentali del disegno sperimentale</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#controllo-degli-errori"><i class="fa fa-check"></i><b>1.6.1</b> Controllo degli errori</a></li>
<li class="chapter" data-level="1.6.2" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#replicazione"><i class="fa fa-check"></i><b>1.6.2</b> Replicazione</a></li>
<li class="chapter" data-level="1.6.3" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#randomizzazione"><i class="fa fa-check"></i><b>1.6.3</b> Randomizzazione</a></li>
<li class="chapter" data-level="1.6.4" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#esperimenti-invalidi"><i class="fa fa-check"></i><b>1.6.4</b> Esperimenti invalidi</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#chi-valuta-se-un-esperimento-è-attendibile"><i class="fa fa-check"></i><b>1.7</b> Chi valuta se un esperimento è attendibile?</a></li>
<li class="chapter" data-level="1.8" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#conclusioni"><i class="fa fa-check"></i><b>1.8</b> Conclusioni</a></li>
<li class="chapter" data-level="1.9" data-path="scienza-e-pseudo-scienza.html"><a href="scienza-e-pseudo-scienza.html#altre-letture"><i class="fa fa-check"></i><b>1.9</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html"><i class="fa fa-check"></i><b>2</b> Progettare un esperimento</a>
<ul>
<li class="chapter" data-level="2.1" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#gli-elementi-della-ricerca"><i class="fa fa-check"></i><b>2.1</b> Gli elementi della ricerca</a></li>
<li class="chapter" data-level="2.2" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#ipotesi-scientifica-rightarrow-obiettivo-dellesperimento"><i class="fa fa-check"></i><b>2.2</b> Ipotesi scientifica <span class="math inline">\(\rightarrow\)</span> obiettivo dell’esperimento</a></li>
<li class="chapter" data-level="2.3" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#identificazione-dei-fattori-sperimentali"><i class="fa fa-check"></i><b>2.3</b> Identificazione dei fattori sperimentali</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#esperimenti-multi-fattoriali"><i class="fa fa-check"></i><b>2.3.1</b> Esperimenti (multi-)fattoriali</a></li>
<li class="chapter" data-level="2.3.2" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#controllo-o-testimone"><i class="fa fa-check"></i><b>2.3.2</b> Controllo o testimone</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#le-unità-sperimentali"><i class="fa fa-check"></i><b>2.4</b> Le unità sperimentali</a></li>
<li class="chapter" data-level="2.5" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#allocazione-dei-trattamenti"><i class="fa fa-check"></i><b>2.5</b> Allocazione dei trattamenti</a></li>
<li class="chapter" data-level="2.6" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#le-variabili-sperimentali"><i class="fa fa-check"></i><b>2.6</b> Le variabili sperimentali</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#variabili-nominali-categoriche"><i class="fa fa-check"></i><b>2.6.1</b> Variabili nominali (categoriche)</a></li>
<li class="chapter" data-level="2.6.2" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#variabili-ordinali"><i class="fa fa-check"></i><b>2.6.2</b> Variabili ordinali</a></li>
<li class="chapter" data-level="2.6.3" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#variabili-quantitative-discrete"><i class="fa fa-check"></i><b>2.6.3</b> Variabili quantitative discrete</a></li>
<li class="chapter" data-level="2.6.4" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#variabili-quantitative-continue"><i class="fa fa-check"></i><b>2.6.4</b> Variabili quantitative continue</a></li>
<li class="chapter" data-level="2.6.5" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#rilievi-visivi-e-sensoriali"><i class="fa fa-check"></i><b>2.6.5</b> Rilievi visivi e sensoriali</a></li>
<li class="chapter" data-level="2.6.6" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#variabili-di-confondimento"><i class="fa fa-check"></i><b>2.6.6</b> Variabili di confondimento</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#esperimenti-di-campo"><i class="fa fa-check"></i><b>2.7</b> Esperimenti di campo</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#scegliere-il-campo"><i class="fa fa-check"></i><b>2.7.1</b> Scegliere il campo</a></li>
<li class="chapter" data-level="2.7.2" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#le-unità-sperimentali-in-campo"><i class="fa fa-check"></i><b>2.7.2</b> Le unità sperimentali in campo</a></li>
<li class="chapter" data-level="2.7.3" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#numero-di-repliche"><i class="fa fa-check"></i><b>2.7.3</b> Numero di repliche</a></li>
<li class="chapter" data-level="2.7.4" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#la-mappa-di-campo"><i class="fa fa-check"></i><b>2.7.4</b> La mappa di campo</a></li>
<li class="chapter" data-level="2.7.5" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#lay-out-sperimentale"><i class="fa fa-check"></i><b>2.7.5</b> Lay-out sperimentale</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="progettare-un-esperimento.html"><a href="progettare-un-esperimento.html#altre-letture-1"><i class="fa fa-check"></i><b>2.8</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html"><i class="fa fa-check"></i><b>3</b> Richiami di statistica descrittiva</a>
<ul>
<li class="chapter" data-level="3.1" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#descrizione-di-dati-quantitativi"><i class="fa fa-check"></i><b>3.1</b> Descrizione di dati quantitativi</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#indicatori-di-tendenza-centrale"><i class="fa fa-check"></i><b>3.1.1</b> Indicatori di tendenza centrale</a></li>
<li class="chapter" data-level="3.1.2" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#indicatori-di-dispersione"><i class="fa fa-check"></i><b>3.1.2</b> Indicatori di dispersione</a></li>
<li class="chapter" data-level="3.1.3" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#incertezza-delle-misure-derivate"><i class="fa fa-check"></i><b>3.1.3</b> Incertezza delle misure derivate</a></li>
<li class="chapter" data-level="3.1.4" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#relazioni-tra-variabili-quantitative-correlazione"><i class="fa fa-check"></i><b>3.1.4</b> Relazioni tra variabili quantitative: correlazione</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#descrizione-di-dati-qualitativi"><i class="fa fa-check"></i><b>3.2</b> Descrizione di dati qualitativi</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#distribuzioni-di-frequenze-e-classamento"><i class="fa fa-check"></i><b>3.2.1</b> Distribuzioni di frequenze e classamento</a></li>
<li class="chapter" data-level="3.2.2" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#statistiche-descrittive-per-le-distribuzioni-di-frequenze"><i class="fa fa-check"></i><b>3.2.2</b> Statistiche descrittive per le distribuzioni di frequenze</a></li>
<li class="chapter" data-level="3.2.3" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#distribuzioni-di-frequenza-bivariate-le-tabelle-di-contingenze"><i class="fa fa-check"></i><b>3.2.3</b> Distribuzioni di frequenza bivariate: le tabelle di contingenze</a></li>
<li class="chapter" data-level="3.2.4" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#connessione"><i class="fa fa-check"></i><b>3.2.4</b> Connessione</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#statistiche-descrittive-con-r"><i class="fa fa-check"></i><b>3.3</b> Statistiche descrittive con R</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#descrizione-dei-sottogruppi"><i class="fa fa-check"></i><b>3.3.1</b> Descrizione dei sottogruppi</a></li>
<li class="chapter" data-level="3.3.2" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#distribuzioni-di-frequenze-e-classamento-1"><i class="fa fa-check"></i><b>3.3.2</b> Distribuzioni di frequenze e classamento</a></li>
<li class="chapter" data-level="3.3.3" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#connessione-1"><i class="fa fa-check"></i><b>3.3.3</b> Connessione</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="richiami-di-statistica-descrittiva.html"><a href="richiami-di-statistica-descrittiva.html#altre-letture-2"><i class="fa fa-check"></i><b>3.4</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html"><i class="fa fa-check"></i><b>4</b> Modelli statistici ed analisi dei dati</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#verità-vera-e-modelli-deterministici"><i class="fa fa-check"></i><b>4.1</b> Verità ‘vera’ e modelli deterministici</a></li>
<li class="chapter" data-level="4.2" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#genesi-deterministica-delle-osservazioni-sperimentali"><i class="fa fa-check"></i><b>4.2</b> Genesi deterministica delle osservazioni sperimentali</a></li>
<li class="chapter" data-level="4.3" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#errore-sperimentale-e-modelli-stocastici"><i class="fa fa-check"></i><b>4.3</b> Errore sperimentale e modelli stocastici</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#funzioni-di-probabilità"><i class="fa fa-check"></i><b>4.3.1</b> Funzioni di probabilità</a></li>
<li class="chapter" data-level="4.3.2" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#funzioni-di-densità"><i class="fa fa-check"></i><b>4.3.2</b> Funzioni di densità</a></li>
<li class="chapter" data-level="4.3.3" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#la-distribuzione-normale-curva-di-gauss"><i class="fa fa-check"></i><b>4.3.3</b> La distribuzione normale (curva di Gauss)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#modelli-a-due-facce"><i class="fa fa-check"></i><b>4.4</b> Modelli ‘a due facce’</a></li>
<li class="chapter" data-level="4.5" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#e-allora"><i class="fa fa-check"></i><b>4.5</b> E allora?</a></li>
<li class="chapter" data-level="4.6" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#le-simulazioni-monte-carlo"><i class="fa fa-check"></i><b>4.6</b> Le simulazioni Monte Carlo</a></li>
<li class="chapter" data-level="4.7" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#analisi-dei-dati-e-model-fitting"><i class="fa fa-check"></i><b>4.7</b> Analisi dei dati e ‘model fitting’</a></li>
<li class="chapter" data-level="4.8" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#modelli-stocastici-non-normali"><i class="fa fa-check"></i><b>4.8</b> Modelli stocastici non-normali</a></li>
<li class="chapter" data-level="4.9" data-path="modelli-statistici-ed-analisi-dei-dati.html"><a href="modelli-statistici-ed-analisi-dei-dati.html#altre-letture-3"><i class="fa fa-check"></i><b>4.9</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html"><i class="fa fa-check"></i><b>5</b> Stime ed incertezza</a>
<ul>
<li class="chapter" data-level="5.1" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#esempio-una-soluzione-erbicida"><i class="fa fa-check"></i><b>5.1</b> Esempio: una soluzione erbicida</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#analisi-dei-dati-stima-dei-parametri"><i class="fa fa-check"></i><b>5.1.1</b> Analisi dei dati: stima dei parametri</a></li>
<li class="chapter" data-level="5.1.2" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#la-sampling-distribution"><i class="fa fa-check"></i><b>5.1.2</b> La ‘sampling distribution’</a></li>
<li class="chapter" data-level="5.1.3" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#lerrore-standard"><i class="fa fa-check"></i><b>5.1.3</b> L’errore standard</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#stima-per-intervallo"><i class="fa fa-check"></i><b>5.2</b> Stima per intervallo</a></li>
<li class="chapter" data-level="5.3" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#lintervallo-di-confidenza"><i class="fa fa-check"></i><b>5.3</b> L’intervallo di confidenza</a></li>
<li class="chapter" data-level="5.4" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#qual-è-il-senso-dellintervallo-di-confidenza"><i class="fa fa-check"></i><b>5.4</b> Qual è il senso dell’intervallo di confidenza?</a></li>
<li class="chapter" data-level="5.5" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#come-presentare-i-risultati-degli-esperimenti"><i class="fa fa-check"></i><b>5.5</b> Come presentare i risultati degli esperimenti</a></li>
<li class="chapter" data-level="5.6" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#alcune-precisazioni"><i class="fa fa-check"></i><b>5.6</b> Alcune precisazioni</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#campioni-numerosi-e-non"><i class="fa fa-check"></i><b>5.6.1</b> Campioni numerosi e non</a></li>
<li class="chapter" data-level="5.6.2" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#popolazioni-gaussiane-e-non"><i class="fa fa-check"></i><b>5.6.2</b> Popolazioni gaussiane e non</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#analisi-statistica-dei-dati-riassunto-del-percorso-logico"><i class="fa fa-check"></i><b>5.7</b> Analisi statistica dei dati: riassunto del percorso logico</a></li>
<li class="chapter" data-level="5.8" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#da-ricordare"><i class="fa fa-check"></i><b>5.8</b> Da ricordare</a></li>
<li class="chapter" data-level="5.9" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#per-approfondire-un-po"><i class="fa fa-check"></i><b>5.9</b> Per approfondire un po’…</a></li>
<li class="chapter" data-level="5.10" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#coverage-degli-intervalli-di-confidenza"><i class="fa fa-check"></i><b>5.10</b> <em>Coverage</em> degli intervalli di confidenza</a>
<ul>
<li class="chapter" data-level="5.10.1" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#intervalli-di-confidenza-per-fenomeni-non-normali"><i class="fa fa-check"></i><b>5.10.1</b> Intervalli di confidenza per fenomeni non-normali</a></li>
</ul></li>
<li class="chapter" data-level="5.11" data-path="stime-ed-incertezza.html"><a href="stime-ed-incertezza.html#altre-letture-4"><i class="fa fa-check"></i><b>5.11</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html"><i class="fa fa-check"></i><b>6</b> Decisioni ed incertezza</a>
<ul>
<li class="chapter" data-level="6.1" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#confronto-tra-due-medie-il-test-t-di-student"><i class="fa fa-check"></i><b>6.1</b> Confronto tra due medie: il test t di Student</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#lipotesi-nulla-e-alternativa"><i class="fa fa-check"></i><b>6.1.1</b> L’ipotesi nulla e alternativa</a></li>
<li class="chapter" data-level="6.1.2" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#la-statistica-t"><i class="fa fa-check"></i><b>6.1.2</b> La statistica T</a></li>
<li class="chapter" data-level="6.1.3" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#simulazione-monte-carlo"><i class="fa fa-check"></i><b>6.1.3</b> Simulazione Monte Carlo</a></li>
<li class="chapter" data-level="6.1.4" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#soluzione-formale"><i class="fa fa-check"></i><b>6.1.4</b> Soluzione formale</a></li>
<li class="chapter" data-level="6.1.5" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#interpretazione-del-p-level"><i class="fa fa-check"></i><b>6.1.5</b> Interpretazione del P-level</a></li>
<li class="chapter" data-level="6.1.6" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#tipologie-alternative-di-test-t-di-student"><i class="fa fa-check"></i><b>6.1.6</b> Tipologie alternative di test t di Student</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#confronto-tra-due-proporzioni-il-test-chi2"><i class="fa fa-check"></i><b>6.2</b> Confronto tra due proporzioni: il test <span class="math inline">\(\chi^2\)</span></a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#simulazione-monte-carlo-1"><i class="fa fa-check"></i><b>6.2.1</b> Simulazione Monte Carlo</a></li>
<li class="chapter" data-level="6.2.2" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#soluzione-formale-1"><i class="fa fa-check"></i><b>6.2.2</b> Soluzione formale</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#conclusioni-e-riepilogo"><i class="fa fa-check"></i><b>6.3</b> Conclusioni e riepilogo</a></li>
<li class="chapter" data-level="6.4" data-path="decisioni-ed-incertezza.html"><a href="decisioni-ed-incertezza.html#altre-letture-5"><i class="fa fa-check"></i><b>6.4</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html"><i class="fa fa-check"></i><b>7</b> Modelli ANOVA ad una via</a>
<ul>
<li class="chapter" data-level="7.1" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#caso-studio-confronto-tra-erbicidi-in-vaso"><i class="fa fa-check"></i><b>7.1</b> Caso-studio: confronto tra erbicidi in vaso</a></li>
<li class="chapter" data-level="7.2" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#descrizione-del-dataset"><i class="fa fa-check"></i><b>7.2</b> Descrizione del dataset</a></li>
<li class="chapter" data-level="7.3" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#definizione-di-un-modello-lineare"><i class="fa fa-check"></i><b>7.3</b> Definizione di un modello lineare</a></li>
<li class="chapter" data-level="7.4" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#parametrizzazione-del-modello"><i class="fa fa-check"></i><b>7.4</b> Parametrizzazione del modello</a></li>
<li class="chapter" data-level="7.5" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#assunzioni-di-base"><i class="fa fa-check"></i><b>7.5</b> Assunzioni di base</a></li>
<li class="chapter" data-level="7.6" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#fitting-del-modello-metodo-manuale"><i class="fa fa-check"></i><b>7.6</b> Fitting del modello: metodo manuale</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#stima-dei-parametri"><i class="fa fa-check"></i><b>7.6.1</b> Stima dei parametri</a></li>
<li class="chapter" data-level="7.6.2" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#calcolo-dei-residui"><i class="fa fa-check"></i><b>7.6.2</b> Calcolo dei residui</a></li>
<li class="chapter" data-level="7.6.3" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#stima-di-sigma"><i class="fa fa-check"></i><b>7.6.3</b> Stima di <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#scomposizione-della-varianza"><i class="fa fa-check"></i><b>7.7</b> Scomposizione della varianza</a></li>
<li class="chapter" data-level="7.8" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#test-dipotesi"><i class="fa fa-check"></i><b>7.8</b> Test d’ipotesi</a></li>
<li class="chapter" data-level="7.9" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#inferenza-statistica"><i class="fa fa-check"></i><b>7.9</b> Inferenza statistica</a></li>
<li class="chapter" data-level="7.10" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#fitting-del-modello-con-r"><i class="fa fa-check"></i><b>7.10</b> Fitting del modello con R</a></li>
<li class="chapter" data-level="7.11" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#medie-marginali-attese"><i class="fa fa-check"></i><b>7.11</b> Medie marginali attese</a></li>
<li class="chapter" data-level="7.12" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#per-concludere"><i class="fa fa-check"></i><b>7.12</b> Per concludere …</a></li>
<li class="chapter" data-level="7.13" data-path="modelli-anova-ad-una-via.html"><a href="modelli-anova-ad-una-via.html#altre-letture-6"><i class="fa fa-check"></i><b>7.13</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html"><i class="fa fa-check"></i><b>8</b> La verifica delle assunzioni di base</a>
<ul>
<li class="chapter" data-level="8.1" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#violazioni-delle-assunzioni-di-base"><i class="fa fa-check"></i><b>8.1</b> Violazioni delle assunzioni di base</a></li>
<li class="chapter" data-level="8.2" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#procedure-diagnostiche"><i class="fa fa-check"></i><b>8.2</b> Procedure diagnostiche</a></li>
<li class="chapter" data-level="8.3" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#analisi-grafica-dei-residui"><i class="fa fa-check"></i><b>8.3</b> Analisi grafica dei residui</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#grafico-dei-residui-contro-i-valori-attesi"><i class="fa fa-check"></i><b>8.3.1</b> Grafico dei residui contro i valori attesi</a></li>
<li class="chapter" data-level="8.3.2" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#qq-plot"><i class="fa fa-check"></i><b>8.3.2</b> QQ-plot</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#test-dipotesi-1"><i class="fa fa-check"></i><b>8.4</b> Test d’ipotesi</a></li>
<li class="chapter" data-level="8.5" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#risultati-contraddittori"><i class="fa fa-check"></i><b>8.5</b> Risultati contraddittori</a></li>
<li class="chapter" data-level="8.6" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#terapia"><i class="fa fa-check"></i><b>8.6</b> ‘Terapia’</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#correzionerimozione-degli-outliers"><i class="fa fa-check"></i><b>8.6.1</b> Correzione/Rimozione degli outliers</a></li>
<li class="chapter" data-level="8.6.2" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#correzione-del-modello"><i class="fa fa-check"></i><b>8.6.2</b> Correzione del modello</a></li>
<li class="chapter" data-level="8.6.3" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#trasformazione-della-variabile-indipendente"><i class="fa fa-check"></i><b>8.6.3</b> Trasformazione della variabile indipendente</a></li>
<li class="chapter" data-level="8.6.4" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#impiego-di-metodiche-statistiche-avanzate"><i class="fa fa-check"></i><b>8.6.4</b> Impiego di metodiche statistiche avanzate</a></li>
<li class="chapter" data-level="8.6.5" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#trasformazioni-stabilizzanti"><i class="fa fa-check"></i><b>8.6.5</b> Trasformazioni stabilizzanti</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#esempio-1"><i class="fa fa-check"></i><b>8.7</b> Esempio 1</a></li>
<li class="chapter" data-level="8.8" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#esempio-2"><i class="fa fa-check"></i><b>8.8</b> Esempio 2</a></li>
<li class="chapter" data-level="8.9" data-path="la-verifica-delle-assunzioni-di-base.html"><a href="la-verifica-delle-assunzioni-di-base.html#altre-letture-7"><i class="fa fa-check"></i><b>8.9</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html"><i class="fa fa-check"></i><b>9</b> Contrasti e confronti multipli</a>
<ul>
<li class="chapter" data-level="9.1" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#esempio"><i class="fa fa-check"></i><b>9.1</b> Esempio</a></li>
<li class="chapter" data-level="9.2" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#i-contrasti"><i class="fa fa-check"></i><b>9.2</b> I contrasti</a></li>
<li class="chapter" data-level="9.3" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#i-contrasti-con-r"><i class="fa fa-check"></i><b>9.3</b> I contrasti con R</a></li>
<li class="chapter" data-level="9.4" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#i-confronti-multipli-a-coppie-pairwise-comparisons"><i class="fa fa-check"></i><b>9.4</b> I confronti multipli a coppie (pairwise comparisons)</a></li>
<li class="chapter" data-level="9.5" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#display-a-lettere"><i class="fa fa-check"></i><b>9.5</b> Display a lettere</a></li>
<li class="chapter" data-level="9.6" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#tassi-di-errore-per-confronto-e-per-esperimento"><i class="fa fa-check"></i><b>9.6</b> Tassi di errore per confronto e per esperimento</a></li>
<li class="chapter" data-level="9.7" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#aggiustamento-per-la-molteplicità"><i class="fa fa-check"></i><b>9.7</b> Aggiustamento per la molteplicità</a></li>
<li class="chapter" data-level="9.8" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#e-le-classiche-procedure-di-confronto-multiplo"><i class="fa fa-check"></i><b>9.8</b> E le classiche procedure di confronto multiplo?</a></li>
<li class="chapter" data-level="9.9" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#consigli-pratici"><i class="fa fa-check"></i><b>9.9</b> Consigli pratici</a></li>
<li class="chapter" data-level="9.10" data-path="contrasti-e-confronti-multipli.html"><a href="contrasti-e-confronti-multipli.html#altre-letture-8"><i class="fa fa-check"></i><b>9.10</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html"><i class="fa fa-check"></i><b>10</b> Modelli ANOVA con fattori di blocco</a>
<ul>
<li class="chapter" data-level="10.1" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#caso-studio-confronto-tra-erbicidi-in-campo"><i class="fa fa-check"></i><b>10.1</b> Caso-studio: confronto tra erbicidi in campo</a></li>
<li class="chapter" data-level="10.2" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#definizione-di-un-modello-lineare-1"><i class="fa fa-check"></i><b>10.2</b> Definizione di un modello lineare</a></li>
<li class="chapter" data-level="10.3" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#stima-dei-parametri-1"><i class="fa fa-check"></i><b>10.3</b> Stima dei parametri</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#coefficienti-del-modello"><i class="fa fa-check"></i><b>10.3.1</b> Coefficienti del modello</a></li>
<li class="chapter" data-level="10.3.2" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#stima-di-sigma-1"><i class="fa fa-check"></i><b>10.3.2</b> Stima di <span class="math inline">\(\sigma\)</span></a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#scomposizione-della-varianza-1"><i class="fa fa-check"></i><b>10.4</b> Scomposizione della varianza</a></li>
<li class="chapter" data-level="10.5" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#adattamento-del-modello-con-r"><i class="fa fa-check"></i><b>10.5</b> Adattamento del modello con R</a></li>
<li class="chapter" data-level="10.6" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#disegni-a-quadrato-latino-1"><i class="fa fa-check"></i><b>10.6</b> Disegni a quadrato latino</a></li>
<li class="chapter" data-level="10.7" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#caso-studio-confronto-tra-metodi-costruttivi"><i class="fa fa-check"></i><b>10.7</b> Caso studio: confronto tra metodi costruttivi</a></li>
<li class="chapter" data-level="10.8" data-path="modelli-anova-con-fattori-di-blocco.html"><a href="modelli-anova-con-fattori-di-blocco.html#definizione-di-un-modello-lineare-2"><i class="fa fa-check"></i><b>10.8</b> Definizione di un modello lineare</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html"><i class="fa fa-check"></i><b>11</b> La regressione lineare semplice</a>
<ul>
<li class="chapter" data-level="11.1" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#caso-studio-effetto-della-concimazione-azotata-al-frumento"><i class="fa fa-check"></i><b>11.1</b> Caso studio: effetto della concimazione azotata al frumento</a></li>
<li class="chapter" data-level="11.2" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#analisi-preliminari"><i class="fa fa-check"></i><b>11.2</b> Analisi preliminari</a></li>
<li class="chapter" data-level="11.3" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#definizione-del-modello-lineare"><i class="fa fa-check"></i><b>11.3</b> Definizione del modello lineare</a></li>
<li class="chapter" data-level="11.4" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#stima-dei-parametri-2"><i class="fa fa-check"></i><b>11.4</b> Stima dei parametri</a></li>
<li class="chapter" data-level="11.5" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#valutazione-della-bontà-del-modello"><i class="fa fa-check"></i><b>11.5</b> Valutazione della bontà del modello</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#valutazione-grafica"><i class="fa fa-check"></i><b>11.5.1</b> Valutazione grafica</a></li>
<li class="chapter" data-level="11.5.2" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#errori-standard-dei-parametri"><i class="fa fa-check"></i><b>11.5.2</b> Errori standard dei parametri</a></li>
<li class="chapter" data-level="11.5.3" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#test-f-per-la-mancanza-dadattamento"><i class="fa fa-check"></i><b>11.5.3</b> Test F per la mancanza d’adattamento</a></li>
<li class="chapter" data-level="11.5.4" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#test-f-per-la-bontà-di-adattamento"><i class="fa fa-check"></i><b>11.5.4</b> Test F per la bontà di adattamento</a></li>
<li class="chapter" data-level="11.5.5" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#coefficiente-di-determinazione"><i class="fa fa-check"></i><b>11.5.5</b> Coefficiente di determinazione</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#previsioni"><i class="fa fa-check"></i><b>11.6</b> Previsioni</a></li>
<li class="chapter" data-level="11.7" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#disegni-a-blocchi-randomizzati-1"><i class="fa fa-check"></i><b>11.7</b> Disegni a blocchi randomizzati</a></li>
<li class="chapter" data-level="11.8" data-path="la-regressione-lineare-semplice.html"><a href="la-regressione-lineare-semplice.html#altre-letture-9"><i class="fa fa-check"></i><b>11.8</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html"><i class="fa fa-check"></i><b>12</b> Modelli ANOVA a due vie con interazione</a>
<ul>
<li class="chapter" data-level="12.1" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#il-concetto-di-interazione"><i class="fa fa-check"></i><b>12.1</b> Il concetto di ’interazione’</a></li>
<li class="chapter" data-level="12.2" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#effetti-incrociati-interazione-tra-lavorazioni-e-diserbo-chimico"><i class="fa fa-check"></i><b>12.2</b> Effetti incrociati: interazione tra lavorazioni e diserbo chimico</a></li>
<li class="chapter" data-level="12.3" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#definizione-del-modello-lineare-1"><i class="fa fa-check"></i><b>12.3</b> Definizione del modello lineare</a></li>
<li class="chapter" data-level="12.4" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#calcoli-manuali"><i class="fa fa-check"></i><b>12.4</b> Calcoli manuali</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#scomposizione-della-varianza-2"><i class="fa fa-check"></i><b>12.4.1</b> Scomposizione della varianza</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#calcoli-con-r"><i class="fa fa-check"></i><b>12.5</b> Calcoli con R</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#model-fitting"><i class="fa fa-check"></i><b>12.5.1</b> Model fitting</a></li>
<li class="chapter" data-level="12.5.2" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#verifica-delle-assunzioni-di-base"><i class="fa fa-check"></i><b>12.5.2</b> Verifica delle assunzioni di base</a></li>
<li class="chapter" data-level="12.5.3" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#scomposizione-della-varianza-3"><i class="fa fa-check"></i><b>12.5.3</b> Scomposizione della varianza</a></li>
<li class="chapter" data-level="12.5.4" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#medie-marginali-attese-e-confronti-multipli-con-r"><i class="fa fa-check"></i><b>12.5.4</b> Medie marginali attese e confronti multipli con R</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#effetti-innestati-valutazione-di-ibridi-di-mais"><i class="fa fa-check"></i><b>12.6</b> Effetti innestati: valutazione di ibridi di mais</a></li>
<li class="chapter" data-level="12.7" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#definizione-del-modello-lineare-2"><i class="fa fa-check"></i><b>12.7</b> Definizione del modello lineare</a></li>
<li class="chapter" data-level="12.8" data-path="modelli-anova-a-due-vie-con-interazione.html"><a href="modelli-anova-a-due-vie-con-interazione.html#fitting-del-modello-con-r-1"><i class="fa fa-check"></i><b>12.8</b> Fitting del modello con R</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html"><i class="fa fa-check"></i><b>13</b> Breve introduzione ai modelli misti</a>
<ul>
<li class="chapter" data-level="13.1" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#raggruppamenti-tra-parcelle"><i class="fa fa-check"></i><b>13.1</b> Raggruppamenti tra parcelle</a></li>
<li class="chapter" data-level="13.2" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#esperimenti-a-split-plot"><i class="fa fa-check"></i><b>13.2</b> Esperimenti a split-plot</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#definizione-del-modello-lineare-3"><i class="fa fa-check"></i><b>13.2.1</b> Definizione del modello lineare</a></li>
<li class="chapter" data-level="13.2.2" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#model-fitting-con-r"><i class="fa fa-check"></i><b>13.2.2</b> Model fitting con R</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#esperimenti-a-strip-plot"><i class="fa fa-check"></i><b>13.3</b> Esperimenti a strip-plot</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#definizione-del-modello-lineare-4"><i class="fa fa-check"></i><b>13.3.1</b> Definizione del modello lineare</a></li>
<li class="chapter" data-level="13.3.2" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#model-fitting-con-r-1"><i class="fa fa-check"></i><b>13.3.2</b> Model fitting con R</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="breve-introduzione-ai-modelli-misti.html"><a href="breve-introduzione-ai-modelli-misti.html#altre-letture-10"><i class="fa fa-check"></i><b>13.4</b> Altre letture</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html"><i class="fa fa-check"></i><b>14</b> La regressione non-lineare</a>
<ul>
<li class="chapter" data-level="14.1" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#caso-studio-degradazione-di-un-erbicida-nel-terreno"><i class="fa fa-check"></i><b>14.1</b> Caso studio: degradazione di un erbicida nel terreno</a></li>
<li class="chapter" data-level="14.2" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#scelta-della-funzione"><i class="fa fa-check"></i><b>14.2</b> Scelta della funzione</a></li>
<li class="chapter" data-level="14.3" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#stima-dei-parametri-3"><i class="fa fa-check"></i><b>14.3</b> Stima dei parametri</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#linearizzazione-della-funzione"><i class="fa fa-check"></i><b>14.3.1</b> Linearizzazione della funzione</a></li>
<li class="chapter" data-level="14.3.2" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#approssimazione-della-vera-funzione-tramite-una-polinomiale-in-x"><i class="fa fa-check"></i><b>14.3.2</b> Approssimazione della vera funzione tramite una polinomiale in X</a></li>
<li class="chapter" data-level="14.3.3" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#minimi-quadrati-non-lineari"><i class="fa fa-check"></i><b>14.3.3</b> Minimi quadrati non-lineari</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#la-regressione-non-lineare-con-r"><i class="fa fa-check"></i><b>14.4</b> La regressione non-lineare con R</a></li>
<li class="chapter" data-level="14.5" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#verifica-della-bontà-del-modello"><i class="fa fa-check"></i><b>14.5</b> Verifica della bontà del modello</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#analisi-grafica-dei-residui-1"><i class="fa fa-check"></i><b>14.5.1</b> Analisi grafica dei residui</a></li>
<li class="chapter" data-level="14.5.2" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#test-f-per-la-mancanza-di-adattamento-approssimato"><i class="fa fa-check"></i><b>14.5.2</b> Test F per la mancanza di adattamento (approssimato)</a></li>
<li class="chapter" data-level="14.5.3" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#errori-standard-dei-parametri-1"><i class="fa fa-check"></i><b>14.5.3</b> Errori standard dei parametri</a></li>
<li class="chapter" data-level="14.5.4" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#coefficiente-di-determinazione-1"><i class="fa fa-check"></i><b>14.5.4</b> Coefficiente di determinazione</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#funzioni-lineari-e-nonlineari-dei-parametri"><i class="fa fa-check"></i><b>14.6</b> Funzioni lineari e nonlineari dei parametri</a></li>
<li class="chapter" data-level="14.7" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#previsioni-1"><i class="fa fa-check"></i><b>14.7</b> Previsioni</a></li>
<li class="chapter" data-level="14.8" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#gestione-delle-situazioni-patologiche"><i class="fa fa-check"></i><b>14.8</b> Gestione delle situazioni ‘patologiche’</a>
<ul>
<li class="chapter" data-level="14.8.1" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#trasformazione-del-modello"><i class="fa fa-check"></i><b>14.8.1</b> Trasformazione del modello</a></li>
<li class="chapter" data-level="14.8.2" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#trasformazione-dei-dati"><i class="fa fa-check"></i><b>14.8.2</b> Trasformazione dei dati</a></li>
</ul></li>
<li class="chapter" data-level="14.9" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#per-approfondire-un-po-1"><i class="fa fa-check"></i><b>14.9</b> Per approfondire un po’…</a>
<ul>
<li class="chapter" data-level="14.9.1" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#riparametrizzazione-delle-funzioni-non-lineari"><i class="fa fa-check"></i><b>14.9.1</b> Riparametrizzazione delle funzioni non-lineari</a></li>
<li class="chapter" data-level="14.9.2" data-path="la-regressione-non-lineare.html"><a href="la-regressione-non-lineare.html#altre-letture-11"><i class="fa fa-check"></i><b>14.9.2</b> Altre letture</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="esercizi.html"><a href="esercizi.html"><i class="fa fa-check"></i><b>15</b> Esercizi</a>
<ul>
<li class="chapter" data-level="15.1" data-path="esercizi.html"><a href="esercizi.html#il-disegno-degli-esperimenti-cap.-1-e-2"><i class="fa fa-check"></i><b>15.1</b> Il disegno degli esperimenti (Cap. 1 e 2)</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="esercizi.html"><a href="esercizi.html#domanda-1"><i class="fa fa-check"></i><b>15.1.1</b> Domanda 1</a></li>
<li class="chapter" data-level="15.1.2" data-path="esercizi.html"><a href="esercizi.html#domanda-2"><i class="fa fa-check"></i><b>15.1.2</b> Domanda 2</a></li>
<li class="chapter" data-level="15.1.3" data-path="esercizi.html"><a href="esercizi.html#domanda-3"><i class="fa fa-check"></i><b>15.1.3</b> Domanda 3</a></li>
<li class="chapter" data-level="15.1.4" data-path="esercizi.html"><a href="esercizi.html#domanda-4"><i class="fa fa-check"></i><b>15.1.4</b> Domanda 4</a></li>
<li class="chapter" data-level="15.1.5" data-path="esercizi.html"><a href="esercizi.html#domanda-5"><i class="fa fa-check"></i><b>15.1.5</b> Domanda 5</a></li>
<li class="chapter" data-level="15.1.6" data-path="esercizi.html"><a href="esercizi.html#domanda-6"><i class="fa fa-check"></i><b>15.1.6</b> Domanda 6</a></li>
<li class="chapter" data-level="15.1.7" data-path="esercizi.html"><a href="esercizi.html#domanda-7"><i class="fa fa-check"></i><b>15.1.7</b> Domanda 7</a></li>
<li class="chapter" data-level="15.1.8" data-path="esercizi.html"><a href="esercizi.html#domanda-8"><i class="fa fa-check"></i><b>15.1.8</b> Domanda 8</a></li>
<li class="chapter" data-level="15.1.9" data-path="esercizi.html"><a href="esercizi.html#domanda-9"><i class="fa fa-check"></i><b>15.1.9</b> Domanda 9</a></li>
<li class="chapter" data-level="15.1.10" data-path="esercizi.html"><a href="esercizi.html#domanda-10"><i class="fa fa-check"></i><b>15.1.10</b> Domanda 10</a></li>
<li class="chapter" data-level="15.1.11" data-path="esercizi.html"><a href="esercizi.html#domanda-12"><i class="fa fa-check"></i><b>15.1.11</b> Domanda 12</a></li>
<li class="chapter" data-level="15.1.12" data-path="esercizi.html"><a href="esercizi.html#domanda-13"><i class="fa fa-check"></i><b>15.1.12</b> Domanda 13</a></li>
<li class="chapter" data-level="15.1.13" data-path="esercizi.html"><a href="esercizi.html#esercizio-1"><i class="fa fa-check"></i><b>15.1.13</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.1.14" data-path="esercizi.html"><a href="esercizi.html#esercizio-2"><i class="fa fa-check"></i><b>15.1.14</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.1.15" data-path="esercizi.html"><a href="esercizi.html#esercizio-3"><i class="fa fa-check"></i><b>15.1.15</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.1.16" data-path="esercizi.html"><a href="esercizi.html#esercizio-4"><i class="fa fa-check"></i><b>15.1.16</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.1.17" data-path="esercizi.html"><a href="esercizi.html#esercizio-5"><i class="fa fa-check"></i><b>15.1.17</b> Esercizio 5</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="esercizi.html"><a href="esercizi.html#statistica-descrittiva-cap.-3"><i class="fa fa-check"></i><b>15.2</b> Statistica descrittiva (Cap. 3)</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="esercizi.html"><a href="esercizi.html#domanda-1-1"><i class="fa fa-check"></i><b>15.2.1</b> Domanda 1</a></li>
<li class="chapter" data-level="15.2.2" data-path="esercizi.html"><a href="esercizi.html#domanda-2-1"><i class="fa fa-check"></i><b>15.2.2</b> Domanda 2</a></li>
<li class="chapter" data-level="15.2.3" data-path="esercizi.html"><a href="esercizi.html#domanda-3-1"><i class="fa fa-check"></i><b>15.2.3</b> Domanda 3</a></li>
<li class="chapter" data-level="15.2.4" data-path="esercizi.html"><a href="esercizi.html#domanda-4-1"><i class="fa fa-check"></i><b>15.2.4</b> Domanda 4</a></li>
<li class="chapter" data-level="15.2.5" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-1"><i class="fa fa-check"></i><b>15.2.5</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.2.6" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-1"><i class="fa fa-check"></i><b>15.2.6</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.2.7" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-1"><i class="fa fa-check"></i><b>15.2.7</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.2.8" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-1"><i class="fa fa-check"></i><b>15.2.8</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.2.9" data-path="esercizi.html"><a href="esercizi.html#esercizio-5-1"><i class="fa fa-check"></i><b>15.2.9</b> Esercizio 5</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="esercizi.html"><a href="esercizi.html#modelli-statistici-cap.-4"><i class="fa fa-check"></i><b>15.3</b> Modelli statistici (Cap. 4)</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-2"><i class="fa fa-check"></i><b>15.3.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.3.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-2"><i class="fa fa-check"></i><b>15.3.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.3.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-2"><i class="fa fa-check"></i><b>15.3.3</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.3.4" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-2"><i class="fa fa-check"></i><b>15.3.4</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.3.5" data-path="esercizi.html"><a href="esercizi.html#esercizio-5-2"><i class="fa fa-check"></i><b>15.3.5</b> Esercizio 5</a></li>
<li class="chapter" data-level="15.3.6" data-path="esercizi.html"><a href="esercizi.html#esercizio-6"><i class="fa fa-check"></i><b>15.3.6</b> Esercizio 6</a></li>
<li class="chapter" data-level="15.3.7" data-path="esercizi.html"><a href="esercizi.html#esercizio-7"><i class="fa fa-check"></i><b>15.3.7</b> Esercizio 7</a></li>
<li class="chapter" data-level="15.3.8" data-path="esercizi.html"><a href="esercizi.html#esercizio-8"><i class="fa fa-check"></i><b>15.3.8</b> Esercizio 8</a></li>
<li class="chapter" data-level="15.3.9" data-path="esercizi.html"><a href="esercizi.html#esercizio-9"><i class="fa fa-check"></i><b>15.3.9</b> Esercizio 9</a></li>
<li class="chapter" data-level="15.3.10" data-path="esercizi.html"><a href="esercizi.html#esercizio-10"><i class="fa fa-check"></i><b>15.3.10</b> Esercizio 10</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="esercizi.html"><a href="esercizi.html#stima-dei-parametri-cap.-5"><i class="fa fa-check"></i><b>15.4</b> Stima dei parametri (Cap. 5)</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-3"><i class="fa fa-check"></i><b>15.4.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.4.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-3"><i class="fa fa-check"></i><b>15.4.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.4.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-3"><i class="fa fa-check"></i><b>15.4.3</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.4.4" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-3"><i class="fa fa-check"></i><b>15.4.4</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.4.5" data-path="esercizi.html"><a href="esercizi.html#esercizio-5-3"><i class="fa fa-check"></i><b>15.4.5</b> Esercizio 5</a></li>
<li class="chapter" data-level="15.4.6" data-path="esercizi.html"><a href="esercizi.html#esercizio-6-1"><i class="fa fa-check"></i><b>15.4.6</b> Esercizio 6</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="esercizi.html"><a href="esercizi.html#inferenza-cap.-6"><i class="fa fa-check"></i><b>15.5</b> Inferenza (Cap. 6)</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-4"><i class="fa fa-check"></i><b>15.5.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.5.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-4"><i class="fa fa-check"></i><b>15.5.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.5.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-4"><i class="fa fa-check"></i><b>15.5.3</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.5.4" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-4"><i class="fa fa-check"></i><b>15.5.4</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.5.5" data-path="esercizi.html"><a href="esercizi.html#esercizio-5-4"><i class="fa fa-check"></i><b>15.5.5</b> Esercizio 5</a></li>
<li class="chapter" data-level="15.5.6" data-path="esercizi.html"><a href="esercizi.html#esercizio-6-2"><i class="fa fa-check"></i><b>15.5.6</b> Esercizio 6</a></li>
<li class="chapter" data-level="15.5.7" data-path="esercizi.html"><a href="esercizi.html#esercizio-7-1"><i class="fa fa-check"></i><b>15.5.7</b> Esercizio 7</a></li>
<li class="chapter" data-level="15.5.8" data-path="esercizi.html"><a href="esercizi.html#esercizio-8-1"><i class="fa fa-check"></i><b>15.5.8</b> Esercizio 8</a></li>
<li class="chapter" data-level="15.5.9" data-path="esercizi.html"><a href="esercizi.html#esercizio-9-1"><i class="fa fa-check"></i><b>15.5.9</b> Esercizio 9</a></li>
<li class="chapter" data-level="15.5.10" data-path="esercizi.html"><a href="esercizi.html#esercizio-10-1"><i class="fa fa-check"></i><b>15.5.10</b> Esercizio 10</a></li>
<li class="chapter" data-level="15.5.11" data-path="esercizi.html"><a href="esercizi.html#esercizio-11"><i class="fa fa-check"></i><b>15.5.11</b> Esercizio 11</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="esercizi.html"><a href="esercizi.html#modelli-anova-ad-una-via-cap.-da-7-a-9"><i class="fa fa-check"></i><b>15.6</b> Modelli ANOVA ad una via (Cap. da 7 a 9)</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-5"><i class="fa fa-check"></i><b>15.6.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.6.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-5"><i class="fa fa-check"></i><b>15.6.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.6.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-5"><i class="fa fa-check"></i><b>15.6.3</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.6.4" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-5"><i class="fa fa-check"></i><b>15.6.4</b> Esercizio 4</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="esercizi.html"><a href="esercizi.html#anova-a-due-vie-cap.-10"><i class="fa fa-check"></i><b>15.7</b> ANOVA a due vie (Cap. 10)</a>
<ul>
<li class="chapter" data-level="15.7.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-6"><i class="fa fa-check"></i><b>15.7.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.7.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-6"><i class="fa fa-check"></i><b>15.7.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.7.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-6"><i class="fa fa-check"></i><b>15.7.3</b> Esercizio 3</a></li>
</ul></li>
<li class="chapter" data-level="15.8" data-path="esercizi.html"><a href="esercizi.html#regressione-cap.-11"><i class="fa fa-check"></i><b>15.8</b> Regressione (Cap. 11)</a>
<ul>
<li class="chapter" data-level="15.8.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-7"><i class="fa fa-check"></i><b>15.8.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.8.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-7"><i class="fa fa-check"></i><b>15.8.2</b> Esercizio 2</a></li>
</ul></li>
<li class="chapter" data-level="15.9" data-path="esercizi.html"><a href="esercizi.html#anova-a-due-vie-con-interazione-cap.-12-e-13"><i class="fa fa-check"></i><b>15.9</b> ANOVA a due vie con interazione (Cap. 12 e 13)</a>
<ul>
<li class="chapter" data-level="15.9.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-8"><i class="fa fa-check"></i><b>15.9.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.9.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-8"><i class="fa fa-check"></i><b>15.9.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.9.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-7"><i class="fa fa-check"></i><b>15.9.3</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.9.4" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-6"><i class="fa fa-check"></i><b>15.9.4</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.9.5" data-path="esercizi.html"><a href="esercizi.html#esercizio-5-5"><i class="fa fa-check"></i><b>15.9.5</b> Esercizio 5</a></li>
<li class="chapter" data-level="15.9.6" data-path="esercizi.html"><a href="esercizi.html#esercizio-6-3"><i class="fa fa-check"></i><b>15.9.6</b> Esercizio 6</a></li>
</ul></li>
<li class="chapter" data-level="15.10" data-path="esercizi.html"><a href="esercizi.html#regressione-non-lineare-cap.-14"><i class="fa fa-check"></i><b>15.10</b> Regressione non-lineare (Cap. 14)</a>
<ul>
<li class="chapter" data-level="15.10.1" data-path="esercizi.html"><a href="esercizi.html#esercizio-1-9"><i class="fa fa-check"></i><b>15.10.1</b> Esercizio 1</a></li>
<li class="chapter" data-level="15.10.2" data-path="esercizi.html"><a href="esercizi.html#esercizio-2-9"><i class="fa fa-check"></i><b>15.10.2</b> Esercizio 2</a></li>
<li class="chapter" data-level="15.10.3" data-path="esercizi.html"><a href="esercizi.html#esercizio-3-8"><i class="fa fa-check"></i><b>15.10.3</b> Esercizio 3</a></li>
<li class="chapter" data-level="15.10.4" data-path="esercizi.html"><a href="esercizi.html#esercizio-4-7"><i class="fa fa-check"></i><b>15.10.4</b> Esercizio 4</a></li>
<li class="chapter" data-level="15.10.5" data-path="esercizi.html"><a href="esercizi.html#esercizio-5-6"><i class="fa fa-check"></i><b>15.10.5</b> Esercizio 5</a></li>
<li class="chapter" data-level="15.10.6" data-path="esercizi.html"><a href="esercizi.html#esercizio-6-4"><i class="fa fa-check"></i><b>15.10.6</b> Esercizio 6</a></li>
<li class="chapter" data-level="15.10.7" data-path="esercizi.html"><a href="esercizi.html#esercizio-7-2"><i class="fa fa-check"></i><b>15.10.7</b> Esercizio 7</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html"><i class="fa fa-check"></i><b>16</b> Appendice 1: breve introduzione ad R</a>
<ul>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#cosa-è-r"><i class="fa fa-check"></i>Cosa è R?</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#oggetti-e-assegnazioni"><i class="fa fa-check"></i>Oggetti e assegnazioni</a>
<ul>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#costanti-e-vettori"><i class="fa fa-check"></i>Costanti e vettori</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#matrici"><i class="fa fa-check"></i>Matrici</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#dataframe"><i class="fa fa-check"></i>Dataframe</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#quale-oggetto-sto-utilizzando"><i class="fa fa-check"></i>Quale oggetto sto utilizzando?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#operazioni-ed-operatori"><i class="fa fa-check"></i>Operazioni ed operatori</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#funzioni-ed-argomenti"><i class="fa fa-check"></i>Funzioni ed argomenti</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#consigli-per-limmissione-di-dati-sperimentali"><i class="fa fa-check"></i>Consigli per l’immissione di dati sperimentali</a>
<ul>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#immissione-di-numeri-progressivi"><i class="fa fa-check"></i>Immissione di numeri progressivi</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#immissione-dei-codici-delle-tesi-e-dei-blocchi"><i class="fa fa-check"></i>Immissione dei codici delle tesi e dei blocchi</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#immissione-dei-valori-e-creazione-del-datframe"><i class="fa fa-check"></i>Immissione dei valori e creazione del datframe</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#leggere-e-salvare-dati-esterni"><i class="fa fa-check"></i>Leggere e salvare dati esterni</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#alcune-operazioni-comuni-sul-dataset"><i class="fa fa-check"></i>Alcune operazioni comuni sul dataset</a>
<ul>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#selezionare-un-subset-di-dati"><i class="fa fa-check"></i>Selezionare un subset di dati</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#ordinare-un-vettore-o-un-dataframe"><i class="fa fa-check"></i>Ordinare un vettore o un dataframe</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#workspace"><i class="fa fa-check"></i>Workspace</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#script-o-programmi"><i class="fa fa-check"></i>Script o programmi</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#interrogazione-di-oggetti"><i class="fa fa-check"></i>Interrogazione di oggetti</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#altre-funzioni-matriciali"><i class="fa fa-check"></i>Altre funzioni matriciali</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#cenni-sulle-funzionalità-grafiche-in-r"><i class="fa fa-check"></i>Cenni sulle funzionalità grafiche in R</a></li>
<li class="chapter" data-level="" data-path="appendice-1-breve-introduzione-ad-r.html"><a href="appendice-1-breve-introduzione-ad-r.html#altre-letture-12"><i class="fa fa-check"></i>Altre letture</a></li>
</ul></li>
<li class="divider"></li>
<li><strong><a href="https://www.statforbiology.com">Back to blog</a></strong></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Metodologia sperimentale per le scienze agrarie</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="richiami-di-statistica-descrittiva" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capitolo 3</span> Richiami di statistica descrittiva<a href="richiami-di-statistica-descrittiva.html#richiami-di-statistica-descrittiva" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Qualunque esperimento include un processo di raccolta dati, tramite osservazioni e/o misurazioni, al termine del quale abbiamo a disposizione un collettivo di valori, di solito organizzati sotto forma di tabella (‘dataset’), dove ogni riga corrisponde ad un’unità sperimentale (soggetto) con tutti i suoi attributi, mentre ogni colonna (detta anche variabile) corrisponde ad un attributo e contiene i valori rilevati per tutte le unità sperimentali. Un esempio di dataset è riportato nella Tabella <a href="richiami-di-statistica-descrittiva.html#tab:tabName1">3.1</a>.</p>
<table>
<caption><span id="tab:tabName1">Tabella 3.1: </span>Numero totale (in migliaia) di passeggeri nei voli internazionali dal 1949 al 1960 (Box and Jenkins airline data).</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Gen</th>
<th align="right">Feb</th>
<th align="right">Mar</th>
<th align="right">Apr</th>
<th align="right">Mag</th>
<th align="right">Giu</th>
<th align="right">Lug</th>
<th align="right">Ago</th>
<th align="right">Set</th>
<th align="right">Ott</th>
<th align="right">Nov</th>
<th align="right">Dic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1949</td>
<td align="right">112</td>
<td align="right">115</td>
<td align="right">145</td>
<td align="right">171</td>
<td align="right">196</td>
<td align="right">204</td>
<td align="right">242</td>
<td align="right">284</td>
<td align="right">315</td>
<td align="right">340</td>
<td align="right">360</td>
<td align="right">417</td>
</tr>
<tr class="even">
<td align="left">1950</td>
<td align="right">118</td>
<td align="right">126</td>
<td align="right">150</td>
<td align="right">180</td>
<td align="right">196</td>
<td align="right">188</td>
<td align="right">233</td>
<td align="right">277</td>
<td align="right">301</td>
<td align="right">318</td>
<td align="right">342</td>
<td align="right">391</td>
</tr>
<tr class="odd">
<td align="left">1951</td>
<td align="right">132</td>
<td align="right">141</td>
<td align="right">178</td>
<td align="right">193</td>
<td align="right">236</td>
<td align="right">235</td>
<td align="right">267</td>
<td align="right">317</td>
<td align="right">356</td>
<td align="right">362</td>
<td align="right">406</td>
<td align="right">419</td>
</tr>
<tr class="even">
<td align="left">1952</td>
<td align="right">129</td>
<td align="right">135</td>
<td align="right">163</td>
<td align="right">181</td>
<td align="right">235</td>
<td align="right">227</td>
<td align="right">269</td>
<td align="right">313</td>
<td align="right">348</td>
<td align="right">348</td>
<td align="right">396</td>
<td align="right">461</td>
</tr>
<tr class="odd">
<td align="left">1953</td>
<td align="right">121</td>
<td align="right">125</td>
<td align="right">172</td>
<td align="right">183</td>
<td align="right">229</td>
<td align="right">234</td>
<td align="right">270</td>
<td align="right">318</td>
<td align="right">355</td>
<td align="right">363</td>
<td align="right">420</td>
<td align="right">472</td>
</tr>
<tr class="even">
<td align="left">1954</td>
<td align="right">135</td>
<td align="right">149</td>
<td align="right">178</td>
<td align="right">218</td>
<td align="right">243</td>
<td align="right">264</td>
<td align="right">315</td>
<td align="right">374</td>
<td align="right">422</td>
<td align="right">435</td>
<td align="right">472</td>
<td align="right">535</td>
</tr>
<tr class="odd">
<td align="left">1955</td>
<td align="right">148</td>
<td align="right">170</td>
<td align="right">199</td>
<td align="right">230</td>
<td align="right">264</td>
<td align="right">302</td>
<td align="right">364</td>
<td align="right">413</td>
<td align="right">465</td>
<td align="right">491</td>
<td align="right">548</td>
<td align="right">622</td>
</tr>
<tr class="even">
<td align="left">1956</td>
<td align="right">148</td>
<td align="right">170</td>
<td align="right">199</td>
<td align="right">242</td>
<td align="right">272</td>
<td align="right">293</td>
<td align="right">347</td>
<td align="right">405</td>
<td align="right">467</td>
<td align="right">505</td>
<td align="right">559</td>
<td align="right">606</td>
</tr>
<tr class="odd">
<td align="left">1957</td>
<td align="right">136</td>
<td align="right">158</td>
<td align="right">184</td>
<td align="right">209</td>
<td align="right">237</td>
<td align="right">259</td>
<td align="right">312</td>
<td align="right">355</td>
<td align="right">404</td>
<td align="right">404</td>
<td align="right">463</td>
<td align="right">508</td>
</tr>
<tr class="even">
<td align="left">1958</td>
<td align="right">119</td>
<td align="right">133</td>
<td align="right">162</td>
<td align="right">191</td>
<td align="right">211</td>
<td align="right">229</td>
<td align="right">274</td>
<td align="right">306</td>
<td align="right">347</td>
<td align="right">359</td>
<td align="right">407</td>
<td align="right">461</td>
</tr>
<tr class="odd">
<td align="left">1959</td>
<td align="right">104</td>
<td align="right">114</td>
<td align="right">146</td>
<td align="right">172</td>
<td align="right">180</td>
<td align="right">203</td>
<td align="right">237</td>
<td align="right">271</td>
<td align="right">305</td>
<td align="right">310</td>
<td align="right">362</td>
<td align="right">390</td>
</tr>
<tr class="even">
<td align="left">1960</td>
<td align="right">118</td>
<td align="right">140</td>
<td align="right">166</td>
<td align="right">194</td>
<td align="right">201</td>
<td align="right">229</td>
<td align="right">278</td>
<td align="right">306</td>
<td align="right">336</td>
<td align="right">337</td>
<td align="right">405</td>
<td align="right">432</td>
</tr>
</tbody>
</table>
<p>Il nostro primo compito è quello di comprendere e descrivere le caratteristiche fondamentali di ogni variabile, utilizzando statistiche descrittive opportunamente scelte, in base al tipo di dato e alle caratteristiche che si vogliono descrivere.</p>
<div id="descrizione-di-dati-quantitativi" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Descrizione di dati quantitativi<a href="richiami-di-statistica-descrittiva.html#descrizione-di-dati-quantitativi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se i dati sono stati ottenuti con un processo di misurazione e rappresentano una quantità, come, ad esempio, il peso, l’altezza, la concentrazione e così via, abbiamo una variabile quantitativa, della quale dobbiamo descrivere almeno due caratteristiche fondamentali:</p>
<ol style="list-style-type: decimal">
<li>tendenza centrale</li>
<li>dispersione</li>
</ol>
<p>La tendenza centrale è un valore che rappresenta il ‘centro’, attorno al quale si collocano tutte le osservazioni; al contrario, la dispersione misura la distanza delle osservazioni tra di loro, cioè, in altre parole, la loro variabilità. Ovviamente, esistono anche altre importanti proprietà di una variabile quantitativa, come la simmetria e la curtosi, anche se in questo capitolo ci accontenteremo di esaminare le più diffuse statistiche descrittive di tendenza centrale e dispersione.</p>
<div id="indicatori-di-tendenza-centrale" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Indicatori di tendenza centrale<a href="richiami-di-statistica-descrittiva.html#indicatori-di-tendenza-centrale" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>L’indicatore di tendenza centrale più diffuso è la <em>media</em> aritmetica, che non necessita di particolari spiegazioni: si tratta della somma dei dati (<span class="math inline">\(x\)</span>) divisa per il loro numero (<span class="math inline">\(n\)</span>):</p>
<p><span class="math display">\[\mu = \frac{\sum\limits_{i = 1}^n x}{n}\]</span></p>
<p>Per esempio, consideriamo il seguente dataset, che elenca le altezze di quattro piante di mais <span class="math inline">\(d = [178, 175, 158, 153]\)</span></p>
<p>Il calcolo della media è banale:</p>
<p><span class="math display">\[\mu = \frac{178 + 175 + 158 + 153}{4} = 166\]</span></p>
<p>La media è ‘centrale’ nel senso che la somma delle sue distanze da ogni altra osservazione è nulla. Di conseguenza, è molto sensibile ai valori estremi; se, ad esempio, supponiamo di avere i cinque valori: 1, 4, 7, 9 e 10 con media pari a 6,2 e supponiamo di sostituire il valore più alto con 100, la media aumenta di conseguenza, diventando pari a 24,2. Per questa sua sensibilità ai valori estremi, si dice che la media non è un indicatore di tendenza centrale ‘robusto’ nei confronti degli <em>outliers</em>, cioè delle osservazioni in qualche modo ‘aberranti’. In presenza di queste osservazioni, che potrebbero essere frutto di un errore sperimentale rilevante, la media tende a non rappresentare più la tendenza centrale del collettivo in modo affidabile.</p>
<p>Un altro indicatore di tendenza centrale è la <em>mediana</em>, cioè il valore che bipartisce i dati in modo che la metà di essi siano più alti e la metà più bassi. Per calcolare la mediana, basta ordinare i soggetti in ordine crescente: se il numero di individui è dispari, la mediana è data dal valore dall’individuo che occupa il posto centrale o, se gli individui sono in numero pari, dalla media delle due osservazioni centrali. Nell’esempio precedente, i dati sono in numero pari, quindi la mediana è: <span class="math inline">\((158 + 175)/2 = 166.5\)</span>.</p>
<p>La mediana è un indicatore più robusto della media: infatti, se consideriamo gli stessi cinque valori elencati in precedenza (1, 4, 7, 9 e 10), la mediana è pari a 7 e non cambia quando sostituiamo il valore più alto con 100.</p>
</div>
<div id="indicatori-di-dispersione" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Indicatori di dispersione<a href="richiami-di-statistica-descrittiva.html#indicatori-di-dispersione" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Conoscere la tendenza centrale di un collettivo è importante, ma non è sufficiente. Infatti, una media pari a 100 può essere ottenuta con tre individui che misurano 99, 100 e 101, rispettivamente, o con tre individui che misurano 1, 100 e 199. E’ evidente che i due gruppi hanno la stessa tendenza centrale, ma sono molto diversi in termini di dispersione (o variabilità) rispetto alla media. Per descrivere la dispersione dei dati possiamo utilizzare il <em>campo di variazione</em>, che è la differenza tra la misura più bassa e la misura più alta. In realtà, questo indicatore è poco diffuso, perché considera solo i valori estremi del collettivo e non necessariamente cresce al crescere della variabilità. Altri indicatori sono più diffusi ed affidabili, come la devianza, la varianza, la deviazione standard ed il coefficiente di variabilità, tutti legati da relazioni algebriche ben definite.</p>
<p>La <em>devianza</em>, generalmente nota come somma dei quadrati (abbreviata SS, da <em>sum of squares</em>) è data da:</p>
<p><span class="math display">\[SS = \sum\limits_{i = 1}^n {(x_i  - \mu)^2 }\]</span></p>
<p>Ad esempio, per le quattro altezze menzionate in precedenza, la devianza è pari a:</p>
<p><span class="math display">\[SS = \left(178 - 166 \right)^2 + \left(175 - 166 \right)^2 + \left(158 - 166 \right)^2  + \left(153 - 166 \right)^2 = 458\]</span></p>
<p>La devianza è un indicatore di dispersione molto utilizzato, soprattutto perché ha un suo preciso significato geometrico, in quanto somma delle distanze euclidee al quadrato, rispetto alla media. Tuttavia, ha due aspetti che vanno tenuti in considerazione: in primo luogo, proprio perché è una somma, il valore finale dipende dal numero di addendi e quindi non la si può utilizzare per confrontare la variabilità di collettivi con diversa numerosità. Inoltre, l’unità di misura della devianza è pari al quadrato dell’unità di misura originale dei dati; ad esempio se le osservazioni sono espresse in centimetri (come nel nostro esempio), la devianza è espressa in centimetri quadrati, il che rende più difficoltosa l’interpretazione dei risultati.</p>
<p>Oltre dalla devianza, un indicatore molto utilizzato è la <em>varianza campionaria</em> (o semplicemente <em>varianza</em>), che è data dalla devianza divisa per il numero di dati meno uno:</p>
<p><span class="math display">\[\sigma^2  = \frac{SS}{n - 1}\]</span></p>
<p>Nel caso delle nostre altezze:</p>
<p><span class="math display">\[\sigma^2  = \frac{458}{3} = 152.67\]</span></p>
<p>La varianza è anche detta scarto quadratico medio è permette di confrontare la variabilità di collettivi diversamente numerosi, anche se permane il problema dell’unità di misura, che è sempre il quadrato di quella delle singole osservazioni. Per eliminare questo problema si ricorre alla radice quadrata della varianza, cioè la <em>deviazione standard</em>, che si indica con <span class="math inline">\(\sigma\)</span>. La deviazione standard è espressa nella stessa unità di misura dei dati originali ed è quindi molto utilizzata per descrivere l’<em>incertezza assoluta</em> di misure ripetute più volte. Nel nostro caso, risulta che:</p>
<p><span class="math display">\[\sigma  = \sqrt{152.67} = 12.36\]</span></p>
<p>e questo valore ci fa capire che, ‘mediamente’, la distanza euclidea tra ogni valore e <span class="math inline">\(\mu\)</span> è pari <span class="math inline">\(12.36\)</span> centimetri. Media e deviazione standard sono spesso riportate contemporaneamente, utilizzando un intervallo <span class="math inline">\(l\)</span> definito come:</p>
<p><span class="math display">\[l = \mu \pm \sigma\]</span></p>
<p>Un problema della deviazione standard è che essa, in assenza della media, non riesce a dare informazioni facilmente comprensibili; infatti, se dicessimo semplicemente che un gruppo di individui ha una deviazione standard pari a <span class="math inline">\(12.36\)</span>, cosa potremmo concludere in relazione alla variabilità di questo collettivo? È alta o bassa? È evidente che, senza sapere la media, non riusciamo a rispondere a questa domanda: la variabilità potrebbe essere considerata molto alta se la media fosse bassa (ad esempio 16), oppure molto bassa, se la media fosse alta (esempio 1600). Per questo, se dovessimo descrivere la variabilità dei dati indipendentemente dalla media, dovremmo utilizzare il <em>coefficiente di variabilità</em> (CV):</p>
<p><span class="math display">\[CV = \frac{\sigma }{\mu } \times 100\]</span></p>
<p>Il CV è un numero puro e non dipende dall’unità di misura e dall’ampiezza del collettivo, sicché è molto adatto ad esprimere, ad esempio, l’errore degli strumenti di misura e delle apparecchiature di analisi (<strong>incertezza relativa</strong>). Nel nostro caso, abbiamo:</p>
<p><span class="math display">\[CV = \frac{12.36}{166} \times 100 = 7.45 \%\]</span></p>
<p>Come la media, anche la devianza, la varianza e la deviazione standard sono sensibili agli <em>outliers</em>. Pertanto, in presenza di osservazioni aberranti, preferiamo descrivere la variabilità del collettivo utilizzando i cosiddetti <em>percentili</em>, che, estendendo il concetto di mediana, bipartiscono il collettivo in modo da lasciare una certa percentuale di individui alla loro sinistra. Ad esempio, il primo percentile bipartisce il collettivo in modo che l’1% dei soggetti sono più bassi e il 99% sono più alti. Allo stesso modo, l’ottantesimo percentile bipartisce il collettivo in modo che l’80% dei soggetti sono più bassi e il 20% sono più alti. Ovviamente, la mediana rappresenta il 50-esimo percentile.</p>
<p>I percentili più utilizzati per descrivere la dispersione di un collettivo sono il 25-esimo e il 75-esimo, che individuano un intervallo all’interno del quale è compreso il 50% dei soggetti: se questo intervallo è piccolo, significa che la variabilità è bassa. Calcolare i percentili a mano non è banale e, di conseguenza, lo faremo nei paragrafi successivi, utilizzando R.</p>
</div>
<div id="incertezza-delle-misure-derivate" class="section level3 hasAnchor" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Incertezza delle misure derivate<a href="richiami-di-statistica-descrittiva.html#incertezza-delle-misure-derivate" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A volte noi misuriamo due quantità e poi le combiniamo, per ottenere una misura derivata, ad esempio la somma o la differenza. Se le due misure hanno un certo grado di incertezza, quantificabile, ad esempio, con la deviazione standard, qual è l’incertezza della loro somma o della loro differenza? La legge di propagazione degli errori dice che, in caso di misure indipendenti, <strong>la deviazione standard di una somma o di una differenza è uguale alla radice quadrata della somma dei quadrati delle deviazioni standard degli addendi</strong>. Ad esempio, se abbiamo fatto due misure indipendenti in triplicato, ottenendo le due medie <span class="math inline">\(22\)</span> e <span class="math inline">\(14\)</span>, con deviazioni standard rispettivamente pari a <span class="math inline">\(2\)</span> e <span class="math inline">\(3\)</span>, la somma sarà pari a <span class="math inline">\(36\)</span>, con deviazione standard pari <span class="math inline">\(\sqrt{2^2 + 3^2} = 3.6\)</span>, mentre la differenza sarà pari ad <span class="math inline">\(8\)</span> con deviazione standard comunque pari a <span class="math inline">\(3.6\)</span>. Ovviamente è anche possibile calcolare la deviazione standard di misure derivate con funzioni diverse dalla somma o dalla differenza, ma si tratta di una situazione meno comune, che non tratteremo in questo libro.</p>
</div>
<div id="relazioni-tra-variabili-quantitative-correlazione" class="section level3 hasAnchor" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Relazioni tra variabili quantitative: correlazione<a href="richiami-di-statistica-descrittiva.html#relazioni-tra-variabili-quantitative-correlazione" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se su ogni soggetto abbiamo rilevato due caratteri quantitativi (ad esempio il peso e l’altezza, oppure la produzione e il contenuto di proteina della granella), è possibile verificare se esista una relazione tra la coppia di variabili ottenute, cioè se al variare di una cambi anche il valore dell’altra, in modo congiunto (variazione congiunta).</p>
<p>Per questo fine, si utilizza il <em>coefficiente di correlazione di Pearson</em> costituito dal rapporto tra la codevianza (o somma dei prodotti) delle due variabili e la radice quadrata del prodotto delle loro devianze. Vedremo tra poco il metodo di calcolo, ma vogliamo anticipare che il coefficiente di correlazione varia tra <span class="math inline">\(-1\)</span> e <span class="math inline">\(+1\)</span>; se è pari ad 1, abbiamo una situazione ideale di concordanza perfetta (quando aumenta una variabile, aumenta anche l’altra in modo esattamente proporzionale), mentre quando è pari a <span class="math inline">\(-1\)</span>, abbiamo una situazione ideale di discordanza perfetta (quando aumenta una variabile, diminuisce l’altra in modo inversamente proporzionale). Un valore pari a <span class="math inline">\(0\)</span> è altrettanto ideal ed indica assenza di qualunque grado di variazione congiunta (assenza di correlazione). Nell’intervallo tra <span class="math inline">\(-1\)</span> ed <span class="math inline">\(1\)</span>, il coefficiente indica una correlazione imperfetta, ma tanto migliore quanto più ci allontaniamo dallo zero e ci avviciniamo a <span class="math inline">\(-1\)</span> o <span class="math inline">\(1\)</span>. Due esempi di ottima correlazione sono mostrati in Figura <a href="richiami-di-statistica-descrittiva.html#fig:figName311">3.1</a>; si evidenzia un elevato grado di correlazione, che, tuttavia, non è perfetta, in quanto i punti non sono esattamente allineati.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figName311"></span>
<img src="_images/CorrelationExample.png" alt="Esempio di correlazione positiva (destra) e negativa (sinistra)" width="75%" />
<p class="caption">
Figura 3.1: Esempio di correlazione positiva (destra) e negativa (sinistra)
</p>
</div>
<p>Proviamo a considerare questo esempio: il contenuto di olio di 9 lotti di acheni di girasole è stato misurato con due metodi diversi ed è riportato più sotto.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="richiami-di-statistica-descrittiva.html#cb1-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">47</span>, <span class="dv">49</span>, <span class="dv">51</span>, <span class="dv">44</span>, <span class="dv">37</span>, <span class="dv">48</span>, <span class="dv">44</span>, <span class="dv">53</span>)</span>
<span id="cb1-2"><a href="richiami-di-statistica-descrittiva.html#cb1-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">44</span>, <span class="dv">44</span>, <span class="dv">49</span>, <span class="dv">53</span>, <span class="dv">48</span>, <span class="dv">34</span>, <span class="dv">47</span>, <span class="dv">46</span>, <span class="dv">51</span>)</span></code></pre></div>
<p>Per valutare la entità della correlazione tra i risultati dei due metodi di analisi, dobbiamo eseguire alcune operazioni preliminari, cioè:</p>
<ol style="list-style-type: decimal">
<li>calcolare i residui per A (<span class="math inline">\(z_A\)</span>)</li>
<li>calcolare i residui per B (<span class="math inline">\(z_B\)</span>)</li>
<li>calcolare devianze e codevianze</li>
</ol>
<p>In primo luogo, calcoliamo le due medie, che sono, rispettivamente, 46.44 e 46.22. Successivamente, possiamo calcolare i residui, come differenze tra ogni dato e la sua media, i loro quadrati ed i loro prodotti, come indicato in Tabella <a href="richiami-di-statistica-descrittiva.html#tab:tabName3">3.2</a>.</p>
<pre><code>##    A  B   scarti.a    scarti.b prod.scarti scarti.a2    scarti.b2
## 1 45 44 -1.4444444  -2.2222222   3.2098765  2.086420   4.93827160
## 2 47 44  0.5555556  -2.2222222  -1.2345679  0.308642   4.93827160
## 3 49 49  2.5555556   2.7777778   7.0987654  6.530864   7.71604938
## 4 51 53  4.5555556   6.7777778  30.8765432 20.753086  45.93827160
## 5 44 48 -2.4444444   1.7777778  -4.3456790  5.975309   3.16049383
## 6 37 34 -9.4444444 -12.2222222 115.4320988 89.197531 149.38271605
## 7 48 47  1.5555556   0.7777778   1.2098765  2.419753   0.60493827
## 8 44 46 -2.4444444  -0.2222222   0.5432099  5.975309   0.04938272
## 9 53 51  6.5555556   4.7777778  31.3209877 42.975309  22.82716049</code></pre>
<table>
<caption><span id="tab:tabName3">Tabella 3.2: </span>Calcolo manuale del coefficiente di correlazione</caption>
<thead>
<tr class="header">
<th align="right">A</th>
<th align="right">B</th>
<th align="right"><span class="math inline">\(z_A\)</span></th>
<th align="right"><span class="math inline">\(z_B\)</span></th>
<th align="right"><span class="math inline">\(z_A \times z_B\)</span></th>
<th align="right"><span class="math inline">\(z_A^2\)</span></th>
<th align="right"><span class="math inline">\(z_B^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">45</td>
<td align="right">44</td>
<td align="right">-1.444</td>
<td align="right">-2.222</td>
<td align="right">3.210</td>
<td align="right">2.086</td>
<td align="right">4.938</td>
</tr>
<tr class="even">
<td align="right">47</td>
<td align="right">44</td>
<td align="right">0.556</td>
<td align="right">-2.222</td>
<td align="right">-1.235</td>
<td align="right">0.309</td>
<td align="right">4.938</td>
</tr>
<tr class="odd">
<td align="right">49</td>
<td align="right">49</td>
<td align="right">2.556</td>
<td align="right">2.778</td>
<td align="right">7.099</td>
<td align="right">6.531</td>
<td align="right">7.716</td>
</tr>
<tr class="even">
<td align="right">51</td>
<td align="right">53</td>
<td align="right">4.556</td>
<td align="right">6.778</td>
<td align="right">30.877</td>
<td align="right">20.753</td>
<td align="right">45.938</td>
</tr>
<tr class="odd">
<td align="right">44</td>
<td align="right">48</td>
<td align="right">-2.444</td>
<td align="right">1.778</td>
<td align="right">-4.346</td>
<td align="right">5.975</td>
<td align="right">3.160</td>
</tr>
<tr class="even">
<td align="right">37</td>
<td align="right">34</td>
<td align="right">-9.444</td>
<td align="right">-12.222</td>
<td align="right">115.432</td>
<td align="right">89.198</td>
<td align="right">149.383</td>
</tr>
<tr class="odd">
<td align="right">48</td>
<td align="right">47</td>
<td align="right">1.556</td>
<td align="right">0.778</td>
<td align="right">1.210</td>
<td align="right">2.420</td>
<td align="right">0.605</td>
</tr>
<tr class="even">
<td align="right">44</td>
<td align="right">46</td>
<td align="right">-2.444</td>
<td align="right">-0.222</td>
<td align="right">0.543</td>
<td align="right">5.975</td>
<td align="right">0.049</td>
</tr>
<tr class="odd">
<td align="right">53</td>
<td align="right">51</td>
<td align="right">6.556</td>
<td align="right">4.778</td>
<td align="right">31.321</td>
<td align="right">42.975</td>
<td align="right">22.827</td>
</tr>
</tbody>
</table>
<p>La somma dei quadrati dei residui ci permette di calcolare le devianze di <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> (rispettivamente 176.22 e 239.56), mentre la somme dei prodotti degli residui ci permette di calcolare la codevianza (pari a 184.11).</p>
<p>Il coefficiente di correlazione è quindi:</p>
<p><span class="math display">\[r = \frac{184.11}{\sqrt{176.22 \times 239.56}} = 0.896\]</span></p>
<p>Vediamo che il coefficiente di correlazione è abbastanza vicino ad 1 e quindi possiamo concludere che i due metodi di analisi danno risultati ben concordanti.</p>
</div>
</div>
<div id="descrizione-di-dati-qualitativi" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Descrizione di dati qualitativi<a href="richiami-di-statistica-descrittiva.html#descrizione-di-dati-qualitativi" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nel capitolo 2 abbiamo visto che le variabili qualitative sono ottenute assegnando ogni soggetto di un collettivo ad una classe scelta tra due o più possibili opzioni. Al termine di questo processo di classificazione, di solito calcoliamo le <em>frequenza assolute</em>, cioè il numero di individui assegnato ad ogni classe. Ad esempio, se abbiamo esaminato 500 insetti rilevando l’ordine a cui appartengono, le frequenze assolute potrebbero essere: 100 ditteri, 200 imenotteri e 150 ortotteri.</p>
<p>Oltre alle frequenze assolute, possiamo calcolare anche le <em>frequenze relative</em>, dividendo le frequenze assolute per il numero totale degli individui del collettivo. Nel caso precedentemente menzionato, la frequenza relativa dei ditteri è pari a <span class="math inline">\(100/500 = 0.2\)</span>.</p>
<p>Se le classi possono essere logicamente ordinate, oltre alle frequenze assolute e relative, possiamo calcolare anche le cosiddette <em>frequenze cumulate</em>, che si ottengono cumulando le frequenze relative di una classe con quelle di tutte le classi precedenti.</p>
<div id="distribuzioni-di-frequenze-e-classamento" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Distribuzioni di frequenze e classamento<a href="richiami-di-statistica-descrittiva.html#distribuzioni-di-frequenze-e-classamento" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Quando rappresentiamo, in un grafico o in una tabella, le frequenze (assolute, relative o cumulate) per tutte le classi e tutti gli individui del collettivo, otteniamo una <em>distribuzione di frequenze</em>.</p>
<p>Ad esempio, se consideriamo il famoso database ‘mtcars’, relativo alle 32 auto storiche censite dalla rivista Motor Trends nel 1974, e analizziamo il numero delle marce, otteniamo la seguente distribuzione di frequenze assolute, relative e cumulate.</p>
<table>
<thead>
<tr class="header">
<th align="right">Marce</th>
<th align="right">Freq.Ass</th>
<th align="right">Freq.Rel</th>
<th align="right">Freq.Cum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">3</td>
<td align="right">15</td>
<td align="right">0.47</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">12</td>
<td align="right">0.38</td>
<td align="right">0.84</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">5</td>
<td align="right">0.16</td>
<td align="right">1.00</td>
</tr>
</tbody>
</table>
<p>Le distribuzioni di frequenze possono essere costruite anche per le variabili quantitative, tramite un’operazione di <em>classamento</em>, che consiste nel suddividere il campo di variazione dei dati in una serie di intervalli (esempio, da 10 a 20, da 20 a 40 e così via) e contare i soggetti in ogni classe. In questo modo, se le osservazioni sono molto numerose, la lettura delle informazioni risulta più semplice e più completa che non elencando tutti i valori o, d’altra parte, riportando solo la loro media e la loro deviazione standard. Daremo un esempio di questa tecnica in un paragrafo successivo.</p>
</div>
<div id="statistiche-descrittive-per-le-distribuzioni-di-frequenze" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Statistiche descrittive per le distribuzioni di frequenze<a href="richiami-di-statistica-descrittiva.html#statistiche-descrittive-per-le-distribuzioni-di-frequenze" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Per una distribuzione di frequenze, il più semplice indicatore di tendenza centrale è la <em>moda</em>, cioè il valore della classe che presenta la maggior frequenza. Ovviamente, se la variabile è quantitativa ed è stata sottoposta a classamento, si considera come moda il punto centrale della classe con maggior frequenza. L’individuazione della moda è banale e non richiede calcoli di sorta.</p>
<p>In alcune condizioni (distribuzioni di frequenze per caratteri qualitativi ordinabili o quantitativi sottoposti a classamento), oltre alla moda possiamo calcolare la <em>mediana</em> e gli altri percentili, nonché la media e le altre statistiche descrittive indicate per i caratteri quantitativi. Tuttavia, si tratta di una situazione più tipica delle scienze economiche e sociali che non delle scienze agrarie e biologiche e, per questo motivo, non la prenderemo in ulteriore considerazione.</p>
</div>
<div id="distribuzioni-di-frequenza-bivariate-le-tabelle-di-contingenze" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Distribuzioni di frequenza bivariate: le tabelle di contingenze<a href="richiami-di-statistica-descrittiva.html#distribuzioni-di-frequenza-bivariate-le-tabelle-di-contingenze" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In alcuni casi, in ciascuna unità sperimentale del collettivo vengono studiati due (o più) caratteri qualitativi, che possiamo rappresentare in una <em>tabella di contingenze</em>. Si tratta di tabelle a due (o più) entrate, nelle quali ogni valore rappresenta la frequenza assoluta per una particolare combinazione dei caratteri rilevati.</p>
<p>Ad esempio, potremmo aver valutato la germinabilità di cariossidi di frumento sottoposte a due tipi di illuminazione, rossa o blu. Per ogni cariosside abbiamo quindi due informazioni, il trattamento a cui è stata sottoposta (luce rossa o blu) e se è germinata oppure no, per un totale di quattro possibili combinazioni (Rosso-si, Rosso-no, Blu-si, Blu-no). Supponendo di aver osservato 95 cariossidi germinate su 110 testate con luce rossa e 67 germinate su 120 testate con luce blu, possiamo definire la tabella di contingenze riportata di seguito.</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">SI</th>
<th align="right">NO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ROSSO</td>
<td align="right">95</td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left">BLU</td>
<td align="right">67</td>
<td align="right">53</td>
</tr>
</tbody>
</table>
<p>Ogni riga della tabella sovrastante costituisce una distribuzione di frequenze per la germinabilità, data una certa tipologia di luce (distribuzione di frequenze condizionate).</p>
</div>
<div id="connessione" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Connessione<a href="richiami-di-statistica-descrittiva.html#connessione" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se guardiamo le due distribuzioni condizionate per la luce rossa e blu, possiamo notare che esiste una certa differenza e che la germinabilità pare maggiore con luce rossa. Potremmo chiederci quindi se una certa modalità del carattere luce (rossa o blue) influenzi il presentarsi di una particolare modalità del carattere germinabilità (si o no). Se così fosse, potremmo parlare di dipendenza o connessione, mentre, nel caso contrario, si dovrebbe parlare di indipendenza dei caratteri.</p>
<p>Come si fa a stabilire se i caratteri sono indipendenti o connessi? Il punto di partenza è pensare che, se i caratteri fossero indipendenti, la germinabilità dovrebbe essere la stessa con entrambi i trattamenti; in totale, abbiamo osservato 230 semi, di cui 162 sono germinati e 68 non lo sono e, di conseguenza, la proporzione di semi germinati è stata pari a 162/230 = 0.704. Ebbene, questa proporzione la si dovrebbe riscontrare con entrambi i trattamenti. In cifre, il numero di semi germinati con luce rossa dovrebbe essere pari a <span class="math inline">\(110 \times 0.704 = 77.44\)</span>, mentre il numero di semi germinati con luce blu dovrebbe essere pari a <span class="math inline">\(120 \times 0.704 = 84.48\)</span>. Rispettando i totali marginali (cioè il numero totale di semi saggiati con luce rossa e blu dovrebbe essere pari, rispettivamente a 110 e 120), possiamo costruire la tabella delle frequenze assolute attese, nell’ipotesi di indipendenza completa tra i due caratteri.</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">SI</th>
<th align="right">NO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ROSSO</td>
<td align="right">77.44</td>
<td align="right">32.56</td>
</tr>
<tr class="even">
<td align="left">BLU</td>
<td align="right">84.48</td>
<td align="right">35.52</td>
</tr>
</tbody>
</table>
<p>A questo punto possiamo costruire un indice statistico di connessione, detto <span class="math inline">\(\chi^2\)</span>, che misuri la discrepanzatra le due tabelle, quella delle frequenze osservate e quella delle frequenze teoriche che si sarebbero dovute osservare nell’ipotesi di indipendenza perfetta:</p>
<p><span class="math display">\[\chi ^2  = \sum \left[ \frac{\left( {f_o  - f_a } \right)^2 }{f_a } \right]\]</span></p>
<p>dove <span class="math inline">\(f_o\)</span> sta per frequenza osservata ed <span class="math inline">\(f_a\)</span> sta per frequenza attesa nel caso indipendenza. Questo indice assume valore pari a zero nel caso di indipendenza completa (le frequenze osservate sono uguali a quelle attese) ed assume un valore positivo tanto più alto quanto maggiore è la connessione tra i due caratteri.</p>
<p>Nel nostro esempio:</p>
<p><span class="math display">\[\chi^2  = \frac{\left( {95  - 77.44 } \right)^2 }{77.44 } + \frac{\left( {15  - 32.56 } \right)^2 }{32.56 } + \frac{\left( {67  - 84.48 } \right)^2 }{84.48 } + \frac{\left( {53  - 35.52 } \right)^2 }{35.52 } = 25.67\]</span></p>
<p>Se i caratteri fossero veramente indipendenti, la tabella delle frequenze osservate dovrebbe essere uguale a quella delle frequenze atteso, il che implicherebbe <span class="math inline">\(\chi^2 = 0\)</span>. Il valore da noi osservato è maggiore di 0 e quindi possiamo dire che esiste un certo grado di connessione, ma non sappiamo dire quanto questa sia elevata. Qual è il <span class="math inline">\(\chi^2\)</span> massimo possibile?</p>
<p>Intuitivamente, possiamo immaginare che la connessione potrebbe essere la più elevata possibile quando con uno dei due trattamenti i semi sono tutti germinati, mentre con l’altro non ne è germinato nessuno, come indicato nella tabella seguente:</p>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">SI</th>
<th align="right">NO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ROSSO</td>
<td align="right">110</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">BLU</td>
<td align="right">0</td>
<td align="right">120</td>
</tr>
</tbody>
</table>
<p>Se calcoliamo il valore di <span class="math inline">\(\chi^2\)</span> per la tabella sovrastante otteniamo 230, che è appunto il massimo valore possibile nella nostra condizione. Più in generale, il <span class="math inline">\(\chi^2\)</span> massimo è dato dal prodotto del numero degli individui per il valore minimo tra il numero di righe meno una e il numero di colonne meno una:</p>
<p><span class="math display">\[\max \chi ^2  = n \cdot \min (r - 1,\,c - 1)\]</span></p>
<p>Possiamo concludere che la connessione tra i due caratteri è pari all’11% circa di quello massima (<span class="math inline">\(25.67/230 = 0.112\)</span>).</p>
</div>
</div>
<div id="statistiche-descrittive-con-r" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Statistiche descrittive con R<a href="richiami-di-statistica-descrittiva.html#statistiche-descrittive-con-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Le statistiche descrittive si calcolano facilmente con R. Per esercizio, utilizziamo il dataset ‘heights.csv’, che è disponibile in una repository online. Il box sottostante mostra come caricare il dataset, del quale utilizzeremo la colonna ‘height’ che riporta le altezze di venti piante di mais.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="richiami-di-statistica-descrittiva.html#cb3-1" aria-hidden="true" tabindex="-1"></a>filePath <span class="ot">&lt;-</span> <span class="st">&quot;https://www.casaonofri.it/_datasets/heights.csv&quot;</span></span>
<span id="cb3-2"><a href="richiami-di-statistica-descrittiva.html#cb3-2" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(filePath, <span class="at">header =</span> T)</span>
<span id="cb3-3"><a href="richiami-di-statistica-descrittiva.html#cb3-3" aria-hidden="true" tabindex="-1"></a>dataset<span class="sc">$</span>height</span>
<span id="cb3-4"><a href="richiami-di-statistica-descrittiva.html#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="do">##  [1] 172 154 150 188 162 145 157 178 175 158 153 191 174 141 165 163</span></span>
<span id="cb3-5"><a href="richiami-di-statistica-descrittiva.html#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [17] 148 152 169 185</span></span></code></pre></div>
<p>La media si calcola con la funzione <code>mean()</code>, mentre la mediana si calcola con la funzione <code>median()</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="richiami-di-statistica-descrittiva.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(dataset<span class="sc">$</span>height)</span>
<span id="cb4-2"><a href="richiami-di-statistica-descrittiva.html#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 164</span></span>
<span id="cb4-3"><a href="richiami-di-statistica-descrittiva.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(dataset<span class="sc">$</span>height)</span>
<span id="cb4-4"><a href="richiami-di-statistica-descrittiva.html#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 162.5</span></span></code></pre></div>
<p>Per la devianza, non esiste una funzione dedicata e dobbiamo utilizzare l’equazione fornita in precedenza:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="richiami-di-statistica-descrittiva.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( (dataset<span class="sc">$</span>height <span class="sc">-</span> <span class="fu">mean</span>(dataset<span class="sc">$</span>height))<span class="sc">^</span><span class="dv">2</span> )</span>
<span id="cb5-2"><a href="richiami-di-statistica-descrittiva.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 4050</span></span></code></pre></div>
<p>Varianza e deviazione standard sono molto facili da calcolare, grazie alle funzioni apposite, mentre il coefficiente di variabilità si può calcolare con la formula fornita in precedenza:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="richiami-di-statistica-descrittiva.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(dataset<span class="sc">$</span>height)</span>
<span id="cb6-2"><a href="richiami-di-statistica-descrittiva.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 213.1579</span></span>
<span id="cb6-3"><a href="richiami-di-statistica-descrittiva.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(dataset<span class="sc">$</span>height)</span>
<span id="cb6-4"><a href="richiami-di-statistica-descrittiva.html#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 14.59993</span></span>
<span id="cb6-5"><a href="richiami-di-statistica-descrittiva.html#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(dataset<span class="sc">$</span>height)<span class="sc">/</span><span class="fu">mean</span>(dataset<span class="sc">$</span>height) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb6-6"><a href="richiami-di-statistica-descrittiva.html#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 8.902395</span></span></code></pre></div>
<p>Per calcolare i percentili si usa la funzione <code>quantile()</code>, fornendo le proporzioni di soggetti da lasciare sulla sinistra con l’argomento ‘probs’. Ad esempio, per il 25-esimo percentile utilizzeremo 0.25, mentre per il 75-esimo utilizzeremo 0.75:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="richiami-di-statistica-descrittiva.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(dataset<span class="sc">$</span>height, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>))</span>
<span id="cb7-2"><a href="richiami-di-statistica-descrittiva.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="do">##    25%    75% </span></span>
<span id="cb7-3"><a href="richiami-di-statistica-descrittiva.html#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="do">## 152.75 174.25</span></span></code></pre></div>
<p>La correlazione si calcola invece con la funzione <code>cor()</code>, come indicato più sotto.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="richiami-di-statistica-descrittiva.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(A, B)</span>
<span id="cb8-2"><a href="richiami-di-statistica-descrittiva.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 0.8960795</span></span></code></pre></div>
<div id="descrizione-dei-sottogruppi" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Descrizione dei sottogruppi<a href="richiami-di-statistica-descrittiva.html#descrizione-dei-sottogruppi" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In biometria è molto comune che il gruppo di soggetti sia divisibile in più sottogruppi, corrispondenti, ad esempio, ai diversi trattamenti sperimentali. In questa comune situazione siamo soliti calcolare, per ogni gruppo, le statistiche descrittive già viste in precedenza, utilizzando la funzione <code>tapply()</code> in R, come mostrata più sotto.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="richiami-di-statistica-descrittiva.html#cb9-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dataset<span class="sc">$</span>height, dataset<span class="sc">$</span>var, mean)</span>
<span id="cb9-2"><a href="richiami-di-statistica-descrittiva.html#cb9-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dataset<span class="sc">$</span>height, dataset<span class="sc">$</span>var, sd)</span>
<span id="cb9-3"><a href="richiami-di-statistica-descrittiva.html#cb9-3" aria-hidden="true" tabindex="-1"></a>descript <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Media =</span> m, <span class="at">SD =</span> s)</span>
<span id="cb9-4"><a href="richiami-di-statistica-descrittiva.html#cb9-4" aria-hidden="true" tabindex="-1"></a>descript</span>
<span id="cb9-5"><a href="richiami-di-statistica-descrittiva.html#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="do">##    Media       SD</span></span>
<span id="cb9-6"><a href="richiami-di-statistica-descrittiva.html#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="do">## C 165.00 14.36431</span></span>
<span id="cb9-7"><a href="richiami-di-statistica-descrittiva.html#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="do">## N 164.00 16.19877</span></span>
<span id="cb9-8"><a href="richiami-di-statistica-descrittiva.html#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="do">## S 160.00 12.16553</span></span>
<span id="cb9-9"><a href="richiami-di-statistica-descrittiva.html#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="do">## V 165.25 19.51709</span></span></code></pre></div>
<p>Nel codice immediatamente precedente, <code>height</code> è la variabile che contiene i valori da mediare, <code>var</code> è la variabile che contiene la codifica di gruppo, <code>mean</code> è la funzione che dobbiamo calcolare. Ovviamente <code>mean</code> può essere sostituito da qualunque altra funzione ammissibile in R, come ad esempio la deviazione standard. Nel codice precedente abbiamo utilizzato la funzione <code>data.frame()</code> per creare una tabella riassuntiva con le medie e le deviazioni standard dei quattro gruppi.</p>
<p>Oltre che in una tabella, i risultati possono anche essere riportati in un grafico a barre, con l’indicazione della variabilità dei dati. Possiamo utilizzare la funzione <code>barplot()</code> alla quale passeremo come argomenti l’altezza delle barre, data dalle medie dei diversi gruppi, i nomi dei gruppi medesimi e, opzionalmente, la scala dell’asse delle ordinate. La funzione <code>barplot()</code>, oltre che creare il grafico, restituisce le ascisse del centro di ogni barra, che possiamo utilizzare per creare dei segmenti verticali corrispondenti alle deviazioni standard di ogni gruppo, attraverso la funzione <code>arrows()</code>.</p>
<p>L’uso di quest’ultima funzione non è immediato; poniamo che le ascisse del centro di ogni barra siano contenute nel vettore ‘coord’; allora i segmenti di variabilità dovranno avere punti di partenza con ascisse contenute in ‘coord’ ed ordinate uguali all’altezza di ogni barra meno la deviazione standard. I punti di arrivo, invece, dovranno avere le stesse ascisse dei punti di partenza ed ordinate uguali all’altezza di ogni barra più la deviazione standard. Gli altri argomenti della funzione <code>arrows()</code> servono per meglio specificare l’aspetto dei segmenti di variabilità; ad esempio, il codice sottostante produce il risultato mostrato in Figura <a href="richiami-di-statistica-descrittiva.html#fig:figName242">3.2</a>; il grafico non è bellissimo, ma, con un po’ di esercizio, è possibile ottenere grafici altamente professionali.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="richiami-di-statistica-descrittiva.html#cb10-1" aria-hidden="true" tabindex="-1"></a>coord <span class="ot">&lt;-</span> <span class="fu">barplot</span>(descript<span class="sc">$</span>Media, <span class="at">names.arg =</span> <span class="fu">row.names</span>(descript), </span>
<span id="cb10-2"><a href="richiami-di-statistica-descrittiva.html#cb10-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">200</span>))</span>
<span id="cb10-3"><a href="richiami-di-statistica-descrittiva.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(coord, descript<span class="sc">$</span>Media <span class="sc">-</span> descript<span class="sc">$</span>SD, </span>
<span id="cb10-4"><a href="richiami-di-statistica-descrittiva.html#cb10-4" aria-hidden="true" tabindex="-1"></a>       coord, descript<span class="sc">$</span>Media <span class="sc">+</span> descript<span class="sc">$</span>SD, </span>
<span id="cb10-5"><a href="richiami-di-statistica-descrittiva.html#cb10-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">length =</span> <span class="fl">0.05</span>, <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">code =</span> <span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figName242"></span>
<img src="_main_files/figure-html/figName242-1.png" alt="Esempio di boxplot in R" width="90%" />
<p class="caption">
Figura 3.2: Esempio di boxplot in R
</p>
</div>
<p>Quando abbiamo a che fare con gruppi molto numerosi, con un certo numero di outliers, è bene sostituire la mediana alla media, in associazione con il 25-esimo e 75-esimo percentile, come indicazioni di variabilità. Da un punto di vista grafico, possiamo utilizzare un <em>boxplot</em> (grafico Box-Whisker). Si tratta di una scatola (box) che ha per estremi il 25-esimo e il 75-esimo percentile ed è tagliata da una linea centrale in corrispondenza della mediana. Dalla scatola partono due linee verticali (baffi = whiskers) che identificano il valore massimo e il minimo. Se il massimo (o il minimo) distano dalla mediana più di 1.5 volte la differenza tra la mediana stessa e il 75-esimo (o 25-esimo) percentile, allora le linee verticali si fermano ad un valore pari ad 1.5 volte il 75-esimo (o il 25-esimo) percentile ed i dati più estremi vengono considerati outliers e rappresentati con un piccolo cerchio. In Figura <a href="richiami-di-statistica-descrittiva.html#fig:figName241">3.3</a> abbiamo raprresentato tre gruppi di valori estratti casualmente nell’intervallo da 0 ad 1.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="richiami-di-statistica-descrittiva.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb11-2"><a href="richiami-di-statistica-descrittiva.html#cb11-2" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>)</span>
<span id="cb11-3"><a href="richiami-di-statistica-descrittiva.html#cb11-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>)</span>
<span id="cb11-4"><a href="richiami-di-statistica-descrittiva.html#cb11-4" aria-hidden="true" tabindex="-1"></a>C <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>)</span>
<span id="cb11-5"><a href="richiami-di-statistica-descrittiva.html#cb11-5" aria-hidden="true" tabindex="-1"></a>series <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>), <span class="at">each =</span> <span class="dv">20</span>)</span>
<span id="cb11-6"><a href="richiami-di-statistica-descrittiva.html#cb11-6" aria-hidden="true" tabindex="-1"></a>values <span class="ot">&lt;-</span> <span class="fu">c</span>(A, B, C)</span>
<span id="cb11-7"><a href="richiami-di-statistica-descrittiva.html#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(values <span class="sc">~</span> series)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figName241"></span>
<img src="_main_files/figure-html/figName241-1.png" alt="Esempio di boxplot in R" width="90%" />
<p class="caption">
Figura 3.3: Esempio di boxplot in R
</p>
</div>
</div>
<div id="distribuzioni-di-frequenze-e-classamento-1" class="section level3 hasAnchor" number="3.3.2">
<h3><span class="header-section-number">3.3.2</span> Distribuzioni di frequenze e classamento<a href="richiami-di-statistica-descrittiva.html#distribuzioni-di-frequenze-e-classamento-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Utilizziamo il dataset ‘mtcars’ disponibile nell’installazione di gbase di R, che possiamo caricare utilizzando la funzione <code>data()</code>.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="richiami-di-statistica-descrittiva.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span></code></pre></div>
<p>In questo dataset, la variabile ‘gear’ indica il numero di marce e le frequenze assolute possono essere ottenute con la funzione <code>table()</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="richiami-di-statistica-descrittiva.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequenze assolute</span></span>
<span id="cb13-2"><a href="richiami-di-statistica-descrittiva.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mtcars<span class="sc">$</span>gear)</span>
<span id="cb13-3"><a href="richiami-di-statistica-descrittiva.html#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb13-4"><a href="richiami-di-statistica-descrittiva.html#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="do">##  3  4  5 </span></span>
<span id="cb13-5"><a href="richiami-di-statistica-descrittiva.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="do">## 15 12  5</span></span></code></pre></div>
<p>Per le frequenze relative e percentuali, possiamo combinare il codice soprastante con l’impiego della funzione <code>length()</code>, che restituisce il numero di elementi in un vettore.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="richiami-di-statistica-descrittiva.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Frequenze relative</span></span>
<span id="cb14-2"><a href="richiami-di-statistica-descrittiva.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mtcars<span class="sc">$</span>gear)<span class="sc">/</span><span class="fu">length</span>(mtcars<span class="sc">$</span>gear)</span>
<span id="cb14-3"><a href="richiami-di-statistica-descrittiva.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb14-4"><a href="richiami-di-statistica-descrittiva.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="do">##       3       4       5 </span></span>
<span id="cb14-5"><a href="richiami-di-statistica-descrittiva.html#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="do">## 0.46875 0.37500 0.15625</span></span>
<span id="cb14-6"><a href="richiami-di-statistica-descrittiva.html#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Frequenze percentuali</span></span>
<span id="cb14-7"><a href="richiami-di-statistica-descrittiva.html#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(mtcars<span class="sc">$</span>gear)<span class="sc">/</span><span class="fu">length</span>(mtcars<span class="sc">$</span>gear) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb14-8"><a href="richiami-di-statistica-descrittiva.html#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb14-9"><a href="richiami-di-statistica-descrittiva.html#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="do">##      3      4      5 </span></span>
<span id="cb14-10"><a href="richiami-di-statistica-descrittiva.html#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="do">## 46.875 37.500 15.625</span></span></code></pre></div>
<p>Mostriamo ora l’operazione di classamento di una variabile quantitativa, che tornerà utile nei prossimi capitoli. Prendiamo con R mille valori casuali da una distribuzione uniforme nell’intervallo da 130 a 200 ed esprimiamo questi mille valori tramite una distribuzione di frequenze nelle sei classi: &lt;140, 140-150, 150-160, 160-170, 170-190, &gt;190. Per il classamento si utilizza la funzione <code>cut()</code>, che con l’argomento <code>breaks()</code> consente di specificare gli estremi inferiori delle classi, inclusi per default nella classe precedente (intervalli aperti a destra e chiusi a sinistra).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="richiami-di-statistica-descrittiva.html#cb15-1" aria-hidden="true" tabindex="-1"></a>vals <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1000</span>, <span class="at">min =</span> <span class="dv">130</span>, <span class="at">max =</span> <span class="dv">200</span>)</span>
<span id="cb15-2"><a href="richiami-di-statistica-descrittiva.html#cb15-2" aria-hidden="true" tabindex="-1"></a>freq <span class="ot">&lt;-</span> <span class="fu">table</span>( <span class="fu">cut</span>(vals, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">140</span>,<span class="dv">150</span>,<span class="dv">160</span>,<span class="dv">170</span>,<span class="dv">190</span>,<span class="dv">200</span>)) )</span>
<span id="cb15-3"><a href="richiami-di-statistica-descrittiva.html#cb15-3" aria-hidden="true" tabindex="-1"></a>freq</span>
<span id="cb15-4"><a href="richiami-di-statistica-descrittiva.html#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb15-5"><a href="richiami-di-statistica-descrittiva.html#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="do">## (100,140] (140,150] (150,160] (160,170] (170,190] (190,200] </span></span>
<span id="cb15-6"><a href="richiami-di-statistica-descrittiva.html#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="do">##       141       135       143       139       282       160</span></span></code></pre></div>
<p>Per le frequenze cumulate si usa invece la funzione <code>cumsum()</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="richiami-di-statistica-descrittiva.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cumsum</span>(freq)</span>
<span id="cb16-2"><a href="richiami-di-statistica-descrittiva.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="do">## (100,140] (140,150] (150,160] (160,170] (170,190] (190,200] </span></span>
<span id="cb16-3"><a href="richiami-di-statistica-descrittiva.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="do">##       141       276       419       558       840      1000</span></span></code></pre></div>
<p>Una distribuzione di frequenze può essere rappresentata con un grafico a torta, che, in R, può essere disegnato con le funzioni <code>pie()</code>. Il grafico sottostante è abbastanza banale, in quanto le classi sono più o meno di ampiezza equivalente, dato che abbiamo utilizzato un campionamento da una distribuzione uniforme.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="richiami-di-statistica-descrittiva.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="fu">table</span>(freq))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:figName243"></span>
<img src="_main_files/figure-html/figName243-1.png" alt="Rappresentazione di una distribuzione di frequenze con un grafico a torta" width="70%" />
<p class="caption">
Figura 3.4: Rappresentazione di una distribuzione di frequenze con un grafico a torta
</p>
</div>
</div>
<div id="connessione-1" class="section level3 hasAnchor" number="3.3.3">
<h3><span class="header-section-number">3.3.3</span> Connessione<a href="richiami-di-statistica-descrittiva.html#connessione-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Consideriamo il dataset ‘HairEyeColor’, disponibile nell’installazione di base di R e relativo al colore degli occhi e dei capelli di 520 studenti di statistica. La tabella delle contingenze, per le femmine, è la seguente:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="richiami-di-statistica-descrittiva.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(HairEyeColor)</span>
<span id="cb18-2"><a href="richiami-di-statistica-descrittiva.html#cb18-2" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> HairEyeColor[,,<span class="dv">2</span>]</span>
<span id="cb18-3"><a href="richiami-di-statistica-descrittiva.html#cb18-3" aria-hidden="true" tabindex="-1"></a>tab</span>
<span id="cb18-4"><a href="richiami-di-statistica-descrittiva.html#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="do">##        Eye</span></span>
<span id="cb18-5"><a href="richiami-di-statistica-descrittiva.html#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Hair    Brown Blue Hazel Green</span></span>
<span id="cb18-6"><a href="richiami-di-statistica-descrittiva.html#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="do">##   Black    36    9     5     2</span></span>
<span id="cb18-7"><a href="richiami-di-statistica-descrittiva.html#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="do">##   Brown    66   34    29    14</span></span>
<span id="cb18-8"><a href="richiami-di-statistica-descrittiva.html#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="do">##   Red      16    7     7     7</span></span>
<span id="cb18-9"><a href="richiami-di-statistica-descrittiva.html#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="do">##   Blond     4   64     5     8</span></span></code></pre></div>
<p>Se vogliamo sapere se il colore degli occhi è legato a quello dei capelli, possiamo utilizzare la funzione <code>as.table()</code> per trasformare l’oggetto <code>tab</code> in una tabella di contingenze (in questo caso non sarebbe necessario, visto che ‘tab’ è già una tabella di contingenze) ed applicare la funzione <code>summary()</code>. Oltre al chi quadro, l’output fornisce altre informazioni, che approfondiremo in un prossimo capitolo.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="richiami-di-statistica-descrittiva.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">as.table</span> (tab))</span>
<span id="cb19-2"><a href="richiami-di-statistica-descrittiva.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Number of cases in table: 313 </span></span>
<span id="cb19-3"><a href="richiami-di-statistica-descrittiva.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Number of factors: 2 </span></span>
<span id="cb19-4"><a href="richiami-di-statistica-descrittiva.html#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Test for independence of all factors:</span></span>
<span id="cb19-5"><a href="richiami-di-statistica-descrittiva.html#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="do">##  Chisq = 106.66, df = 9, p-value = 7.014e-19</span></span>
<span id="cb19-6"><a href="richiami-di-statistica-descrittiva.html#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="do">##  Chi-squared approximation may be incorrect</span></span></code></pre></div>
<hr />
</div>
</div>
<div id="altre-letture-2" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Altre letture<a href="richiami-di-statistica-descrittiva.html#altre-letture-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>F. Crivellari (2006). Analisi statistica dei dati con R. Apogeo, Milano.</li>
<li>G. Leti e L. Cerbara (2009). Elementi di statistica descrittiva. Il Mulino Editore, Bologna.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="progettare-un-esperimento.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelli-statistici-ed-analisi-dei-dati.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
