<!DOCTYPE html>
<html lang="en">
<head>
  
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131792052-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-131792052-1');
  </script>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>The broken bridge between biologists and statisticians  | How do we combine errors, in biology? The delta method</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link rel="stylesheet" href="/css/blog.css" />
    <script type="text/javascript"
      src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>    
</head>
<body>

    
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">Home</a>
            <a class="navbar-item" href="/aboutThis">About this site</a>
            <a class="navbar-item" href="/Tutorials">Tutorials</a>
            <a class="navbar-item" href="/_statbook">Book</a>
            <a class="navbar-item" href="/Rpackages">R packages</a>
            <a class="navbar-item" href="/links">Links</a>
            <a class="navbar-item" href="/about">About me</a>
        </div>
    </nav>
    

    
    <section class="hero is-info is-medium">
        <div class="hero-body" style="background-image: url(/img/bg-blog.jpg);">
            <div class="container has-text-centered">
                <br>
                <h1 class="title is-size-1">
                    
                        How do we combine errors, in biology? The delta method
                    
                </h1>
                
            </div>
        </div>
    </section>



<div class="container">
    <div class="section">
    

<div class="columns">
    <div class="column is-9">
        <div class="tile is-child box">
          <p class="subtitle is-size-6 has-text-grey-light">
          Andrea Onofri &middot;&nbsp; Added on May 25, 2019 &middot;
          <i class="far fa-clock"></i>&nbsp;7 min read 
          </p><hr/>
            <div class="content">
                


<p>In a recent post I have shown that we can build linear combinations of model parameters (<a href="https://www.statforbiology.com/2019/stat_general_errorpropagation/">see here</a> ). For example, if we have two parameter estimates, say Q and W, with standard errors respectively equal to <span class="math inline">\(\sigma_Q\)</span> and <span class="math inline">\(\sigma_W\)</span>, we can build a linear combination as follows:</p>
<p><span class="math display">\[Z = AQ + BW + C\]</span></p>
<p>where A, B and C are three coefficients. The standard error for this combination can be obtained as:</p>
<p><span class="math display">\[ \sigma_Z = \sqrt{ A^2 \sigma^2_Q + B^2 \sigma^2_W + 2AB \sigma_{QW} }\]</span></p>
<p>In biology, nonlinear transformations are much more frequent than linear transformations. Nonlinear transformations are, e.g., <span class="math inline">\(Z = exp(Q + W)\)</span>, or, <span class="math inline">\(Z = 1/(Q + W)\)</span>. What is the standard error for these nonlinear transformations? This is not a complex problem, but the solution may be beyond biologists with an average level of statistical proficiency. It is named the ‘delta method’ and it provides the so called ‘delta standard errors’. I thought it might be useful to talk about it, by using a very simple language and a few examples.</p>
<div id="example-1-getting-the-half-life-of-a-herbicide" class="section level1">
<h1>Example 1: getting the half-life of a herbicide</h1>
<p>A herbicide has proven to follow a first order degradation kinetic in soil, with constant degradation rate <span class="math inline">\(k = -0.035\)</span> and standard error equal to <span class="math inline">\(0.00195\)</span>. What is the half-life (<span class="math inline">\(T_{1/2}\)</span>) of this herbicide and its standard error?</p>
<p>Every pesticide chemist knows that the half-life (<span class="math inline">\(T_{1/2}\)</span>) is derived by the degradation rate, according to the following equation:</p>
<p><span class="math display">\[T_{1/2} = \frac{\log(0.5)}{k}\]</span></p>
<p>Therefore, the half-life for our herbicide is:</p>
<pre class="r"><code>Thalf &lt;- log(0.5)/-0.035
Thalf</code></pre>
<pre><code>## [1] 19.80421</code></pre>
<p>But … what is the standard error of this half-life? There is some uncertainty around the estimate of <span class="math inline">\(k\)</span> and it is clear that such an uncertainty should propagate to the estimate of <span class="math inline">\(T_{1/2}\)</span>; unfortunately, the transformation is nonlinear and we cannot use the expression given above for linear transformations.</p>
<div id="the-basic-idea" class="section level2">
<h2>The basic idea</h2>
<p>The basic idea behind the delta method is that most of the simple nonlinear functions, which we use in biology, can be locally approximated by the tangent line through a point of interest. For example, our nonlinear half-life function is <span class="math inline">\(Y = \log(0.5)/X\)</span> and, obviously, we are interested in the point where <span class="math inline">\(X = k = -0.035\)</span>. In the graph below, we have represented our nonlinear function (in black) and its tangent line (in red) through the above point: we can see that the approximation is fairly good in the close vicinity of <span class="math inline">\(X = -0.035\)</span>.</p>
<p><img src="/post/Stat_General_TheDeltaMethod_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>What is the equation of the tangent line? In general, if the nonlinear function is <span class="math inline">\(G(X)\)</span>, you may remember from high school that the slope <span class="math inline">\(m\)</span> of the tangent line is equal to the first derivative of <span class="math inline">\(G(X)\)</span>, that is <span class="math inline">\(G&#39;(X)\)</span>. You may also remember that the equation of a line with slope <span class="math inline">\(m\)</span> through the point <span class="math inline">\(P(X_1, Y_1)\)</span> is <span class="math inline">\(Y - Y_1 = m(X - X_1)\)</span>. As <span class="math inline">\(Y_1 = G(X_1)\)</span>, the tangent line has equation:</p>
<p><span class="math display">\[Y = G(X_1) + G&#39;(X_1)(X - X_1)\]</span></p>
</div>
<div id="we-need-the-derivative" class="section level2">
<h2>We need the derivative!</h2>
<p>In order to write the equation of the red line in the Figure above, we need to consider that <span class="math inline">\(X_1 = -0.035\)</span> and we need to be able to calculate the first derivative of our nonlinear half-life fuction. I am not able to derive the expression of the first derivative for all nonlinear functions and it was a relief for me to discover that R can handle this task in simple ways, e.g. by using the function ‘D()’. For our case, it is:</p>
<pre class="r"><code>D(expression(log(0.5)/X), &quot;X&quot;)</code></pre>
<pre><code>## -(log(0.5)/X^2)</code></pre>
<p>Therefore, we can use this R function to calculate the slope <span class="math inline">\(m\)</span> of the tangent line in the figure above:</p>
<pre class="r"><code>X &lt;- -0.035
m &lt;- eval( D(expression(log(0.5)/X), &quot;X&quot;) )
m</code></pre>
<pre><code>## [1] 565.8344</code></pre>
<p>We already know that <span class="math inline">\(G(-0.035) = 19.80421\)</span>. Therefore, we can write the equation of the tangent line (red line in the graph above):</p>
<p><span class="math display">\[Y = 19.80421 + 565.8344 \, (X + 0.035)\]</span></p>
<p>that is:</p>
<p><span class="math display">\[Y = 19.80421 + 565.8344 \, X + 565.8344 \cdot 0.035 = 39.60841 + 565.8344 \, X\]</span></p>
</div>
<div id="replacing-a-curve-with-a-line" class="section level2">
<h2>Replacing a curve with a line</h2>
<p>Now, we have two functions:</p>
<ol style="list-style-type: decimal">
<li>the original nonlinear half-life function <span class="math inline">\(Y = \log(0.5)/X\)</span>$</li>
<li>a new linear function (<span class="math inline">\(Y = 39.60841 + 565.8344 \, X\)</span>), that is a very close approximation to the previous one, at least near to the point <span class="math inline">\(X = -0.035\)</span>, which we are interested in.</li>
</ol>
<p>Therefore, we can approximate the former with the latter! If we use the linear function, we see that the half-life is:</p>
<pre class="r"><code>39.60841 + 565.8344 * -0.035</code></pre>
<pre><code>## [1] 19.80421</code></pre>
<p>which is what we expected. The advantage is that we can now use the low of propagation of errors to estimate the standard error (see the first and second equation in this post):</p>
<p><span class="math display">\[ \sigma_{ \left[ 39.60841 + 565.8344 \, X \right]} = \sqrt{ 562.8344^2 \, \sigma^2_X}\]</span></p>
<p>Here we go:</p>
<pre class="r"><code>sqrt( m^2 * (0.00195 ^ 2) )</code></pre>
<pre><code>## [1] 1.103377</code></pre>
</div>
<div id="in-general" class="section level2">
<h2>In general…</h2>
<p>If we have a nonlinear transformation <span class="math inline">\(G(X)\)</span>, the standard error for this transformation is approximated by knowing the first derivative <span class="math inline">\(G&#39;(X)\)</span> and the standard error of <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[\sigma_{G(X)}  \simeq \sqrt{ [G&#39;(X)]^2 \, \sigma^2_X }\]</span></p>
</div>
</div>
<div id="example-2-a-back-transformed-count" class="section level1">
<h1>Example 2: a back-transformed count</h1>
<p>A paper reports that the mean number of microorganisms in a substrate, on a logarithmic scale, was <span class="math inline">\(X_1 = 5\)</span> with standard error <span class="math inline">\(\sigma = 0.84\)</span>. It is easy to derive that the actual number of micro-organisms was <span class="math inline">\(\exp{5} = 148.4132\)</span>; what is the standard error of the back-transformed mean?</p>
<p>The first derivative of our nonlinear function is:</p>
<pre class="r"><code>D(expression(exp(X)), &quot;X&quot;)</code></pre>
<pre><code>## exp(X)</code></pre>
<p>and thus the slope of the tangent line is:</p>
<pre class="r"><code>X &lt;- 5
m &lt;- eval( D(expression(exp(X)), &quot;X&quot;) )
m</code></pre>
<pre><code>## [1] 148.4132</code></pre>
<p>According to the function above, the standard error for the back-transformed mean is:</p>
<pre class="r"><code>sigma &lt;- 0.84
sqrt( m^2 * sigma^2 )</code></pre>
<pre><code>## [1] 124.6671</code></pre>
</div>
<div id="example-3-selenium-concentration-in-olive-drupes" class="section level1">
<h1>Example 3: Selenium concentration in olive drupes</h1>
<p>The concentration of selenium in olive drupes was found to be <span class="math inline">\(3.1 \, \mu g \,\, g^{-1}\)</span> with standard error equal to 0.8. What is the intake of selenium when eating one drupe? Please, consider that one drupe weights, on average, 3.4 g (SE = 0.31) and that selenium concentration and drupe weight show a covariance of 0.55.</p>
<p>The amount of selenium is easily calculated as:</p>
<pre class="r"><code>X &lt;- 3.1; W = 3.4
X * W</code></pre>
<pre><code>## [1] 10.54</code></pre>
<p>Delta standard errors can be obtained by considering the partial derivatives for each of the two variables:</p>
<pre class="r"><code>mX &lt;- eval( D(expression(X*W), &quot;X&quot;) )
mW &lt;- eval( D(expression(X*W), &quot;W&quot;) )</code></pre>
<p>and combining them as follows:</p>
<pre class="r"><code>sigmaX &lt;- 0.8; sigmaW &lt;- 0.31; sigmaXW &lt;- 0.55
sqrt( (mX^2)*sigmaX^2 + (mW^2)*sigmaW^2 + 2*X*W*sigmaXW )</code></pre>
<pre><code>## [1] 4.462726</code></pre>
<p>For those of you who would like to get involved with matrix notation: we can reach the same result via matrix multiplication (see below). This might be easier when we have more than two variables to combine.</p>
<pre class="r"><code>der &lt;- matrix(c(mX, mW), 1, 2)
sigma &lt;- matrix(c(sigmaX^2, sigmaXW, sigmaXW, sigmaW^2), 2, 2, byrow = T)
sqrt( der %*% sigma %*% t(der) )</code></pre>
<pre><code>##          [,1]
## [1,] 4.462726</code></pre>
</div>
<div id="the-delta-method-with-r" class="section level1">
<h1>The delta method with R</h1>
<p>In R there is a shortcut function to calculate delta standard errors, that is available in the ‘car’ package. In order to use it, we need to have:</p>
<ol style="list-style-type: decimal">
<li>a named vector for the variables that we have to combine</li>
<li>an expression for the transformation</li>
<li>a variance-covariance matrix</li>
</ol>
<p>For the first example, we have:</p>
<pre class="r"><code>obj &lt;- c(&quot;k&quot; = -0.035)
sigma &lt;- matrix(c(0.00195^2), 1, 1)

library(car)</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre class="r"><code>deltaMethod(object = obj, g=&quot;log(0.5)/k&quot;, vcov = sigma)</code></pre>
<pre><code>##            Estimate       SE    2.5 %   97.5 %
## log(0.5)/k 19.80421 1.103377 17.64163 21.96678</code></pre>
<p>For the second example:</p>
<pre class="r"><code>obj &lt;- c(&quot;X1&quot; = 5)
sigma &lt;- matrix(c(0.84^2), 1, 1)
deltaMethod(object = obj, g=&quot;exp(X1)&quot;, vcov = sigma)</code></pre>
<pre><code>##         Estimate       SE     2.5 %   97.5 %
## exp(X1) 148.4132 124.6671 -95.92978 392.7561</code></pre>
<p>For the third example:</p>
<pre class="r"><code>obj &lt;- c(&quot;X&quot; = 3.1, &quot;W&quot; = 3.4)
sigma &lt;- matrix(c(0.8^2, 0.55, 0.55, 0.31^2), 2, 2, byrow = T)
deltaMethod(object = obj, g=&quot;X * W&quot;, vcov = sigma)</code></pre>
<pre><code>##       Estimate       SE    2.5 %   97.5 %
## X * W    10.54 4.462726 1.793218 19.28678</code></pre>
<p>The function ‘deltaMethod()’ is very handy to be used in connection with model objects, as we do not need to provide anything, but the transformation function. But this is something that requires another post!</p>
<p>However, two final notes relating to the delta method need to be pointed out here:</p>
<ol style="list-style-type: decimal">
<li>the delta standard error is always approximate;</li>
<li>if the original variables are gaussian, the transformed variable, usually, is not gaussian.</li>
</ol>
<p>Thanks for reading!</p>
</div>

            </div>
        </div>
    </div>
    <div class="column is-3">
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Tags</h1>
        <div class="tags">
        
            <span class="tag"><a href="/tags/agricensdata">agricensdata</a></span>
        
            <span class="tag"><a href="/tags/aomisc">aomisc</a></span>
        
            <span class="tag"><a href="/tags/asreml">asreml</a></span>
        
            <span class="tag"><a href="/tags/blogdown">blogdown</a></span>
        
            <span class="tag"><a href="/tags/correlation">correlation</a></span>
        
            <span class="tag"><a href="/tags/delta_method">delta_method</a></span>
        
            <span class="tag"><a href="/tags/drcseedgerm">drcseedgerm</a></span>
        
            <span class="tag"><a href="/tags/drm">drm</a></span>
        
            <span class="tag"><a href="/tags/error_propagation">error_propagation</a></span>
        
            <span class="tag"><a href="/tags/linear_models">linear_models</a></span>
        
            <span class="tag"><a href="/tags/mixed_models">mixed_models</a></span>
        
            <span class="tag"><a href="/tags/multi_environment_studies">multi_environment_studies</a></span>
        
            <span class="tag"><a href="/tags/nlme">nlme</a></span>
        
            <span class="tag"><a href="/tags/nonlinear_regression">nonlinear_regression</a></span>
        
            <span class="tag"><a href="/tags/r">r</a></span>
        
            <span class="tag"><a href="/tags/seed_germination">seed_germination</a></span>
        
            <span class="tag"><a href="/tags/split_plot">split_plot</a></span>
        
            <span class="tag"><a href="/tags/time_to_event_models">time_to_event_models</a></span>
        
            <span class="tag"><a href="/tags/variance">variance</a></span>
        
        </div>          
    </div>
</div><br>
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Recent posts</h1>
        
            <h1><a href="/2019/stat_nlmm_interaction/">Fitting &#39;complex&#39; mixed models with &#39;nlme&#39;: Example #4</a></h1>
            <time class="has-text-grey-light is-size-7">13 September 2019</time>
        
            <h1><a href="/2019/stat_nlmm_designconstraints/">Fitting &#39;complex&#39; mixed models with &#39;nlme&#39;: Example #3</a></h1>
            <time class="has-text-grey-light is-size-7">13 September 2019</time>
        
            <h1><a href="/2019/stat_lmm_2-wayssplitrepeated/">Fitting &#39;complex&#39; mixed models with &#39;nlme&#39;: Example #2</a></h1>
            <time class="has-text-grey-light is-size-7">13 September 2019</time>
        
            <h1><a href="/2019/stat_lmm_environmentalvariance/">Fitting &#39;complex&#39; mixed models with &#39;nlme&#39;. Example #1</a></h1>
            <time class="has-text-grey-light is-size-7">20 August 2019</time>
        
            <h1><a href="/2019/stat_survival_comparinglots/">Germination data and time-to-event methods: comparing germination curves</a></h1>
            <time class="has-text-grey-light is-size-7">20 July 2019</time>
        
    </div>
</div>
    <br>
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Archives</h1>
        
            <a href="/archives/2019">2019</a> (15)<br>
        
            <a href="/archives/2018">2018</a> (2)<br>
        
            <a href="/archives/2014">2014</a> (1)<br>
        
    </div>
</div>

    </div>
</div>


    </div>
</div>
<footer class="footer has-background-grey-darker has-text-white">
    <div class="content has-text-centered">
        <p>
             <span class="icon is-large"><a href="mailto:andrea.onofri@unipg.it" class="mysocial"><i class="far fa-envelope-open fa-3x"></i></a></span>&nbsp;&nbsp;
            <span class="icon is-large"><a href="https://github.com/OnofriAndreaPG/" class="mysocial"><i class="fab fa-github fa-3x"></i></a></span>&nbsp;&nbsp;
                       <span class="icon is-large"><a href="https://www.r.project.org/" class="mysocial"><i class="fab fa-r-project fa-3x"></i></a></span>&nbsp;&nbsp;

            <br><br>
            Copyright &copy; The broken bridge between biologists and statisticians, 2019 - Theme by <a href="https://jeffprod.com" class="mysocial">JeffProd.com</a>
            - <a class="mysocial" href="/aboutThis">About this site</a>
        </p>
    </div>
</footer>

<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
</body>
</html>
