<!DOCTYPE html>
<html lang="en">
<head>
  
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131792052-1"></script>
  
  <script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-131792052-1');
  </script>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Fixing the bridge between biologists and statisticians  | Dealing with correlation in designed field experiments: part I</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css" />
    <link rel="stylesheet" href="https://www.statforbiology.com/css/blog.css" />
       
</head>
<body>

    
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://www.statforbiology.com/">Home</a>
            <a class="navbar-item" href="https://www.statforbiology.com/aboutthis" >About this site</a>
            <a class="navbar-item" href="https://www.statforbiology.com/tutorials" >Tutorials</a>
            <a class="navbar-item" href="https://www.statforbiology.com/_Statbook" >Book (Italian)</a>
            <a class="navbar-item" href="https://www.statforbiology.com/_StatbookEng" >Book (English)</a>
            <a class="navbar-item" href="https://www.statforbiology.com/rpackages" >R packages</a>
            <a class="navbar-item" href="https://www.statforbiology.com/recentcourses" >Stat Courses</a>
            <a class="navbar-item" href="https://www.statforbiology.com/links" >Links</a>
            <a class="navbar-item" href="https://www.statforbiology.com/about" >About me</a>
        </div>
    </nav>
    

    
    <section class="hero is-info is-medium">
        <div class="hero-body" style="background-image: url(https://www.statforbiology.com/img/bg-blog.jpg);">
            <div class="container has-text-centered">
                <br>
                <h1 class="title is-size-1">
                    
                        Dealing with correlation in designed field experiments: part I
                    
                </h1>
                
            </div>
        </div>
    </section>



<div class="container">
    <div class="section">
    

<div class="columns">
    <div class="column is-9">
        <div class="tile is-child box">
          <p class="subtitle is-size-6 has-text-grey-light">
          Andrea Onofri &middot;&nbsp; Added on April 30, 2019 &middot;
          <i class="far fa-clock"></i>&nbsp;7 min read 
          </p><hr/>
            <div class="content">
                


<div id="observations-are-grouped" class="section level1">
<h1>Observations are grouped</h1>
<p>When we have recorded two traits in different subjects, we can be interested in describing their joint variability, by using the Pearson’s correlation coefficient. That’s ok, altough we have to respect some basic assumptions (e.g. linearity) that have been detailed elsewhere (<a href="https://www.statforbiology.com/2019/stat_general_correlation_alookat/">see here</a>). Problems may arise when we need to test the hypothesis that the correlation coefficient is equal to 0. In this case, we need to make sure that all the couples of observations are taken on independent subjects.</p>
<p>Unfortunately, this is most often false whenever measures are taken from designed field experiments. In this case, observations may be grouped by one or more treatment/blocking factors. This has been clearly described by Bland and Altman (1994); we would like to give an example that is more closely related to plant/crop science. Think about a genotype experiment, where we compare the behaviour of several genotypes in a randomised blocks design. Usually, we do not only measure yield. We also measure other traits, such as crop height. At the end of the experiment, we might be interested in reporting the correlation between yield and height. How should we proceed? It would seem an easy task, but it is not.</p>
<p>Let’s assume that we have a randomised blocks design, with 27 genotypes and 3 replicates. For each plot, we recorded two traits, i.e. yield and the weight of thousand kernels (TKW). In the end, we have 81 plots and just as many couples of measures in all. We will use the dataset ‘WheatQuality.csv’, that is available on ‘gitHub’.</p>
<pre class="r"><code>library(Hmisc)
library(knitr)
library(plyr)
dataset &lt;- read.csv(&quot;https://www.casaonofri.it/_datasets/WheatQuality.csv&quot;, header=T)
head(dataset)</code></pre>
<pre><code>##     Genotype Block Height  TKW Whectol Yield
## 1 arcobaleno     1     90 44.5    83.2 64.40
## 2 arcobaleno     2     90 42.8    82.2 60.58
## 3 arcobaleno     3     88 42.7    83.1 59.42
## 4       baio     1     80 40.6    81.8 51.93
## 5       baio     2     75 42.7    81.3 51.34
## 6       baio     3     76 41.1    81.1 47.78</code></pre>
</div>
<div id="how-many-correlations" class="section level1">
<h1>How many correlations?</h1>
<p>It may be tempting to consider the whole lot of measures and calculate the correlation coefficient between yield and TKW. This is the result:</p>
<pre class="r"><code>ra &lt;- with(dataset, rcorr(Yield, TKW) )
ra$r[1,2] #Correlation coefficient</code></pre>
<pre><code>## [1] 0.540957</code></pre>
<pre class="r"><code>ra$P[1,2] #P-level</code></pre>
<pre><code>## [1] 1.850931e-07</code></pre>
<p>We observe a positive correlation, and <span class="math inline">\(r\)</span> seems to be significantly different from 0. Therefore, we would be encouraged to conclude that plots with a high value on yield tend to have a high value on TKW, as well. Unfortunately, such a conclusion is not supported by the data.</p>
<p>Indeed, the test of significance is clearly invalid, as the 81 plots are not independent; they are grouped by block and genotype and we are totally neglecting these two effects. Are we sure that the same correlation holds for all genotypes/blocks? Let’s check this.</p>
<pre class="r"><code>wCor &lt;- function(x) cor(x$Yield, x$TKW)
wgCors &lt;- ddply(dataset, ~Genotype, wCor)
wgCors</code></pre>
<pre><code>##       Genotype         V1
## 1   arcobaleno  0.9847228
## 2         baio  0.1611952
## 3      claudio -0.9993872
## 4     colorado  0.9837293
## 5     colosseo  0.4564855
## 6        creso -0.5910193
## 7       duilio -0.9882330
## 8       gianni -0.7603802
## 9       giotto  0.9520211
## 10      grazia  0.4980828
## 11       iride  0.7563338
## 12    meridano  0.1174342
## 13      neodur  0.4805871
## 14      orobel  0.8907754
## 15 pietrafitta -0.9633891
## 16  portobello  0.9210135
## 17   portofino -0.9900764
## 18   portorico  0.1394211
## 19       preco  0.9007067
## 20    quadrato -0.5840238
## 21    sancarlo -0.6460670
## 22      simeto -0.4051779
## 23       solex -0.6066363
## 24 terrabianca -0.4076416
## 25       verdi  0.5801404
## 26     vesuvio -0.7797493
## 27    vitromax -0.8056514</code></pre>
<pre class="r"><code>wbCors &lt;- ddply(dataset, ~Block, wCor)
wbCors</code></pre>
<pre><code>##   Block        V1
## 1     1 0.5998137
## 2     2 0.5399990
## 3     3 0.5370398</code></pre>
<p>As for the genotypes, we have 27 correlation coefficients, ranging from -0.999 to 0.985. We only have three couples of measurements per genotype and it is clear that this is not much, to reliably estimate a correlation coefficient. However, it is enough to be suspicious about the extent of correlation between yield and TKW, as it may depend on the genotype.</p>
<p>On the other hand, the correlation within blocks is more constant, independent on the block and similar to the correlation between plots.</p>
<p>It may be interesting to get an estimate of the average within-group correlation. To this aim, we can perform two separate ANOVAs (one per trait), including all relevant effects (blocks and genotypes) and calculate the correlation between the residuals:</p>
<pre class="r"><code>mod1 &lt;- lm(Yield ~ factor(Block) + Genotype, data = dataset)
mod2 &lt;- lm(TKW ~ factor(Block) + Genotype, data = dataset)
wCor &lt;- rcorr(residuals(mod1), residuals(mod2))
wCor$r</code></pre>
<pre><code>##            x          y
## x 1.00000000 0.03133109
## y 0.03133109 1.00000000</code></pre>
<pre class="r"><code>wCor$P</code></pre>
<pre><code>##           x         y
## x        NA 0.7812693
## y 0.7812693        NA</code></pre>
<p>The average within-group correlation is very small and unsignificant. Let’s think about this correlation: residuals represent yield and TKW values for all plots, once the effects of blocks and genotypes have been removed. A high correlation of residuals would mean that, letting aside the effects of the block and genotype to which it belongs, a plot with a high value on yield also shows a high value on TKW. The existence of such correlation is clearly unsopported by our dataset.</p>
<p>As the next step, we could consider the means for genotypes/blocks and see whether they are correlated. Blocks and genotypes are independent and, in principle, significance testing is permitted. However, this is not recommended with block means, as three data are too few to make tests.</p>
<pre class="r"><code>means &lt;- ddply(dataset, ~Genotype, summarise, Mu1=mean(Yield), Mu2 = mean(TKW))
rgPear &lt;- rcorr( as.matrix(means[,2:3]) )
rgPear$r</code></pre>
<pre><code>##           Mu1       Mu2
## Mu1 1.0000000 0.5855966
## Mu2 0.5855966 1.0000000</code></pre>
<pre class="r"><code>rgPear$P</code></pre>
<pre><code>##            Mu1        Mu2
## Mu1         NA 0.00133149
## Mu2 0.00133149         NA</code></pre>
<pre class="r"><code>means &lt;- ddply(dataset, ~Block, summarise, Mu1=mean(Yield), Mu2 = mean(TKW))
rbPear &lt;- cor( as.matrix(means[,2:3]) )
rbPear</code></pre>
<pre><code>##             Mu1         Mu2
## Mu1  1.00000000 -0.08812544
## Mu2 -0.08812544  1.00000000</code></pre>
<p>We note that the correlation between genotype means is high and significant. On the contrary, the correlation between block means is near to 0.</p>
</div>
<div id="and-so-what" class="section level1">
<h1>And so what?</h1>
<p>At this stage, you may be confused… Let’s try to clear the fog.</p>
<p>Obtaining a reliable measure of correlation from designed experiments is not obvious. Indeed, in every designed field experiment we have groups of subjects and there are several possible types of correlation:</p>
<ol style="list-style-type: decimal">
<li>correlation between plot measurements</li>
<li>correlation between the residuals</li>
<li>correlation between treatment/block means</li>
</ol>
<p>All these correlations should be investigated and used for interpretation.</p>
<ol style="list-style-type: decimal">
<li>The ‘naive’ correlation between the plot measurements is very easily calculated, but it is grossy misleading. Indeed, it disregards the treatment/block effects and it does not permit hypotheses testing, as the subjects are not independent. In this example, looking at the ‘naive’ correlation coefficient, we would wrongly conclude that plots with high yield also have high TKW, while further analyses show that this is not true, in general. We would reasonably suggest that the ‘naive’ correlation coefficient is never used for interpretation.</li>
<li>The correlation between the residuals is a reliable measure of joint variation, because the experimental design is adequately referenced, by removing the effects of tratments/blocks. In this example, residuals are not correlated. Further analyses show that the correlation between yield and TKW, if any, may depend on the genotype, while it does not depend on the block.</li>
<li>The correlation between treatment/block means permits to assess whether the treatment/block effects on the two traits are correlated. In this case, while we are not allowed to conclude that yield and TKW are, in general, correlated, we can conclude that the genotypes with a high level of yield also show a high level of TKW.</li>
</ol>
</div>
<div id="take-home-message" class="section level1">
<h1>Take-home message</h1>
<p>Whenever we have data from designed field experiments, our correlation analyses should never be limited to the calculation of the ‘naive’ correlation coefficient between the observed values. This may not be meaningful! On the contrary, our interpretation should be mainly focused on the correlation between residuals and on the correlation between the effects of treatments/blocks.</p>
<p>An elegant and advanced method to perform sound correlation analyses on data from designed field experiments has been put forward by Piepho (2018), within the frame of mixed models. Such an approach will be described in another post.</p>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<ol style="list-style-type: decimal">
<li>Bland, J.M., Altman, D.G., 1994. Statistics Notes: Correlation, regression, and repeated data. BMJ 308, 896–896.</li>
<li>Piepho, H.-P., 2018. Allowing for the structure of a designed experiment when estimating and testing trait correlations. The Journal of Agricultural Science 156, 59–70.</li>
</ol>
</div>

            </div>
        </div>
    </div>
    <div class="column is-3">
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Tags</h1>
        <div class="tags">
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/agricensdata">agricensdata</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/ammi_analysis">ammi_analysis</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/aomisc">aomisc</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/asreml">asreml</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/bayesian_stat">bayesian_stat</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/biplot">biplot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/blogdown">blogdown</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/boxplot">boxplot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/case_study">case_study</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/climate_data">climate_data</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/correlation">correlation</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/cva">cva</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/data_management">data_management</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/delta_method">delta_method</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/descriptive_statistics">descriptive_statistics</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/diallel_models">diallel_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/dplyr">dplyr</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/drcseedgerm">drcseedgerm</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/drcte">drcte</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/drm">drm</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/error_propagation">error_propagation</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/gge_analysis">gge_analysis</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/ggh4x">ggh4x</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/ggplot">ggplot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/gls">gls</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/gnlht">gnlht</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/jags">jags</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/linear_models">linear_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/lm">lm</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/lmdiallel">lmdiallel</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/lme">lme</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/long_term_experiments">long_term_experiments</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/meta_analysis">meta_analysis</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/metafor">metafor</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/mixed_models">mixed_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/multi_environment_studies">multi_environment_studies</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/multivariate_stat">multivariate_stat</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/nlme">nlme</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/nls">nls</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/nonlinear_regression">nonlinear_regression</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/p-values">p-values</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/pca">pca</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/percentiles">percentiles</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/plot">plot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/qq_plot">qq_plot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/r">r</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/regression">regression</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/repeated_measures">repeated_measures</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/seed_germination">seed_germination</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/split_plot">split_plot</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/statforbiology">statforbiology</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/statistical_inference">statistical_inference</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/subsampling">subsampling</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/tidyverse">tidyverse</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/time_to_event_models">time_to_event_models</a></span>
        
            <span class="tag"><a href="https://www.statforbiology.com/tags/variance">variance</a></span>
        
        </div>          
    </div>
</div><br>
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Recent posts</h1>
        
            <h1><a href="https://www.statforbiology.com/2024/stat_general_errorpropagation/">How do we combine errors? The linear case</a></h1>
            <time class="has-text-grey-light is-size-7">22 November 2024</time>
        
            <h1><a href="https://www.statforbiology.com/2024/stat_general_thedeltamethod_edit/">How do we combine errors, in biology? The delta method</a></h1>
            <time class="has-text-grey-light is-size-7">22 November 2024</time>
        
            <h1><a href="https://www.statforbiology.com/2024/r_ggplot_dualscaledaxes/">Plotting weather data with ggplot()</a></h1>
            <time class="has-text-grey-light is-size-7">6 June 2024</time>
        
            <h1><a href="https://www.statforbiology.com/2024/stat_lm_checkassumptions/">Here is why I don&#39;t care about the Levene&#39;s test</a></h1>
            <time class="has-text-grey-light is-size-7">15 March 2024</time>
        
            <h1><a href="https://www.statforbiology.com/2024/stat_nls_paircomp2/">Pairwise comparisons in nonlinear regression</a></h1>
            <time class="has-text-grey-light is-size-7">23 February 2024</time>
        
    </div>
</div>
    <br>
        <div class="card">
    <div class="card-content">
        <h1 class="title is-5">Archives</h1>
        
            <a href="https://www.statforbiology.com/archives/2024">2024</a> (5)<br>
        
            <a href="https://www.statforbiology.com/archives/2023">2023</a> (12)<br>
        
            <a href="https://www.statforbiology.com/archives/2022">2022</a> (8)<br>
        
            <a href="https://www.statforbiology.com/archives/2021">2021</a> (16)<br>
        
            <a href="https://www.statforbiology.com/archives/2020">2020</a> (13)<br>
        
            <a href="https://www.statforbiology.com/archives/2019">2019</a> (13)<br>
        
            <a href="https://www.statforbiology.com/archives/2018">2018</a> (2)<br>
        
            <a href="https://www.statforbiology.com/archives/2014">2014</a> (1)<br>
        
    </div>
</div>

    </div>
</div>


    </div>
</div>
<footer class="footer has-background-grey-darker has-text-white">
    <div class="content has-text-centered">
        <p>
             <span class="icon is-large"><a href="mailto:andrea.onofri@unipg.it" class="mysocial"><i class="far fa-envelope-open fa-3x"></i></a></span>&nbsp;&nbsp;
            <span class="icon is-large"><a href="https://github.com/OnofriAndreaPG/" class="mysocial"><i class="fab fa-github fa-3x"></i></a></span>&nbsp;&nbsp;
           <span class="icon is-large"><a href="https://twitter.com/onofriandreapg" class="mysocial"><i class="fab fa-twitter fa-3x"></i></a></span>&nbsp;&nbsp;
            <span class="icon is-large"><a href="https://www.r-project.org/" class="mysocial"><i class="fab fa-r-project fa-3x"></i></a></span>&nbsp;&nbsp;
 
<br>
<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">Copyright &copy; <a property="dct:title" rel="cc:attributionURL" href="https://www.statforbiology.com/aboutthis/">Fixing the bridge between biologists and statisticians</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.statforbiology.com/about/">Andrea Onofri</a> is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a> - Theme by <a href="https://jeffprod.com" class="mysocial">JeffProd.com</a></p>
            
</div>
</footer>

<script defer src="https://use.fontawesome.com/releases/v5.1.0/js/all.js"></script>
</body>
</html>
